### ISSUE TITLE
`tofu fmt` should allow disabling "align equals signs" to reduce needless diffs

### ISSUE THREAD

**Issue by sodul** [opentofu/opentofu#1041]
### OpenTofu Version

```shell
> ./tofu -version
OpenTofu v1.6.0-rc1
on darwin_arm64
```

### Use Cases

The fact that `fmt` forces all equal signs to be aligned is contrary to the standard style guide of many languages as unnecessary burden and causes needless diffs that increases the potential for merge conflicts, increased number of line wraps, etc...

### Attempted Solutions

Using sed commands such as `sed -ei 's/[ ]+=/ =/'` is dangerous since it could modify comments (harmless) or embedded text data where the space is actually relevant.

### Proposal

Add a cli option or environment variable such as `--equals-align` with various options such as:
- `right`: the default and current behavior.
- `left`: where `=` is always preceded by one space.
- `disabled`: the number of spaces is not changed.

examples:

Right:
```tf
variable "equals_align" {
  description = "how equals should be aligned"
  type        = string
}
```

Left:
```tf
variable "equals_align" {
  description = "how equals should be aligned"
  type = string
}
```

Disabled:
```tf
variable "equals_align" {
  description= "how equals should be aligned"
  type   = string
}
```

Because of this issue we actually avoid using `fmt`. The `main.tf` files in the opentofu repo are themselves inconsistent.
https://github.com/opentofu/opentofu/blob/main/testing/equivalence-tests/tests/data_read/main.tf

### References

This has been reported several times in the original project, I can dig a few mentions if needed.

**Comment by rdtechie** [comment]
I respectfully disagree with this as the `fmt` subcommand is actually a opinionated formatter. As such it should not be configurable. In our company we have `fmt` running in CI and it gives warnings if there are diffs and stops CI. This forces our code submitters to structure the code in the correct way.

**Comment by janosdebugs** [comment]
Thank you for the request @sodul. This feature would, unfortunately, inevitably lead to more formatting features being requested. We would need to create an extensible way to provide formatting options, which requires quite a bit of planning. As the core team is still quite small we don't have the capacity to implement such a feature for now.

**Comment by tmccombs** [comment]
If there isn't any desire to make `tofu fmt` configurable, is there any possibility of changing the style so that it doesn't enforce aligning equals? Or maybe change it so that it leaves the alignment alone? (so that if the equals are aligned, it leaves them alone, but also wont't force alignment of code that isn't already aligned)?

**Comment by yottta** [comment]
> If there isn't any desire to make `tofu fmt` configurable, is there any possibility of changing the style so that it doesn't enforce aligning equals? Or maybe change it so that it leaves the alignment alone? (so that if the equals are aligned, it leaves them alone, but also wont't force alignment of code that isn't already aligned)?

Maintainers reconsidered this recently and was decided that the way `tofu fmt` works today is already well established and it wouldn't benefit from adding such changes.
In case you want to create different formatting rules, you could fork https://github.com/fatih/hclfmt and update it to match your requirements.

**Comment by tmccombs** [comment]
> In case you want to create different formatting rules, you could fork https://github.com/fatih/hclfmt and update it to match your requirements.

it looks like that basically just parses the file as hcl, then writes it back, and used the old hcl v1 library. I think you could do something similar with hcl/v2/hclwrite, but you would basically need to re-implement all of the formatting, since hclwrite doesn't have any levers to pull on how it writes the output out. 

Assuming that is basically how `tofu fmt` works, that would also mean to fix this tofu would either need to fork the hcl library or do it's own reimplementation.  ☹️
