### ISSUE TITLE
Annoying TF bug not fixed for years - wrong EC2 instance IP address

### ISSUE THREAD

**Issue by speller** [opentofu/opentofu#1050]
There's one very annoying bug in TF that is not fixed since 2018: https://github.com/hashicorp/terraform-provider-aws/issues/6781.  I'm facing it regularly when I have to use the internal or public IP address of an instance AND this instance is updated in-place and gets new IP addresses in the same TF run. This can make the whole deployment inconsistent. The issue is not only related to Route53, but to ANY place where you try to use the instance IP address (private or public). For example, configuring other services or apps.

Is there a chance that it will be fixed in OTF soon?

**Comment by janosdebugs** [comment]
Hi @speller, thank you for raising this issue.

Short term answer: currently we are only mirroring the Hashicorp providers, not adding bugfixes to them, which is why the provider repositories have issues disabled on them.

Longer term answer: Most of the team is out for the holidays, but we'll go over all the bugs in January and will decide if we have the capacity to pick up provider issues then.

**Comment by speller** [comment]
@janosdebugs Thank you for the clarification! 🤞 for this issue to be picked up :)

**Comment by cube2222** [comment]
Hey @speller! We've discussed this with the core team, and for now we're not accepting bug reports and changes requests to HashiCorp providers.

Right now we're just mirroring these without any changes, and introducing any changes from our side would make the maintenance overhead of those mirrors much larger. This is not something we currently have the bandwidth for, as we're growing the team.
