### ISSUE TITLE
Audit `internal/` directory to make code more accessible

### ISSUE THREAD

**Issue by nitrocode** [opentofu/opentofu#1051]
### OpenTofu Version

```shell
Latest
```

### Use Cases

For example, terraform.lang contains methods to help run terraform native functions such as format, formatlist, etc

https://github.com/opentofu/opentofu/tree/main/internal

The code that lives in interval prevented me from creating a string template function in a custom provider easily. One workaround would be to fork terraform or to copy and paste a few files to allow my code to run properly. This would be a back and not ideal in case upstream bugs were fixed or new features get added.

Since this is a fork already, it might not be that much effort to change the directory structure for specific modules to make them accessible to other applications

### Attempted Solutions

https://github.com/cloudposse/terraform-provider-utils/pull/55

### Proposal

Some options

1. Move select directories outside of `internal/`
2. Create a new library (or libraries) for these internal functions and have opentofu depend on them

**Comment by janosdebugs** [comment]
Hi @nitrocode there have been several requests to make the `internal` directory available to include as libraries, such as #758.  This issue is unfortunately more complex than simply exposing everything in `internal`. Exposing the entire internals of OpenTofu would put everyone who is using it as a library at risk of having their dependencies broken at any time. In your case, if we exposed that function you needed, but then changed it down the line (e.g. we add an additional parameter), your provider would be broken when you upgrade your OpenTofu dependency. That's not a very pleasant experience.

The right approach in this case would be opening separate issues for individual features that should be exposed. This can then be done either as a deliberate, documented, and supported API, or moved to a separate repo in the OpenTofu org that both you and OpenTofu can consume. If you come across such valuable functions, please open separate issues for them. If you have something specific in mind (e.g. terraform.lang) please feel free to edit this issue to reflect that specific feature you'd need.

Is this approach ok with you or do you feel like we shoud be doing something different?

**Comment by mwarkentin** [comment]
We have a use case which triggered some of this discussion - ours is around interacting with terraform locks. @bukzor-sentryio just opened a detailed issue on terraform itself: https://github.com/hashicorp/terraform/issues/34453

If that makes sense we could open this issue here as well.

**Comment by janosdebugs** [comment]
Thank you for the description @mwarkentin. There have been numerous requests to make OpenTofu more modular and reusable as a library (#810 #758 #544 #382 #381 ) and that is also a direction that makes sense. However, the codebase is quite large so it makes a helps to open specific actionable issues for things that you and your team need and would consume from OpenTofu if they were available. Specific issues, especially when they are paired with a use case description, help us prioritize feature requests.

As a side note, when you open the specialized issues, please describe the feature in its entirety rather than linking to the Terraform repository so we can maintain a clear separation betweeen OpenTofu and Hashicorp's offerings.

**Comment by cube2222** [comment]
As Janos wrote, let's have issues for specific features/functionalities you'd like exposed.

In practice, before we expose anything, we'll have to think about the stability guarantees we're willing to make about the exposed API, so it's not a change we'll be making lightly.
