### ISSUE TITLE
Using OpenTofu with TFE

### ISSUE THREAD

**Issue by dannyibishev** [opentofu/opentofu#1102]
### OpenTofu Version

```shell
Not installed yet.
```

### Use Cases

I would like to have the ability to install opentofu in our terraform enterprise offering. We have stopped upgrading our workspaces since version `1.5.5` which is the version just before the revised licence changes were introduced.

Going forward, my team would like to start using opentofu.

### Attempted Solutions

Could not find any related articles or methods in the latest install documentation for version `1.6.0`

### Proposal

To add opentofu to tfe. I would expect a packaged .zip file along with a sha256 checksum that we can use directly.

You can find instructions of how this is typically done through this support request: https://support.hashicorp.com/hc/en-us/articles/4408248880403-How-to-add-a-Terraform-Version-to-Terraform-Enterprise

**Comment by janosdebugs** [comment]
Hi @dannyibishev both of the requested files are available [in the release](https://github.com/opentofu/opentofu/releases/tag/v1.6.0). However, I'd heavily assume that they would expect the binary to be called `terraform` instead of `tofu`, so I'm not sure this  will work.

**Comment by cube2222** [comment]
Hey @dannyibishev, I would recommend creating a support ticket with HashiCorp for this.

**Comment by dannyibishev** [comment]
Yep you were right. Using the zip and sha checksums won't be enough. This is what I observed with my attempt on a freshly provisioned workspace.

```txt
Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
https://<ommited>/app/<ommited>/<ommited>/runs/run-rp8GsynLkaVkKVev

Waiting for the plan to start...

Operation failed: failed getting Terraform version from CLI: failed getting terraform version: failed starting command "/home/tfc-agent/.tfc-agent/component/terraform/runs/run-rp8GsynLkaVkKVev/bin/terraform version": fork/exec /home/tfc-agent/.tfc-agent/component/terraform/runs/run-rp8GsynLkaVkKVev/bin/terraform: no such file or directory
```

I will reach out and raise a support request with Hashicorp But I have a good feeling that they will not want to support opentofu. :disappointed: 

Is there any chance we can add an alias that points to the opentofu binary?

**Comment by janosdebugs** [comment]
@dannyibishev Terraform is a registered trademark of HashiCorp, so I don't think we'll be distributing any packages with binaries named `terraform` in them as part of OpenTofu releases.

While it would be technically possible to rename or symlink things, we don't recommend it as there is no guarantee that TFE will play nice with binaries that don't behave as expected or output the strings they may be looking for.

Since TFE doesn't support OpenTofu, it's not advisable to use it as it would put you in an unsupported scenario where we can't really help and HashiCorp can decide not to help if something goes wrong. It would be better if they officially supported OpenTofu for you to be on the safe side.
