### ISSUE TITLE
Enable ppc64le Architecture

### ISSUE THREAD

**Issue by mtarsel** [opentofu/opentofu#1130]
### Summary

Enable ppc64le architecture (POWER) for OpenTofu. Public ppc64le resources are available at Oregon State University’s Open Source Lab [1] for testing.

[1] https://osuosl.org/services/powerdev/

### Problem Statement

Expanding the open source ecosystem for ppc64le as well as enabling more users of OpenTofu. There is a need for IaaC project to provision machines in networks without other architectures present.

### User-facing description

Allow users running ppc64le architecture to use OpenTofu in order to be utilized for projects such as OpenShift and PowerVC.

### Technical Description

The OpenTofu core will have to make changes for ppc64le as well as update documentation in the OpenTofu repository. See my fork [1] for an initial Proof of Concept patch and test output. The simple patch I wrote does not include documentation changes. There are public ppc64le machines available for this project including CI [2] and a mirror [3] to host binaries.
[1] https://github.com/mtarsel/opentofu/tree/enable-ppc64le
[2] https://osuosl.org/services/powerdev/request_powerci/
[3] https://ftp2.osuosl.org/pub/ppc64el/

### Rationale and alternatives

The impact is the use of open source software on different hardware platforms.

### Proof of Concept

Check out my fork: https://github.com/opentofu/opentofu/compare/main...mtarsel:opentofu:enable-ppc64le

```
root@41c3803946ab:~/opentofu# ../go/bin/tofu -version
OpenTofu v1.7.0-dev
on linux_ppc64le
root@41c3803946ab:~/opentofu# go version
go version go1.21.6 linux/ppc64le
```

Edit: I am also available on OpenTofu slack to chat

**Comment by yussufsh** [comment]
Thanks @janosdebugs for looking at the request.

>Is your request related to the OpenShift Installer embedding Terraform and potentially replacing it with OpenTofu? If yes, I was under the impression that OpenShift built its own Terraform from source, did that change or am I mistaken there?

This request is not for OpenShift Installer, but the example is given because OpenShift can be installed in UPI (User Provisioned Infrastructure) way where the user creates the infrastructure using OpenTofu or any other tool he likes.

>If no, do you have any specific use cases that would be enabled by us shipping a ppc64le binary? 

One is to run the UPI install scripts on ppc64le machine.
Another use case is where clients have only ppc64le hardware in a network and cannot use x86 machine to run OpenTofu. Let it be for provisioning IBM Cloud or OpenStack resources.

>Also, how would this work since none of the providers have binaries for this architecture?

We build the required providers for ppc64le which we want to use in our templates. The user then configures his local machine to use these custom provider plugins.

**Comment by janosdebugs** [comment]
Thank you @yussufsh we had a very long chat with @mtarsel yesterday on Slack, I'll post the summary shortly.

**Comment by janosdebugs** [comment]
**Dear community, after having a conversation with @mtarsel we'd like to hear from you. If you are a ppc64le user, please comment or react to this issue to show your support for this RFC.**

Several issues remain to be addressed:

1. Currently no provider we know of supports this architecture. OpenTofu is dependent on prebuilt binaries supplied by the provider authors for each platform. If a provider author choses not to build a binary for a platform, OpenTofu will not be able to use that provider on that platform. The provider authors need to be convinced that they should start shipping binaries for ppc64le, which puts them in the same position as us: needing for ppc64le hardware for testing (see below).
2. As part of the OpenTofu project, we ship binaries for a few providers such as AWS. However, these providers are merely mirrors and are maintained by HashiCorp under the MPL license. HashiCorp currently [does not support ppc64le for Terraform](https://github.com/hashicorp/terraform/issues/26522), so it would not be reasonable to ask them to merge ppc64le-specific bugfixes without testing. On the other hand, we currently don't have the infrastructure set up to maintain downstream changes for these providers, nor is this currently something we have the capacity for. Many of our users currently also rely on the providers having an identical behavior.
3. As ppc64le is not a wide-spread architecture, neither the OpenTofu core developers nor the community have easy access to hardware of this sort. This makes solving issues difficult and could potentially block releases. While @mtarsel has volunteered his time to help the project with ppc64le-related issues, at this time no company has committed to officially providing hardware and development time for this platform.
4. In addition to hardware, we would also need to set up a build and test infrastructure connected to GitHub Actions. This would require significant engineering time and more importantly, one of the few people with admin access to our GitHub organization working on this. We would also need to make sure that no secrets can leak via the custom runners.

As an alternative to directly implementing ppc64le support, we would recommend setting up a fork of OpenTofu and of the relevant providers. This fork would help OpenTofu on PowerPC gain traction and show that the architecture receives steady maintenance without taking away resources from the main OpenTofu development. It would also help iron out any technical issues along the way without affecting the main OpenTofu releases. Patches for ppc64le-specific issues could be merged back into the main codebase based on the CI set up on the fork as long as they don't affect other platforms negatively.

We can support the creation of this fork by modifying our configurations so that the build is able to run on the new GitHub organization without changes apart from adding the architecture to the config. This would also benefit the OpenTofu project outside the ppc64le architecture as it would make running the complete release cycle for testing purposes possible.

Once the fork has proven a success and enough experience has been gained in maintaining it, support for ppc64le could possibly be added to the main OpenTofu codebase.

**Comment by mtarsel** [comment]
I would prefer not to have a fork since there already seems to be a strong need for OpenTofu on ppc64le. We can help maintain ppc64le development and testing. I'll answer inline below.

> Currently no provider we know of supports this architecture.

Yes this is true however after some more discussions with other ppc64le users, I have learned that Cloud Automation Manager (CAM) is used by customers with the following providers supported by CAM: Alibaba Cloud, Amazon EC2, Google Cloud, Huawei Cloud, IBM, IBM cloud Kuberenetes Service, Microsoft Azure, Microsoft HyperV, Nutanix, OpenStack, Tencent Cloud, Turbonomic, VMware NSX-T, VMware NSXv, VMware vRealize Automation, and VMware vSphere. The most common used ones are AWS, GCP, IBM Cloud, Azure,  OpenStack, and VMware vSphere so perhaps this could be a good starting point.

In addition, there is a big use case for OpenTofu doing installs of Red Hat OpenShift UPI here [1]. 

> HashiCorp currently does not support ppc64le for Terraform.

Even though Hashicorp does not support ppc64le, we previously had been building the binaries ourselves - there already is a need for this project on ppc64le. Ideally we could have upstream inclusion the same as other architectures. I think if we did make a fork for ppc64le, it would gain traction quickly and then we would have to merge it all later instead of just including ppc64le in OpenTofu at this time.

> we currently don't have the infrastructure set up to maintain downstream changes for these providers

What infrastructure would be needed for this exactly? Can this work [2]? 

> neither the OpenTofu core developers nor the community have easy access to hardware of this sort.

ppc64le hardware is available at OSU OSL and I can help out where needed. Public ppc64le services are offered here [2]

> we would also need to set up a build and test infrastructure connected to GitHub Actions

Myself or someone on our team can help setup at whatever level is most comfortable with everyone. Additionally, we can absolutely help maintain the ppc64le development in the OpenTofu repo as well as the testing with ppc64le infrastructure (myself personally or someone else on the same team). 

[1] https://github.com/ocp-power-automation
[2] https://osuosl.org/services/powerdev/

**Comment by cube2222** [comment]
Hey @mtarsel, Kuba, the technical lead of the OpenTofu project here. Thank you for submitting the issue and providing us with information on ppc64le and possible ways to come by the resources to support ppc64le in OpenTofu.

We make development decisions based on community feedback and need and this is a large ask in terms of core developer time and long-term maintenance commitment. We would need feedback from the wider community on their ppc64le use cases, or an official commitment from IBM to support this effort long term with at least some development resources to consider supporting this upstream. I understand you currently have a use-case for ppc64Ie-built OpenTofu, and for now I'd recommend creating an internal or public-facing fork / build pipeline to facilitate this.

We'll be happy to incorporate any bug fixes you need to make upstream as long as they don't negatively affect other platforms, so that there aren't any big patches you have to maintain across the evolution of the OpenTofu codebase, and the overall burden of this undertaking is reduced.

**Comment by mtarsel** [comment]
We'll review - for now we'll close out the issue.

**Comment by mikelolasagasti** [comment]
@mtarsel isn't this something downstream can provide? 

Fedora and probably EPEL will get OpenTofu including ppc64le builds. https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=2258867
