### ISSUE TITLE
Function to transform a list of objects into a map, with key being any object field and value the object itself

### ISSUE THREAD

**Issue by dennislapchenko** [opentofu/opentofu#1248]
### OpenTofu Version

```shell
OpenTofu v1.6.1
```

### Use Cases

One of the most commonly executed operations is `list(object({})` transformation into a `map(object({})` in order to use in `for_each` resources. This constant transformation isnt very hard to do, however a function (like in some programming languages) could definitely ease up this process.

### Attempted Solutions

Currently only an explicit transformation is possible.
```
locals {
  object_list = [
    {
      name = "foo"
      dimensions = "bar"
    }
  ]
}

module "mymodule" {
  ...
  for_each = {
    for obj in local.object_list: obj.name => obj
  }
  ...
}
```

### Proposal

```
locals {
  object_list = [
    {
      name = "foo"
      dimensions = "bar"
    }
  ]
}

module "mymodule" {
  ...
  for_each = listtransform(local.object_list, "name")
  ...
}
```

**Comment by janosdebugs** [comment]
Hey @dennislapchenko thank you for this issue. We discussed this with the core team and since functions implemented in providers are coming to Terraform and we'll be building our own version of it in OpenTofu, we feel that this could be implemented using a provider once that feature hits. As a consequence, we decided that we will not be implementing this function in the OpenTofu core.
