### ISSUE TITLE
Add support for `count` and conditional expressions in the import block

### ISSUE THREAD

**Issue by RoozbehShafiee** [opentofu/opentofu#1274]
### OpenTofu Version

```shell
1.6.1
```

### Use Cases

The import block could benefit greatly from supporting `count`.

Importing resources currently poses a challenge when dealing with count or conditional expressions. Introducing support for such scenarios would enhance the import block's functionality as part of a module. By enabling the definition of an optional resource ID as a variable, users could effortlessly import existing resources alongside those managed by OpenTofu.

### Attempted Solutions

No possibility of importing resources using `count` or conditional expressions

### Proposal

```
import {
  count = var.resource_id == null ? 0 : 1

  id = var.resource_id
  to = aws_s3_bucket.bucket[each.value.key]
}

resource "aws_s3_bucket" "bucket" {
  for_each = local.bucket_ids
  ...
}
```

AND

```
import {
  for_each = local.bucket_ids

  id = each.value.import == true ? each.value.import_id : null
  to = each.value.import == true ? each.value.id : null
}

resource "aws_s3_bucket" "bucket" {
  for_each = local.bucket_ids
  ...
}
```

### References

There is no reference!

**Comment by RLRabinowitz** [comment]
Hey @RoozbehShafiee , thank you for filing this issue!

I would like to mention a couple of things about the `import` block:
- `import` blocks are not allowed inside of a module. We assume the a module is mostly a "blackbox", and that a module author would really want to allow for `import`s as part of the module's configuration. It is the responsibility of the user of the module to import into a resource of the module, if they'd like to do that. With this assumption in mind, there'd be no need for a conditional `import` block, as the root module's author could decide whether or not to import
- We're currently working on [adding `for_each` support for the `import` block](https://github.com/opentofu/opentofu/issues/1033). We are not currently adding a `count` field, as we didn't see a specific use-case for needing to have `count` in the `import` block, and everything that could be done using `count` field could also be made more explicit using a `for_each` field.
- Once `for_each` has been implemented, then the `for_each` map itself could help with the use-case of conditional import - Simply adjust the map according to the resources you'd like to import. You could even have the `for_each` field be an empty map

I would appreciate some clarification regarding the use-case that this should help solve - Is this coming from a module author perspective, who'd like to provide module variables that'll help users of the modules to import existing resources instead of creating them?

**Comment by RoozbehShafiee** [comment]
To be honest, I have no idea how the `for_each` function in the import block will work in OpenTofu, but I'm really looking forward to testing it. However, based on my use case, this feature doesn't work with Terraform 1.7.3 and conditional expressions. The `for_each` function, along with support for conditional expressions, can almost resolve the issue that `count` does. Additionally, the empty map feature is awesome.

**Comment by RLRabinowitz** [comment]
OK. I think we could continue this discussion after we release the `for_each` field for the `import` block. Changing the value for the `for_each` map dynamically could help with your use-case, with no need for specific behaviour with conditionals for the `to` or `id` fields.

**Comment by RLRabinowitz** [comment]
Hey @RoozbehShafiee , now that OpenTofu 1.7 is out, and import for_each has been released, it can help your use-case using it.
The import block will import once for each key-value pair in the `for_each`. If the `for_each` is empty, no import will take place

```
import {
  for_each = var.resource_id == null ? {} : { import: var.resource_id }

  id = each.value
  to = aws_s3_bucket.bucket["my-bucket"]
}
```

I'm closing this issue for now. If there are other use-cases that are not solved by this, feel free to re-open the issue

**Comment by RoozbehShafiee** [comment]
Hi @RLRabinowitz , Thanks a lot for considering my request as part of 1.7 release. It will unblock me to import hundreds of resources and bringing them under OpenTofu umbrella. I will test that and will re-open the issue if needed.
