### ISSUE TITLE
Don't fail on missing import, allow plan/apply to propose new resource

### ISSUE THREAD

**Issue by paulaustin-automutatio** [opentofu/opentofu#1289]
### OpenTofu Version

```shell
OpenTofu v1.6.1
on windows_amd64
```

### Use Cases

Deploy an imports.tf in a module to help repair missing state

### Attempted Solutions

N/A

### Proposal

Make the default approach that if the id specified in an import doesn't exist then it is assumed that the resource would need to be created. At the moment it fails so you can't create the resource without commenting out the missing imports.

 
Terraform has a similar issue

https://github.com/hashicorp/terraform/issues/33633

**Comment by RLRabinowitz** [comment]
Hey @paulaustin-automutatio , thank you for submitting the issue!

I would like to hear more about your use-case here - How are you using the `import` blocks, and how would allowing the plan/apply to propose creation of the resource would benefit your use-case

**Comment by RLRabinowitz** [comment]
There's [this suggestion](https://github.com/opentofu/opentofu/issues/1274) that is a bit adjacent.
And once we introduce `for_each` field, it could be used to have more control over your `import` blocks.

Does your use-case require `import` blocks to only import if the resource doesn't exist in the cloud?

**Comment by paulaustin-automutatio** [comment]
@RLRabinowitz here are the situations where importing any existing state full or partial would be useful.

1. Bugs in the code, network, or file issues that result in corrupted state.
2. Someone accidentally deleting the state, or using the state manipulation commands resulted in missing or incorrect state.
3. In development when you're making changes and decide it's easier to delete the local state and re-import what existed.
4. Disaster recovery testing to simulate corrupted state and recovery of the state

The above request was based on the existing functionality.

However If I was starting from scratch designing the import functionality I would have likely done the following:

Have the following methods of being able to assign resource ids to the resources for import purposes. My preference is for less lines of code in the .tf files

1. Where a provider is able to map from the input parameters to resource ids (azurerm can do this for most resources) then allow that provider to return it (e.g. getImportId function internal to the code).
2. Similar to how there is a for_each meta argument have an import_id meta argument on a resource to provide the id for resources
3. Have the import blocks to map from resource state keys to ids

The next question is then how do you import them into an existing state?

My preference would be to have it as part of the import command as opposed to plan or apply. That way you only need to import when you want to. This ticket was created based on the fact the existing code was using the import blocks in the apply.

The import command would work in a few different ways.

1. The existing import where the state key and resource ids are specified
2. --from-import-blocks would use the in .tf import configurations as described above
3. --from-file [file] would import from a imports.tf file that contains import blocks to process

The flags 2 & 3 could conceivably also be used in the plan phase to import missing resources. However I think it's better to do it it in the import.

**Comment by RLRabinowitz** [comment]
Hey @paulaustin-automutatio , sorry for the long wait. I've been looking into how possible it would be to do this. Specifically, I was looking into if there's a possible way of determining whether a failure from the provider when importing is an actual error or an error due to the resource not existing in remote.

After digging deeper, it _might_ be possible to tell if a resource is missing in remote, but not all providers are implemented in such a way that would allow OpenTofu to tell whether the resource exists in remote or not.

For example, the AWS provider is implemented in such a way that OpenTofu is able to determine that an import failed due to non-existent remote object. With the AWS, when attempting to import a non-existent S3 bucket, for example, you get the following error:

```
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "aws_s3_bucket.a", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated
│ with the provider's configured region or endpoint, or use "tofu apply" to create a new remote object for this resource.
╵
```

For these specific cases, OpenTofu does "understand" that the failure is due to the resource no existing in remote. However, there are providers, like the [helm provider](https://github.com/hashicorp/terraform-provider-helm), which implemented `helm_release` import in a way that simply conveys an error to OpenTofu. When that happens, OpenTofu has no way of actually knowing whether or not this failure is due to "non-existent remote object" - This would entirely depend on how the provider implements such a case.

Another example is providers that have implemented non-trivial imports, like the [env0 provider](https://github.com/env0/terraform-provider-env0). There you can import some resources by both ID or name. In such a case, when a name is used, there's no way of implementing the import in such a way that OpenTofu would consider as a "non-existent remote object"


So, it _might_ be possible to fix this specifically for resources and providers for which the error you get is "Cannot import non-existent remote object", but it means that any `dont_fail_on_missing_import` would still fail in these scenarios and providers

**Comment by cam72cam** [comment]
There's also no method to know if a provider supports the error mode that we could handle or not, until we call import.

It would mean that `dont_fail_on_missing_import` may fail anyways for some providers and it would be tricky to convey that it's the provider does not support that functionality.

**Comment by paulaustin-automutatio** [comment]
I guess your issue that it is hard to change the API of the providers as the existing providers are defined by terraform.

If I was writing providers from scratch I would have included:

1. A getResourceImportId() to return the ID of the resource if you had to do an import. Then you could have an --auto on import to try and import anything that was missing in the local state.
2. Some kind of status code for when resource creation failed (e.g. Success, Already Existed, Permission Denied, Error, and maybe other kinds of error. Instead of a return type if you can't change the existing signature add a getResourceUpdateStatus() method as an extra method.

Is there a way to be able to extend the API so that updated providers can have either different method signatures, or to add additional method signatures. Then OpenTofu compatible providers can offer more functionality.

**Comment by RLRabinowitz** [comment]
Hey @paulaustin-automutatio . Extending the API would require providers to actually start implementing the new API (almost from scratch), which is very unlikely right now, especially since the most popular ones are maintained by Hashicorp. 

Right now, there's no actual way of providing this functionality without either:
- Creating some new API for the provider, and hoping that providers start using the new API (mostly, for this specific feature)
- Rely on providers implementing import in a specific manner, that would allow OpenTofu to figure out that an import failed because the resource doesn't exist. But that would mean that the feature would work for some providers, and not work for others

Either way, this is not something that we can go forward with right now. I'm closing the issue for now.
If we'll have some better way in the future to implement such a feature, we could then reconsider it

**Comment by pravallikavalli** [comment]
Hey @paulaustin-automutatio confirming that this issue directly affects our UAT environment.

We're using OpenTofu in a GitLab CI/CD pipeline with remote state stored in S3. In our UAT setup, OpenTofu attempted to recreate existing S3 buckets due to missing state entries, resulting in BucketAlreadyOwnedByYou errors. No infrastructure changes were made — the state simply drifted.

To unblock our pipeline, we manually ran tofu import for each bucket. While this worked, it introduces unnecessary manual steps and risk in what should be a stable validation environment.

It would be extremely helpful if OpenTofu could:

Detect existing remote resources and import them automatically, or

Allow plan/apply to proceed gracefully when import blocks reference missing state

Since the AWS provider returns a clear Cannot import non-existent remote object error, this behavior seems feasible for AWS resources.

Thanks for the thoughtful discussion — resolving this would significantly improve reliability in UAT and disaster recovery workflows.
