### ISSUE TITLE
Multiline support for "tofu console"

### ISSUE THREAD

**Issue by boldandbusted** [opentofu/opentofu#1307]
### OpenTofu Version

```shell
Any/Latest
```

### Use Cases

I would like to be able to post multiple lines into opentofu console. While the console as it is is very useful, there are circumstances where being able to cut-and-paste more syntactically valid yet complex code is precluded by this limitation. While this plea should be applied to OpenTofu, you can see more discussion and support for the feature at https://discuss.hashicorp.com/t/multiline-expression-in-terraform-console/23452

At this writing, there has been no apparent movement on this feature in the Terraform CLI codebase.

### Attempted Solutions

`tofu console`
Try to paste multiline HCL. Notice it fails, and the tears start to fall. Also, try 

`cat one-off-command-set.tf | tofu console`

to pipe a multiline file into the console, and tears fall again.

### Proposal

Please include multiline support in `tofu console`. :)

### References

- https://github.com/hashicorp/terraform/issues/32954
- https://github.com/orgs/opentofu/discussions/1300

**Comment by janosdebugs** [comment]
Hello @boldandbusted, thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made). :)

**Comment by Ericwww** [comment]
I dug into the problem and found that solving it might not be that complicated.

But the hard part is that I'm not sure how to do what users expect.

I have tried several tools or products that have similar functionality.

For the terminal (shell), we can do multi-line input via

```shell
$ echo \
> "foo"
foo
```

For python command line, we can do multi-line input via

```shell
>>> print(\
... "\
... foo \
... bar\
... "\
... )
foo bar
>>>
```

or write a file like 

```
print(
    "foo"
)
```

and run command

```shell
$ cat foo.txt | python3
foo
```

Of course, I think python's command line may have some optimizations for this. Since I don't know Python very well, I can't introduce the logic behind it.

If newlines are supported by adding an escape character, I'm not sure if this will work the same under Linux pipes.

So, back to the question itself. I think it may be necessary to add more detailed information, such as: a real use case.

Another thing I want to confirm is that using multiline for one expression or for many expressions?

**Comment by AdamElgressy** [comment]
Hi, I wanted to contribute and start with this issue
I saw the terraform's console wiki" https://developer.hashicorp.com/terraform/cli/commands/console
from there, and from looking at the code, we would only want valid one liners, but I think something we can do here, is make the input into a one line, if it is multiline, and only then run the `out, exit, diags := session.Handle(line)`

I also assume thats solves the issue because @boldandbusted wrote that his multiline is "syntactically valid yet complex code is precluded by this limitation"

we can have a context of brackets (like python have), where we try to match brackets to decide that the expression is fully written, this helps in the case of filter of mapping (from the example):
`{ for key, value in var.apps : key => value if value.region == "us-east-1" }`
where with this solution we could enter:
```
{ 
for key, value in var.apps : key => value 
if value.region == "us-east-1" 
}
```

Are there any other cases we would like to support for multiline in the console, which aren't bracket related?
Let me know, and if thats all, I'll add the implementation :)

**Comment by boldandbusted** [comment]
I'm not sure if that addresses this proposed changr, but I was thinking that whatever the change is, the result would be that the OpenTofu console would behave pretty much like a shell. That means you could pass data via a pipe, a tty or a file. My use case is to be able to "disect" complex code against a State and observe values and apply functions, for loops and other structures that require multiple lines. Is that helpful?

**Comment by Ericwww** [comment]
I made some progress.

using a backslash to continue input whose behavior is most like shell

<img width="912" alt="image" src="https://github.com/opentofu/opentofu/assets/24605603/94adbf3a-9ee8-4886-a233-4c0448dcd9f2">

but for pipe, your file will look like this (hard to view I think)

```
split( \
",", \
"foo,bar,baz" \
)
```

<img width="796" alt="image" src="https://github.com/opentofu/opentofu/assets/24605603/8e2da5cb-0fec-4a31-8c54-7d2f8b5180a6">

**Comment by AdamElgressy** [comment]
@Ericwww I think that the backslash where we have brackets should be redundant, just like it is in python console/ipython.

I think that @boldandbusted said that he wanted to be able to enter more complex snippets, which would have more than one full expression. @boldandbusted if you could give us concrete examples (snippets), it would be best.

If that is something we would want to support, we can buffer every line which haves a backslash in it, or where a bracket is still open, and when we finish, determine what lines to send the session handler, according to brackets rules. And at the end return the output of the last expression.

Also, we would need to remember to clear that buffer every time we evaluate an expression.

**Comment by cam72cam** [comment]
As a note, it looks like this feature may be implemented in some fashion in the HashiCorp/terraform repository based on their beta release notes. As a reminder, if discussing or submitting code to OpenTofu *do not look at or discuss similar code in hashicorp/terraform* as that may violate the license.

**Comment by boldandbusted** [comment]
Very late thanks for this! 🥇 🚀 💯
