### ISSUE TITLE
Allow Variable Validation Conditions to Refer to Other Variables

### ISSUE THREAD

**Issue by RoseSecurity** [opentofu/opentofu#1336]
### OpenTofu Version

```shell
OpenTofu 1.6.2
```

### Use Cases

I want to be able to have conditional validation on variables - the condition being the value of other variables.
Currently, I'm trying to implement a load balancer ([resource "aws_lb"](https://www.terraform.io/docs/providers/aws/r/lb.html#security_groups)) in AWS - the load balancer resource can either be of type "application" or "network". Depending on the load balancer type, there are several required and optional variables that you can pass in. Terraform throws an error if you fail to pass a required variable, but, if you pass in an optional variable to the wrong load balancer type, there isn't much warning.

For the sake of example, an application load balancer can optionally take a list of security groups, but a network load balancer can't. If a developer passes in a list of security groups to an NLB, they may have specified the wrong value for load_balancer_type, or they may be passing variables into the wrong load balancer resource - in either case, I'd like to give a warning to the developer to save them having to go debugging.

This isn't a request that's strictly for AWS load balancers - the pattern of "value X is required if value Y is Z" seems to be fairly common across Terraform plugins.

### Attempted Solutions

I tried adding a validation block here:

```terraform
variable "security_groups" {
  description = "A list of security groups to attach to the load balancer. Only works with ALBs"
  type = list(string)

  validation {
    condition = var.lb_type == "application"
    error_message = "Security groups can only be used by Application Load Balancers."
  }
}
```

Error:

```console
Error: Invalid variable validation condition

  on variables.tf line 36, in variable "security_groups":
  36:     condition = var.lb_type == "application"

The condition for variable "security_groups" must refer to var.security_groups
in order to test incoming values.
```

### Proposal

Just a few prefaces to my proposals:

- Implementing such a feature could allow for cyclic dependencies between variables - although, I think that it's at the developer's own risk - like how to package systems in programming languages facilitate cyclic dependencies (but we still all recognize the benefit of having them).

- I think that the (bigger) potential issue is causing a significant growth in the dependency graph by creating a complex set of conditional validation rules

### References

- [Terraform Request](https://github.com/hashicorp/terraform/issues/25609)

**Comment by cam72cam** [comment]
Do you think a variant of https://github.com/opentofu/opentofu/issues/1042 may be helpful here?

**Comment by RoseSecurity** [comment]
@cam72cam Definitely, I really would love to see more flexibility around this area

**Comment by apparentlymart** [comment]
The current limitation that a variable's validation condition can refer only to itself is ultimately the result of an internal design quirk:

One of the most important steps that OpenTofu performs while constructing its execution graph is the `ReferenceTransformer`, which finds every graph node that could potentially contain [reference expressions](https://opentofu.org/docs/language/expressions/references/), and every graph node that represents something that can be referred to in an expression<sup>1</sup>, and draws in dependency edges from all of the referrers to the objects they refer to.

Because the Tofu language uses modules as a namespacing boundary, the `ReferenceTransformer` additionally wants to know which module namespace each node "belongs to", so that e.g. it can avoid creating a spurious dependency edge between an object in a child module that refers to `var.foo` and the `variable "foo"` block in the _root_ module. By the rules of the language, there are two separate valid `variable "foo"` declarations and so `ReferenceTransformer` needs to make sure to connect only the right one.

Inherent in that algorithm today is an assumption that each node belongs only to one module path, which is tricky for input variables because they actually have a stake in both the module where they are declared _and_ the module that's calling it:

1. Inside the module itself, the arguments in the `validation` blocks want to be able to depend on other objects in the same module where the `variable` block is declared...
2. ...but the variable's _main value_ originates from an expression inside a `module` block in the _calling_ module, and so it needs to be able to depend on objects in the parent module too.

The current implementation sacrificed (1) to retain (2), because (2) is the primary functionality.

I can imagine at least two possible strategies for resolving this feature request:

* Rework `ReferenceTransformer` so that it can somehow deal with input variable graph nodes being expression-referrers in both their own module and in their parent module at the same time, somehow resolving different references from the same graph node in two different module namespaces.
* Split the graph nodes that represent input variables into two parts: one that determines the value assigned by the caller while belonging to the parent module, and another that "finalizes" the value for use in the child module by applying type conversions, substituting the default value if appropriate, and then finally checking the validation rules.

    The graph transformer which inserts the graph nodes for input variables would then gain the new responsibility of drawing dependency edges from the second node to the first, to ensure that the caller's direct definition of the variable always gets evaluated first.

I would personally favor the second option because it reserves the additional complexity only for the input variable handling. I enjoy the relatively-elegant separation of concerns where one node deals with the variable value as the caller defined it, while the other node deals with the variable value as the callee receives it.

I think there's also a nice potential secondary benefit of being able to share more code between the "root variable" nodes and the "(non-root) module variable" nodes. Today they are pretty separate but share some utility functions. I think in principle it should be possible to have only one implementation of "finalize the value for use inside the module" which is used for both root and non-root modules. The major differences live in the "determine the value assigned by the caller" part because for root modules those are determined by a static table passed in to the language runtime by Tofu CLI instead of by evaluating expressions.

<sup>1</sup> (many graph nodes meet _both_ of these criteria)

**Comment by mm-chia** [comment]
I believe this feature has been implemented in Terraform 1.9.0.
Would love to see it in Tofu as well, it is a nice improvement to have :)

**Comment by mloskot** [comment]
@mm-chia 
> I believe this feature has been implemented in Terraform 1.9.0.

No need to believe in it, it's a fact ;)

https://www.hashicorp.com/blog/terraform-1-9-enhances-input-variable-validations

**Comment by dabmajor** [comment]
+1

**Comment by mrkesu** [comment]
This has already been tagged as `accepted` and is on the [roadmap](https://github.com/opentofu/opentofu/milestones) for v1.9...

**Comment by julian-alarcon** [comment]
So, this is still not supported according to this: https://opentofu.org/docs/v1.9/intro/migration/terraform-1.9/#input-variable-validation
