### ISSUE TITLE
Adding AWS sample for Amazon S3 remote backend to documentation 

### ISSUE THREAD

**Issue by LumberjackUsingMath** [opentofu/opentofu#1339]
### OpenTofu Version

```shell
any/latest
```

### Use Cases

The link to the AWS sample would be a great reference in the documentation regarding the usage of an Amazon S3 remote backend for OpenTofu. It provides an example to kickstart a OpenTofu project following best practices

### Attempted Solutions

If someone let's me know where to put it, I can prepare the pull request 

### Proposal

Referencing the https://github.com/aws-samples/bootstrap-amazon-s3-remote-backend-for-open-tofu

**Comment by Yantrio** [comment]
Hi, I'm aware we dont have tutorial-style documentation right now but there is a vast amount online already. For example: https://spacelift.io/blog/terraform-s3-backend

**Comment by Yantrio** [comment]
@LumberjackUsingMath Firstly, thank you for the contribution.

In the future, we do recommend that people follow our [Contributing guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md) as we would've loved to have discussed this a bit more before accepting the issue

Firstly I'm not too sure about pitching to users that they should use CloudFormation to manage their infra, when OpenTofu would work well for this. This could increase complexity overall for users new to IaC.

I am also a little concerned by the license in the repo you are pitching: https://github.com/aws-samples/bootstrap-amazon-s3-remote-backend-for-open-tofu/blob/main/Mozilla%20Public%20License%202.0 I'm mainly a bit confused by the hashicorp license being there. Would you be able to explain what's going on here with the licensing of this repo?

I've also left a comment on the pull request but our intention in the long run with the s3 backend with OpenTofu is to support multiple S3-compatible services. This means that where possible we are not looking to tie things too closely to AWS specifically. We want to provide options to the users.

In my personal opinion, we should probably have some sort of guide directly in the OpenTofu documentation that end users can consume rather than an external resource that could disappear or become unmaintained over time.

**Comment by LumberjackUsingMath** [comment]
Hello @Yantrio, 

thanks for the great feedback. I released that repository as I could not find any IaC example which solves the creation of the remote backend in an automated way and following best practices. For instance, https://spacelift.io/blog/terraform-s3-backend gives a great head start but leaves the reader all the work to provision the resource and has the following three weakness. 1/ it creates the backend using a local state 2/ it does not recommend a KMS key 3/ the bucket policy could be more restrictive. 
Of course one can do this with OpenTofu as well, but Amazon CloudFormation does not require a local state and any manual interactions such as importing resources. 

Thanks a lot for spotting the license bug, I must have missed the first line when I copied the OpenTofu license. Now it is correct. 

Regarding the name, would you mind explaining why having multiple S3-compatible services justifies to shorten the name? S3 alone is kind of an ambiguous term. If someone drives an Audi S3, the first thing they might think of could be their car. 

Regarding your suggestion to have a guide directly in the OpenTofu documentation: Agree, it is always good to reduce the risk of outdated links. How should the guide look and where should it reside, in your opinion?
