### ISSUE TITLE
Large numbers are truncated in plan

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1361]
### OpenTofu Version

```shell
1.6.2
```

### OpenTofu Configuration Files

```hcl
locals {
  ids = [
    9223372036854773256,
    9223372036854773263,
    9223372036854773263,
    9223372036854773266
  ]
}

output "ids" {
  value = local.ids
}
```

### Debug Output

.

### Expected Behavior

```
Changes to Outputs:
  + ids = [
      + 9223372036854773256,
      + 9223372036854773263,
      + 9223372036854773263,
      + 9223372036854773266,
    ]
```

### Actual Behavior

```
Changes to Outputs:
  + ids = [
      + 9223372036854774000,
      + 9223372036854774000,
      + 9223372036854774000,
      + 9223372036854774000,
    ]
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34686

**Comment by Ericwww** [comment]
It seems truncated only at view scene. When run apply, origin number will show in state file.

I don't have a 32bit system but I could test it in the 32bit system container. If you don't mind, can I take this?

**Comment by cam72cam** [comment]
Sure, thanks @Ericwww!

**Comment by Ericwww** [comment]
Hi @cam72cam @RLRabinowitz 

I found some strange unit test code may caused by same reason. 

https://github.com/opentofu/opentofu/blob/94537dcda2103b7a36ce5e490589e05e3c44eba0/internal/command/jsonformat/differ/differ_test.go#L2748-L2789

And when I change the number at line 2784 from `0.0` to `0`, tofu crashed (throw panic).
The problem might be here
https://github.com/opentofu/opentofu/blob/94537dcda2103b7a36ce5e490589e05e3c44eba0/internal/command/jsonformat/structured/attribute_path/matcher.go#L52-L65

This number is index of a list. Like the number `0` in `test_resource.resource.list[0].attribute`.

It seems that it will not lead to some bug in the short term. (I test it by `range` function, but range only support to generate a maximum of 1024 elements)
Because in actual scenarios, users may not use such a large number. Or tofu might crash when user give such a large number.

**Comment by cam72cam** [comment]
I just noticed that there was a potentially related go-cty release within the past week which is likely related to this work: https://github.com/zclconf/go-cty/commit/4a34c33ad713db9437a9173c5d5529ca0ed606e3

We need to upgrade go-cty and add some tests for encoding objects with unknown values.

Thanks again @Ericwww for the initial PR!  Let me know if you would like to take on this followup.

**Comment by cam72cam** [comment]
My mistake, this was a false alarm and does not interface with the encoding/json package directly.
