### ISSUE TITLE
[State Encryption] Syntax for migrating from unencrypted state/plan

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1365]
Dear everyone, we need your input on syntax for migrating from unencrypted to encrypted state and plan files. Please let us know which solution would work best for you and why. This is a companion issue to #1366.

## Background

Under normal operations, OpenTofu will refuse to read unencrypted state and plan files when encryption is configured. This is protecting users from smuggled-in state and plan files that could cause damage.

However, when migrating from unencrypted state and plan files to encrypted ones, the users need to have the ability to perform this migration. Furthermore, we want to enable users of CI systems to do this declaratively.

For more details on the state encryption function please see [the design document](https://github.com/opentofu/opentofu/blob/main/docs/state_encryption.md), [the user documentation](https://github.com/opentofu/opentofu/blob/main/website/docs/language/state/encryption.mdx), or [this video](https://www.youtube.com/watch?v=rR4IbhlRSkI).

## Solution 1

This solution infers the users' intention to read unencrypted data by the presence of an empty `fallback{}` block. This is somewhat unusual because users may not expect empty blocks to have such an implication.

```hcl
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      method = method.aes_gcm.mymethod
      fallback{} # The empty fallback block signals that reading unencrypted state is OK.
    }
  }
}
```

Note that this functionality should be disabled if the `enforced` option is set to true.

## Solution 2

This solution uses an explicit option to allow reading unencrypted data.

```hcl
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      method = method.aes_gcm.mymethod
      fallback{
        allow_unencrypted = true # Allows reading unencrypted by default
      }
    }
  }
}
```

Note that this functionality will be overridden by the `enforced` option, which will not allow unencrypted state to be read under any circumstances.

## Solution 3

This option changes solution 2 by moving the migration option up from the fallback block. This option would also actively refuse to work if it encounters an encrypted state file, forcing the user to immediately remove this option once the migration is complete. As before, the `enforced` flag would prevent unencrypted data manipulation.

```hcl
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      method = method.aes_gcm.mymethod
      migrate_from_unencrypted = true
    }
  }
}
```

**Comment by janosdebugs** [comment]
@RDhar yes, the enforced option would always prevent any unencrypted data manipulation

**Comment by StephanHCB** [comment]
I am leaning towards Solution 3, simply because it's the most explicit.

There is something we may need to warn the users about in the documentation:

When working with wrappers like `terragrunt`, in order to migrate an existing tree to encrypted state, you will need to force a state write for all remote states, which usually only happens while applying. With a large tree and some slow providers this can be inhibitive because `terragrunt run-all apply` for the full tree takes a very long time, and while that runs, you can't work on anything because it will walk through your state blobs, and lock them one after the other.

For these cases, a gradual migration "while applying anyway" is the most feasible approach. To do this, one can simply set "migrate_from_unencrypted = true" in the configuration, and not enforce encryption until unencrypted state has aged out.

**Comment by janosdebugs** [comment]
We had a conversation with @cam72cam and we would prefer this solution:

```
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      method = method.aes_gcm.mymethod
      migrate_from_unencrypted = true
    }
  }
}
```

Our issue with solution 3 is that the change may need to go through a dev-test-prod pipeline and forcing the user to remove code for each of those may not be feasible.

We would like to argue for very big warnings in both the execution and documentation.

**Comment by joshuashanks-sentilink** [comment]
Does solution 3 need to fail if it finds state that is unencrypted? I would think that it could be treated like an import block, if the state is encrypted don't worry about it and if not encrypt it then moves forward. 

Maybe behavior could be different if there was also a `migrate_if_unencrypted` option.

Going back to the import block idea I think I'd actually like to pass in a hash of the unencrypted data as an "id" and only do the encryption if the hash matches, otherwise expect the state to be encrypted.

```
terraform {
  encryption {
    # Methods and key providers here

    state {
      method = method.aes_gcm.mymethod
      migrate_if_unencrypted = true
      migrate_if_hash = "a4d8..."
    }
  }
}
```

**Comment by jjshanks** [comment]
Does solution 3 need to fail if it finds state that is unencrypted? I would think that it could be treated like an import block, if the state is encrypted don't worry about it and if not encrypt it then moves forward.

Maybe behavior could be different if there was also a `migrate_if_unencrypted` option.

Going back to the import block idea I think I'd actually like to pass in a hash of the unencrypted data as an "id" and only do the encryption if the hash matches, otherwise expect the state to be encrypted.

```
terraform {
  encryption {
    # Methods and key providers here

    state {
      method = method.aes_gcm.mymethod
      migrate_if_unencrypted = true
      migrate_if_hash = "a4d8..."
    }
  }
}
```

**Comment by janosdebugs** [comment]
Hey folks, @cam72cam, @Yantrio have yet another proposal and we would consider to be more idiomatic. To migrate from unencrypted to encrypted state you would have to do the following:

```hcl2
terraform {
  encryption {
    method "unencrypted" "migration" {
    }
    state {
      method = method.foo.bar
      fallback {
        method = method.unencrypted.migration
      }
    }
  }
}
```

Once the migration is complete, a user can set the `enforced` option to lock down the setup. This option will prevent OpenTofu from reading an unencrypted state, which prevents smuggled-in unencrypted state files. This option will also prevent OpenTofu from writing unencrypted state in case an environment variable is missing:

```hcl2
terraform {
  encryption {
    state {
      enforced = true
    }
  }
}
```

This will fail unless the following environment configuration is set:

```bash
TF_ENCRYPTION="terraform {
  encryption {
    state {
      method = method.some_method.name
    }
  }
}"
```

**Comment by skyzyx** [comment]
I would recommend renaming the issue to use the positive action instead of the negative action:

```diff
- [State Encryption] Syntax for migrating from unencrypted state/plan
+ [State Encryption] Syntax for migrating to encrypted state/plan
```

I also want to echo my comments from #1366 about describing things from the position of "positive actions" as opposed to "negative actions".

---

Also, based on your most recent comment, I would suggest the following:

```hcl
terraform {
  encryption {
    method "decrypt_state" "migration" {}

    state {
      method = method.foo.bar
      fallback {
        method = method.decrypt_state.migration
      }
    }
  }
}
```

Regarding your next block:

```hcl
terraform {
  encryption {
    state {
      enforced = true
    }
  }
}
```

Enforce _what?_ In elementary school (primary school in Europe?), we learned about "context clues" to help us understand what we were reading. But there isn't (necessarily) enough context without having to make assumptions.

`encryption{}` is talking _about_ encryption generally, but does not imply that this thing is definitely encrypted.

`state{}` gets us closer, which lets us know that we're thinking about the state file. But are we enforcing that a project has a state? Don't they all? (I'm being facetious, but I think it's warranted.)

I think that if we were to favor _clarity_ and require the user to make fewer _assumptions_, I would implement something like this:

```hcl
terraform {
  encryption {
    state {
      enforce_encrypted_state = true

      # Or maybe…
      # require_encrypted_state = true

      # Or where the "context clue" is the state{} block.
      # require_encryption = true
    }
  }
}
```
