### ISSUE TITLE
[State Encryption] Syntax for migrating to unencrypted state/plan

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#1366]
This issue is a companion to #1365 and deals with migrating from an encrypted to an unencrypted state/plan. Your input is needed on the syntax.

## Background

Under normal operations, OpenTofu will refuse to read unencrypted state and plan files when encryption is configured. This is protecting users from smuggled-in state and plan files that could cause damage.

However, when migrating from encrypted state and plan files to unencrypted ones, the users need to have the ability to perform this migration. Furthermore, we want to enable users of CI systems to do this declaratively.

For more details on the state encryption function please see [the design document](https://github.com/opentofu/opentofu/blob/main/docs/state_encryption.md), [the user documentation](https://github.com/opentofu/opentofu/blob/main/website/docs/language/state/encryption.mdx), or [this video](https://www.youtube.com/watch?v=rR4IbhlRSkI).

## Solution 1

This solution implicitly migrates from encrypted to unencrypted by not specifying a method. To prevent this behavior, users will need to use the `enforced` option.

```hcl
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      # Note the lack of a method here.
      fallback {
        method = method.aes_gcm.mymethod
      }
    }
  }
}
```

## Solution 2

This solution will add an explicit option to allow decryption:

```hcl
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      allow_unencrypted = true
      fallback {
        method = method.aes_gcm.mymethod
      }
    }
  }
}
```

**Comment by StephanHCB** [comment]
`allow_unencrypted` seems to me to just be the negation of the already present `enforced` option, so I don't really see a need for both. Thus, I'd lean towards Solution 1. Not a strong preference, though.

**Comment by cube2222** [comment]
With this basically being an empty encryption block for the statefile, I'd probably just call it `unencrypted = true`.

But generally in favour of explicit field, so solution 2.

**Comment by janosdebugs** [comment]
We had a conversation with @cam72cam and we would prefer the following solution:

```
terraform {
  encryption {
    # Methods and key providers here

    statefile {
      migrate_to_unencrypted = true
      fallback {
        method = method.aes_gcm.mymethod
      }
    }
  }
}
```

**Comment by cam72cam** [comment]
We failed to consider how remote state would fit into this paradigm.  Both the default and individual remote states rely upon empty fallback blocks currently.  I've moved the PR to a draft and implemented a pattern that could work, but IMO is clunky.

I've also implemented Solution 1/2 in [1366_encryption_method_warnings](https://github.com/opentofu/opentofu/compare/1366_encryption_method_warnings)

![image](https://github.com/opentofu/opentofu/assets/892136/17dd9382-0e75-4446-bc41-466929b6d367)
![image](https://github.com/opentofu/opentofu/assets/892136/6cfe7e6b-63b6-4770-b88c-2995264d53b4)

**Comment by jjshanks** [comment]
I'm not sure I am a fan of either solution. I would expect going to unencrypted to be uncommon and for special cases like sending the state file to someone that needs it unencrypted. Is there a more common use case y'all have been thinking about that I missed?

Instead of adding support for this in the `encryption` block could there be a decrypt command that writes the decrypted state out to a new file?

`tofu state decrypt -out=decrypted.state`

**Comment by janosdebugs** [comment]
In line with [this comment](https://github.com/opentofu/opentofu/issues/1365#issuecomment-2034708781), @cam72cam, @Yantrio and I would like to propose the following solution:

```hcl2
terraform {
  encryption {
    method "unencrypted" "migration" {
    }
    state {
      method = method.unencrypted.migration
      fallback {
        method = method.foo.bar
      }
    }
  }
}
```

In case the `enforced` flag is set, the unencrypted method will fail and a migration to unencrypted state will not take place. In all other situations, the migration will complete to unencrypted state.

**Comment by skyzyx** [comment]
Generally, as a point of user experience, I would discourage what I call "falsey as true" -- instead always favoring "truthy as true". Or, put another way, it is better for a positive action to be set to false, than a negative action to be set to true.

For example:

This is an example of "truthy as true" (e.g., yes, do the thing):

```hcl
require_encryption = true
```

This is an example of "falsey as true" (e.g., yes, **don't** do the thing):

```hcl
allow_unencrypted = true
```

In many contexts of supporting customers of software, there is a high consistency in confused customers when developers leverage "falsey as true" toggles, or even worse, mix-and-match their usage inconsistently in a UI (where a UI is any interface that a user experiences).

Tying this feedback into @janosdebugs’ most recent post, I would suggest the following "truthy as true" approach:

```hcl
terraform {
  encryption {
    method "decrypt_state" "migration" {} # <- This.

    state {
      method = method.decrypt_state.migration # <- This.
      fallback {
        method = method.foo.bar
      }
    }
  }
}
```

(While this _specific_ example is a bit simplistic and a touch contrived, the over-arching principle is sound.)

The words "encrypt" and "decrypt" are positive actions. (Yes, do the thing.)

The words "unencrypt" or "undecrypt" (the latter of which we don't generally say in English), are simply _!encrypt_ and _!decrypt_ (negative actions; yes, don't do the thing).

---

> In case the `enforced` flag is set, the unencrypted method will fail and a migration to unencrypted state will not take place. In all other situations, the migration will complete to unencrypted state.

Does the flag say _what_ is being enforced? I think it should. I would strongly advise an approach of _clarity_ over _assumption_.

In my examples above, I also clarified _what_ is being decrypted (instead of _assuming_ the user will understand and infer the intended meaning). Not just _to decrypt_ (something?), but specifically _to decrypt the state_.

**Comment by skyzyx** [comment]
I would also recommend renaming the issue to use the positive action instead of the negative action:

```diff
- [State Encryption] Syntax for migrating to unencrypted state/plan
+ [State Encryption] Syntax for migrating from encrypted state/plan
```

**Comment by skyzyx** [comment]
@cam72cam said:

> We failed to consider how remote state would fit into this paradigm.

This concerns me a bit. IMO, remote state should be a primary use-case, and local state should be a secondary use-case. I appreciate that you're working through it -- thank you! -- but if the above quote is true, my opinion is that this was approached in the reverse order.

**Comment by cam72cam** [comment]
I should have made a more clear comment.  I should have phrased it as "remote state *data sources*" instead of just saying "remote state".

**Comment by janosdebugs** [comment]
Regarding naming: the method should serve for both encryption from a plain text state and decryption to a plain text state.
