### ISSUE TITLE
OpenTofu uses BUSL-1.1 licensed Terraform code and relicenses it as MPL-2.0.

### ISSUE THREAD

**Issue by Trojaner** [opentofu/opentofu#1469]
### OpenTofu Version

```shell
v1.7.0-alpha1
```

### Expected Behavior

OpenTofu should not violate any license terms.

### Actual Behavior

OpenTofu appears to violate Terraform license terms.

### Steps to Reproduce

1. `git clone https://github.com/opentofu/opentofu -b v1.7.0-alpha1`.
2. Build and [release](https://github.com/opentofu/opentofu/releases/tag/v1.7.0-alpha1) artifacts as "MPL-2.0" and claim it as [truly open source](https://opentofu.org/manifesto/).

### Additional Context

Example:
[Original Terraform code](https://github.com/hashicorp/terraform/blob/a718f70f8513f9336e25de8c077c22cfae85481d/internal/refactoring/remove_statement.go) vs. [OpenTofu "OSS" code](
https://github.com/opentofu/opentofu/blob/e9fe0f1118e77c0ba8a78dad264fcafbccebb1b0/internal/refactoring/remove_statement.go)

Note that this feature was implemented by Terraform *after* the license change.
While it is correctly attributed to HashiCorp in the OpenTofu header, the license identifier is wrong.

For more details see the source article:
https://www.infoworld.com/article/3714980/opentofu-may-be-showing-us-the-wrong-way-to-fork.html

**Comment by marcinwyszynski** [comment]
@Trojaner 

The team is aware of these accusations and is currently working on an official response. Please stay tuned.

**Comment by robbert229** [comment]
# Intro

I am not directly involved; however, the license is there for a couple of legitimate reasons, and the code is not a derivative work, or violating any licenses.

# Licensing "Smoking Gun"

The Hashicorp MPL license is not a smoking gun publicly demonstrating OpenTofu committing theft, instead its indicative of OpenTofu deeply caring about maintaining its integrity with regards to licensing.

Some of the code in this feature is copy / pasted from other parts of the existing open tofu codebase that is licensed by Hashicorp under the mpl. This is the correct action. To put it another way, the linked file is not entirely new code, and as a result pulls from existing parts of the Hashicorp mpl licensed codebase. That is why the license is included here.

# Code Similarities

This feature is not a big brand-new thing, it's a small refinement on the management of lifecycles. The claims in the article about the code being identical completely ignore the fact that both implementations share a common lineage. It would be like claiming that `SELECT * FROM posts` is theft from another `SELECT * FROM ` query because they are similar. 

The code is substantially different in all ways that it can possible be, go as a language is boring, and most go code looks alike, especially when from the same codebase. Interacting with existing terraform code also makes the code look similar. 

# Sources

The whole development process of this feature occurred in public view. If you look back you can see that the evolution of it, the review, and that it is obviously not a copy/paste of hasicorp code. I urge whoever has concerns to do some research. It took me about fifteen minutes of reading after seeing the article to come up with some major concerns over the accuracy of the article, and I am of the opinion that the article should be retracted due to irresponsible journalism.

https://github.com/opentofu/opentofu/pull/1158
https://github.com/opentofu/opentofu/issues/454#issuecomment-1904213569
https://app.slack.com/client/T05QP2H25SA/C05R0FD0VRU/thread/C05R0FD0VRU-1705997490.521719/1706012969.801869

**Comment by Trojaner** [comment]
@robbert229 Thank you for the explanation of the situation. After inspecting the code more carefully it looks like that the code indeed seems only similar on the first sight given the shared common lineage. 

Well, infoworld.com is for sure off my feed now given the lousy research the article author did despite the weight of the topic and the constant attempted bashing of the team behind this project.

**Comment by robbert229** [comment]
No worries, you were a victim of irresponsible journalism.

**Comment by rbkaspr** [comment]
The one thing I'll say is in future a title like "<Project> *appears* to use improperly licensed code" is probably the better way to start the discussion if you're not quite sure.

**Comment by cam72cam** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7182147077496344576

OpenTofu Project was recently made aware of a letter by HashiCorp’s lawyers, alleging that OpenTofu was not respecting the terms of its BSL license governing its Terraform codebase. OpenTofu vehemently disagrees with any suggestion that it misappropriated, mis-sourced, or otherwise misused HashiCorp’s BSL code. Indeed, it seems that HashiCorp may be conflating code that it had previously been open-sourced under the MPL and more recently developed code it published under the BSL. OpenTofu’s maintainers have investigated this matter, and intends to issue a written response providing a more detailed explanation of its position in the coming days.

**Comment by s3rj1k** [comment]
Would be curious to see how this all plays out and if in fact it would be proven that there was a license misuse (not stating that it was), who will be "appointed" as the license breaker, meaning will OpenTofu legally protect their contributors.

**Comment by not-igalze** [comment]
@robbert229  

> The whole development process of this feature occurred in public view. If you look back you can see that the evolution of it, the review, and that it is obviously not a copy/paste of hasicorp code. I urge whoever has concerns to do some research. It took me about fifteen minutes of reading after seeing the article to come up with some major concerns over the accuracy of the article, and I am of the opinion that the article should be retracted due to irresponsible journalism.


best take on this whole thing so far

**Comment by tjhorner** [comment]
I just encountered that InfoWorld article and just like @robbert229 surmised, after even an inkling of research it's very obvious that this claim is entirely baseless. It's clear that the `remove` block feature was implemented based on a properly-licensed similar feature (likely the `move` block) and not plagiarized from HashiCorp's implementation. Additionally, the copyright header is automatically added to every source file regardless of whether it came before the fork or after. I sent an email to the author with these details. Here's hoping it can be amicably resolved.

Email to author:

> Hi Matt,
> 
> I was reading your article about [OpenTofu's supposed license snafu](https://www.infoworld.com/article/3714980/opentofu-may-be-showing-us-the-wrong-way-to-fork.html) and I think there is an important part that you missed which would change the narrative a bit. The article's chief complaint is how the OpenTofu authors took code from BUSL-licensed Terraform and copied it to their MPL fork, then changed HashiCorp's license header to retroactively be MPL instead of BUSL. As I see it, there are two issues at play here:
> 
> 1. OpenTofu plagiarizing HashiCorp's code for the new feature.
> 2. The re-licensing of that plagiarized code.
> 
> Now, I'm not certain one way or the other if OpenTofu did actually plagiarize HashiCorp's code — the diffs don't really show any obvious signs of copying, and at a project of this size there are bound to be other properly-licensed examples for implementations of similar features, from which both parties would likely follow the pattern of (for example, [this file from before the relicensing](https://github.com/opentofu/opentofu/blob/b8680121929d8f71dd1258d9b6ce34246662f61c/internal/refactoring/move_statement.go) is very similar) — but whether or not they did is irrelevant to my complaint here. The issue I have is with that second point.
> 
> HashiCorp (and via fork OpenTofu) both use a tool called "copywrite" to automatically add copyright headers to the beginning of source files if they are not present. You can see that [OpenTofu changed the configuration for this tool in their fork](https://github.com/opentofu/opentofu/blob/b8680121929d8f71dd1258d9b6ce34246662f61c/.copywrite.hcl#L9) to add a copyright header for both themselves and HashiCorp, in order to acknowledge that much of the code in the repository was authored by HashiCorp pre-fork (a CYA, I suppose). You can read the discussion surrounding this change in [this PR](https://github.com/opentofu/opentofu/pull/1232) as well. This copyright header is added automatically for every existing and new source file, regardless of whether any HashiCorp-authored code is actually in the file.
> 
> Given this information, it seems very unlikely that the OpenTofu authors simply copied the code for this new feature directly from HashiCorp's source repo and changed the license header to match their own. The license header was not changed by a human and is part of an automated process that applies to all files; I don't think OpenTofu's authors thought they could "retroactively make BUSL-licensed code magically become MPL-licensed code".
> 
> I don't have any sort of relationship with OpenTofu or its authors but I do think this article unfairly makes them look foolish, especially since there is no strong evidence to indicate that they did actually plagiarize improperly licensed code. If anything, it seems to me they only copied from pre-fork code for similar features, which is entirely legal and ethical.
> 
> I would appreciate a correction or amendment to the article to reflect this.
> 
> Thank you,

**Comment by tjhorner** [comment]
Just received a response from Matt, it looks like this whole situation is going to be resolved soon. It is disappointing that these claims were published by HashiCorp/InfoWorld in the first place but I am glad to see that it's being resolved amicably.

**Comment by cube2222** [comment]
Here's the blog post with all the details: https://opentofu.org/blog/our-response-to-hashicorps-cease-and-desist/

**Comment by s3rj1k** [comment]
> Here's the blog post with all the details: https://opentofu.org/blog/our-response-to-hashicorps-cease-and-desist/

Just a thought, if `other` than Golang language is used, would it be possible to even file a copy-right claim?

(thinking WASM)

**Comment by marcinwyszynski** [comment]
@s3rj1k WASM would be problematic because of its inherent limitations. The obvious candidate would likely be Rust but just think about the enormity of the task to rewrite a large complex codebase to a new language.

**Comment by s3rj1k** [comment]
> @s3rj1k WASM would be problematic because of its inherent limitations. The obvious candidate would likely be Rust but just think about the enormity of the task to rewrite a large complex codebase to a new language.

I was not talking about full rewrite, instead some kind of adhoc runtime execution for new module logic, doesn't have to be WASM, anything that can be embedded inside (LUA, JS, ...)

**Comment by marcinwyszynski** [comment]
Not sure if this kind of architectural complexity would be good for the maintainability of the codebase and the stability of the product.

**Comment by s3rj1k** [comment]
> Not sure if this kind of architectural complexity would be good for the maintainability of the codebase and the stability of the product.

Yea it will probably complicate things, it is only useful in case of additional `Hashicorp's Cease and Desist Letters`, given that they try hard to sell themselves  I can imagine that this is not their last try.

**Comment by marcinwyszynski** [comment]
@s3rj1k I can't really speculate on what someone else is going to do, and why. These are things outside my control. I'd much rather focus on what we *can* do, which is to stick to the highest possible ethical standards - like described in the [contributing guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md) - and keep developing in the open.

I'd personally hate for us to resort to gimmicks like using a different language to work around licensing issues. We have a world class core team and external contributors that can and do ship features independently. That's what we've done in the past, and that's what we will keep doing.

Re: subsequent baseless claims - they will look less and less credible, and each new debunked claim will give us free publicity and trust.

**Comment by tjhorner** [comment]
Yeah, I don't think this is a problem with a technical solution. It is a social one, and I think the guidelines that the maintainers have put in place are a good defense against these kinds of claims.

**Comment by s3rj1k** [comment]
> pretty rock-solid to me

We just have to wait and see will HashiCorp takes this to court or not.

**Comment by s3rj1k** [comment]
> I'd personally hate for us to resort to gimmicks like using a different language to work around licensing issues.

https://github.com/opentofu/terraform-provider-lua

**Comment by marcinwyszynski** [comment]
@s3rj1k This is a very different use case - this is so that users can quickly write functions they're missing, instead of having to release them as standalone providers. That's not part of the core language, and will also work with legacy Terraform.
