### ISSUE TITLE
Simplify Lineage uuid creation

### ISSUE THREAD

**Issue by mikelolasagasti** [opentofu/opentofu#1525]
Currently `internal/states/statemgr/lineage.go` only contains the `NewLineage` function that returns a UUID string.

This function is only called from `internal/states/statemgr/helper.go` and only once, so it can be simplified by directly calling UUID generation function `uuid.Must(uuid.NewRandom()).String()` to achieve the same result.

**Comment by Evi1Pumpkin** [comment]
Hi @mikelolasagasti, we truly appreciate your effort in opening this issue and dedication to enhancing the Opentofu project!
As part of our issue triage process, the core team aims to accept issues that can benefit our OpenTofu users. Due to the large and complex nature of the project, each change requires careful consideration. Regrettably, this particular issue does not meet that criteria, so the core team has decided to close it.
If you think we should avoid using libraries owned by HashiCorp, we recommend creating an issue to list the libraries we may prefer not to depend on anymore. We can then discuss each case and decide whether we want to replace them at this time.
Thank you for your understanding and continued support.
