### ISSUE TITLE
"terraform" provider functions: encode_tfvars, decode_tfvars, encode_expr

### ISSUE THREAD

**Issue by snowsky** [opentofu/opentofu#1614]
### OpenTofu Version

```shell
GitHub repo on main branch
```

### Use Cases

This is to follow up the discussions on Slack, https://opentofucommunity.slack.com/archives/C05RKE7PS72/p1714960161198039. Janos would like to use an issue for migration guides. There are 3 new functions introduced in Terraform 1.8:
```
"encode_tfvars"
"decode_tfvars"
"encode_expr"
```
More details: https://developer.hashicorp.com/terraform/language/functions/terraform-encode_tfvars

### Attempted Solutions

N/A

**Comment by cube2222** [comment]
Additionally, I'd personally be in favour of adding these in OpenTofu 1.8. Not sure what others think?

**Comment by Gogotchuri** [comment]
Working on a draft PR

**Comment by Gogotchuri** [comment]
Hey everyone, I dug deeper into this issue and started the implementation.
I have concerns regarding the "encode_expr" function, it was needed to fix a very specific issue when passing values to tfe_variable.
Will OpenTofu ever need that function for compatibility?

**Comment by Evi1Pumpkin** [comment]
IMO, we shouldn't implement `encode_expr` because we gain nothing from it.
The drive behind implementing those functions is to make migrating from Terraform to OpenTofu easier. However, in this case, if a person uses the `tfe_variable` resource, they are using TFE, and it is very unlikely that they will use TFE with OpenTofu. So, for them to migrate to OpenTofu, they would have to stop using TFE and drop the `tfe_variable` resource, making it unwise to implement a function solely for this resource.
