### ISSUE TITLE
Investigate dead code in ./internal/moduledeps/

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#1796]
As far as I am aware, this code is not used by any other tofu package and was likely made obsolete due to some previous refactoring.  The git history should be investigated to determine if it truly can be removed.

**Comment by apparentlymart** [comment]
Indeed, `internal/moduledeps` is some legacy code from circa Terraform v0.10 from the very first implementation of `terraform init` automatically installing provider plugins over the network. At that time it was essentially bolted on the side as a separate concern, because the concept of providers being a kind of dependency arrived pretty late and the rest of the codebase wasn't designed to accommodate that.

That functionality was later subsumed into `internal/configs` as part of the configuration language rewrite in Terraform v0.12. For example, [`AllProviderRequirements` in `moduledeps`](https://github.com/opentofu/opentofu/blob/c8633519b9212c9f6a57d9a77fb768832a6d4b14/internal/moduledeps/module.go#L130-L143) was replaced by [`allProviderRequirements` in `configs`](https://github.com/opentofu/opentofu/blob/c8633519b9212c9f6a57d9a77fb768832a6d4b14/internal/configs/config.go#L377-L560).

(The new functions are of course, by now, considerably more complicated having grown to include various new and interesting ways that a module can imply a dependency on an official provider.)
