### ISSUE TITLE
Changing `create_before_destroy` and using `-refresh=false` could keep resources detached from state

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1806]
### OpenTofu Version

```shell
1.8.0-beta
```

### OpenTofu Configuration Files

Configuration during the first `apply`
```hcl
resource "local_file" "main" {
  content  = "test"
  filename = "foo.txt"

  lifecycle {
    create_before_destroy = true
  }
}
```

Configuration during that second command `tofu apply -refresh=false`
```hcl
resource "local_file" "main" {
  content  = "test"
  filename = "bar.txt"
}
```

### Debug Output

.

### Expected Behavior

Apply should remove the file and create a new one

### Actual Behavior

The plan actually claims it would destroy and recreate the file:
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

OpenTofu will perform the following actions:

  # local_file.main must be replaced
-/+ resource "local_file" "main" {
      ~ content_base64sha256 = "n4bQgYhMfWWaL+qgxVrQFaO/TxsrC4Is0V1sFbDwCgg=" -> (known after apply)
      ~ content_base64sha512 = "7iaw3Ur350mqGo7jwQrpkj9hiYB3Lkc/iBml1JQODbJ6wYX4oOHV+E+IvIh/1nsUNzLDBMxfqa2Ob1f1ACio/w==" -> (known after apply)
      ~ content_md5          = "098f6bcd4621d373cade4e832627b4f6" -> (known after apply)
      ~ content_sha1         = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
      ~ content_sha256       = "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08" -> (known after apply)
      ~ content_sha512       = "ee26b0dd4af7e749aa1a8ee3c10ae9923f618980772e473f8819a5d4940e0db27ac185f8a0e1d5f84f88bc887fd67b143732c304cc5fa9ad8e6f57f50028a8ff" -> (known after apply)
      ~ filename             = "foo.txt" -> "bar.txt" # forces replacement
      ~ id                   = "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

However, the actual apply only creates the file:
```
local_file.main: Creating...
local_file.main: Creation complete after 0s [id=a94a8fe5ccb19ba61c4c0873d391e987982fbbd3]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Steps to Reproduce

1. Create the configuration as mentioned in the first part
2. `tofu init`
3. `tofu apply`
4. Change the configuration as mentioned in the second part
5. `tofu apply -refresh=false`

### References

- Related issue in the Terraform Repository - https://github.com/hashicorp/terraform/issues/35218

**Comment by eduzgun** [comment]
Hi @RLRabinowitz, I've found a solution for this. Please can I be assigned to the issue?

**Comment by RLRabinowitz** [comment]
Thank you for volunteering @eduzgun , I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

**Comment by eduzgun** [comment]
> Thank you for volunteering @eduzgun , I've assigned you. Please read [the "I've been assigned an issue, now what?" section of the contribution guide](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#ive-been-assigned-an-issue-now-what) before you begin working.

Thank you. I will most likely complete it within 4 days.

**Comment by apparentlymart** [comment]
I want to caution that the `local_file` resource type in the `hashicorp/local` provider has some slightly quirky behaviors that can make things more confusing when testing OpenTofu Core behaviors. I don't _think_ any of this is actually a cause of the behavior this issue is describing, but I'm mentioning it in case someone encounters these while trying to test:

- The `ReadResource` behavior (which is what's disabled by `-refresh=false`) checks both that the file tracked in `filename` in the state is still present on disk _and_ that the current content of the file has the same checksum that was captured in the `id` attribute.

    If the content doesn't match the checksum then the resource type behaves as if the file isn't present at all, rather than updating the state to match the new content, and so this causes OpenTofu to behave as if the file wasn't present and propose to create it. During apply the "create" overwrites the original file and so the end result still converges, but the plan is misleading.

- This resource type has no implementation of update-in-place, so it treats all configuration changes as forcing replacement.

- Since there can only be one file on disk for any given filename, this resource type isn't really `create_before_destroy` compatible unless you make sure to always change the filename whenever you change anything else.

    If you try to use `create_before_destroy` _without_ changing the filename then OpenTofu Core will first ask the provider to "create" the file -- which in practice really overwrites it -- and then will ask the provider to "delete" the file, which deletes the file that was just written and thus leaves you with no file at all.

As I say, I don't think anything I wrote above is actually the _cause_ of this issue -- instead, it seems to be the fact that `-refresh=false` prevents OpenTofu Core from updating the `create_before_destroy` flag in the state before creating the plan -- but all of the above can potentially be confusing when trying to verify a fix using `local_file` as the testing vehicle, because it behaves slightly oddly compared to "normal" resource types that work with network APIs instead of with the filesystem.

**Comment by apparentlymart** [comment]
I feel unsure about what you presented as "the second bug"... the ideal behavior here is pretty debatable, but I believe the _intended_ behavior is that the configuration "wins" when it's still present, so that an operator doesn't become trapped in a situation where they've got `create_before_destroy` turned on for a resource that cannot properly support it and so they need to turn it off in the configuration (and thus get the state updated to match) in order to proceed.

I would concede that the comment you found in `NodeDestroyResourceInstance.CreateBeforeDestroy` seems like it's disagreeing with me, but I think it's important to keep in mind that much of the OpenTofu core functionality is designed under the assumption that the refresh phase _won't_ be disabled, or rather that an operator will only use `-refresh=false` when they _know_ the system is already properly synchronized and so no refreshing should be needed.

I must admit I'm not really sure what I'd change here. It could be argued that using `-refresh=false` in this situation is operator error because the state _does_ need refreshing. But I could also imagine countering that argument by saying that differences between configuration and state are supposed to be resolved by planning and applying rather than by refreshing: the concept of "refresh" is to reconcile the state with the real remote systems, and so it ideally shouldn't be influenced by the configuration _at all_. Alas, this is far from the only inconsistency of that kind, and so the true distinction between "refresh" and "plan" is rather ambiguous today and both `-refresh=false` _and_ `-refresh-only` are rife with quirky edge-cases. :confounded:

**Comment by ollevche** [comment]
Thank you @apparentlymart for the additional context. Indeed, I missed that in this case we have a conflict for `create_before_destroy` from both configuration and state for the same resource.

I would prefer to tweak the behavior of `NodeDestroyResourceInstance.CreateBeforeDestroy` to use the configuration value if it exists, otherwise use the one from the state. That way we would keep the original intent of prioritizing state's `create_before_destroy` for complete removal and correctly handle scenarios for resource changes.

**Comment by apparentlymart** [comment]
I think that's a plausible direction to try. It's tough to say with certainty that it won't cause some surprising behavior for _someone_, but as you say it should only affect cases where there's still a block in the configuration, that block in the configuration disagrees with the current state, _and_ the operator used `-refresh=false`, which is probably a pretty small cohort and I have trouble imagining how they'd prefer the current behavior in that scenario.
