### ISSUE TITLE
Allow specifying workspace at init time

### ISSUE THREAD

**Issue by lijok** [opentofu/opentofu#2104]
### OpenTofu Version

```shell
1.8.4
```

### The problem in your OpenTofu project

Now that Tofu supports string interpolation in its config (backend, etc), a usecase arises where the name of the workspace is used to derive the authentication and other contexts. Unfortunately, we must first run `init` before we can run `workspace select`, preventing this usecase from working.

### Attempted Solutions

Using a variable to specify the workspace we intend to use, at init time.

### Proposal

`tofu init -workspace dev.tenant-a` - Sets `terraform.workspace`, inits the stack and switches to that workspace.

Or, more ideally, we can set up / select workspaces without having to `init` first.

**Comment by apparentlymart** [comment]
I do notice that this is closed and so this response perhaps isn't very helpful to you in particular :grinning:  but just in case someone else finds this in future with a similar need:

OpenTofu decides the "current workspace" based on both a file in the `.terraform` directory that the `tofu workspace` commands manipulate _and_ on the environment variable `TF_WORKSPACE` which overrides the file on disk if it's set to a non-empty value.

Therefore I believe it would already be possible to force a particular workspace on `tofu init` by setting that environment variable when running it. For example, in a Unix-style shell that lets you set environment variables just for one command:

```shell
TF_WORKSPACE=dev.tenant-a tofu init
```

Manually creating the special file that `tofu workspace select` would normally overwrite would probably also work, but the exact details of how the commands manipulate the `.terraform` directory is not intended to be a compatibility constraint, so if anyone is intending to rely on either of these I would recommend preferring to use the environment variable due to its behavior already being documented and constrained by the OpenTofu v1.x Compatibility Promises.

**Comment by cam72cam** [comment]
That feedback is useful and worth considering under #2160
