### ISSUE TITLE
location of  lock file, .terraform.lock.hcl, does not follow TF_DATA_DIR

### ISSUE THREAD

**Issue by allpoints** [opentofu/opentofu#2113]
### OpenTofu Version

```shell
OpenTofu v1.8.4
on linux_amd64
```
```


### OpenTofu Configuration Files

```
The specifics of the config aren't relevant to this issue.
```


### Debug Output

```
X---.----x----.----x----.----x----.----x----.----x----.----x----.----x----.
XX Plan of code run against AWS account 'ops01'

> echo $TF_DATA_DIR
../Workspaces/ops01/example_dir

> tofu plan -var-file=$TF_VARS -out=${HOME}/plan.out
...
OpenTofu has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

X---.----x----.----x----.----x----.----x----.----x----.----x----.----x----.
XX Plan of exact same code run against AWS account 'ops02'
XX Note change to TF_DATA_DIR

> echo $TF_DATA_DIR
../Workspaces/ops02/example_dir

> tofu plan -var-file=$TF_VARS -out=${HOME}/plan.out
╷
│ Error: Required plugins are not installed
│
│ The installed provider plugins are not consistent with the packages selected in the dependency lock file:
│   - registry.opentofu.org/hashicorp/aws: there is no package for registry.opentofu.org/hashicorp/aws 5.73.0 cached in ../Workspaces/ops02/example_dir/providers
│
│ OpenTofu uses external plugins to integrate with a variety of different infrastructure services. To download the plugins required for this configuration, run:
│   tofu init
╵

> tofu init -var-file=$TF_VARS

Initializing the backend...
Initializing modules...

Initializing provider plugins...
- Reusing previous version of hashicorp/aws from the dependency lock file
- Installing hashicorp/aws v5.73.0...
- Installed hashicorp/aws v5.73.0 (signed, key ID 0C0AF313E5FD9F80)
                                                                           <redacted for space>
OpenTofu has been successfully initialized!
```


### Expected Behavior

The second run should have worked correctly using the state for _ops02_ stored the directory pointed to by the TF\_DATA\_DIR environment variable.  It should have recognized and used the versions of he provider modules stored in that directory by a previous `tofu init`


### Actual Behavior

The second run, against _ops02_ complained because it was using the .terraform.lock.hcl which was created for _ops01_.  This is because the lock file is not kept with all the other opentofu state in TF\_DATA\_DIR

### Steps to Reproduce

1. set TF\_DATA\_DIR to point to "directory A"
2. `tofu init`
3. set TF\_DATA\_DIR to point to "directory B"
4. `tofu init` at a later point in time so the module versions pulled in do not match those for "A"
5. set TF\_DATA\_DIR to point to point back to "directory A"
6. `tofu plan`

_plan_ will complain about a mismatch.

### Additional Context

This is one of those bug reports where following the reporting format makes the issue seem more complex than it is.  The short version is, the _.terraform.lock.hcl_ file should be maintained in the directory pointed to by TF\_DATA\_DIR and not at the top of the working directory.

If you're curios about the use case here, I have several AWS accounts which all use the exact same opentofu code.  The only thing that changes between them are some values set in a variable file.  Using TF_DATA_DIR allows me to keep to opentofu state in sync with the AWS account being managed.

### References

_No response_

**Comment by apparentlymart** [comment]
Hi @allpoints! Thanks for reporting this.

The `.terraform.lock.hcl` file is intentionally placed in your root module directory because the intention is for you to include it in your version control system as part of the source code for the root module.

This file cannot be included _in_ `.terraform` because this file is used as part of the process of _constructing_ that directory when you run `tofu init`. The dependency lock file dictates which providers are to be installed unless you bypass it with the `-upgrade` option.

With all of that said then: it sounds like this issue is essentially a feature request for some way to create the dependency lock file in a different place than the root directory, and then presumably for later `tofu init` calls to then read the dependency lock file from that same situation. Is that right?

I'd also like to understand your use-case more concretely. It seems like you are trying to use the same working directory to work with two different configurations that have different dependencies, which is not really a mode that OpenTofu was designed to operate in. But if we can understand better what your goal is, then maybe we can find a good way to support that use-case either with existing features or with new capabilities.

Thanks again!

**Comment by allpoints** [comment]
Thanks for the quick turn around.

To answer your question, the whole idea is to be able to _reuse_ the same code across AWS accounts.  For discussion,  imagine several almost identical, single tenant, customer environments, each in their own AWS account.  The only difference between the configurations are things related to naming, e.g. tags, which are easily specified via command line or a variable file.

Each Customer/AWS account uses its own TF_DATA_DIR and S3 based state backend.  The TF_DATA_DIR is specified via environment variable and the backed is specified using a variable in the code.

The problem now is the lock file with module version information.  As  modules are written to TF_DATA_DIR each Customer/AWS account _may_ have a different version depending on when they were initialized.  (See the example in the original report)

I would be _fine_  with the default location for the lock file, .terraform/modules/ and .terrafrom/providers/ directories.  In fact I would prefer that.  However the problem then becomes the  .terraform/terraform.tfstate  file which tracks where the S3 backend is for each account.  It's obviously critical that _this_ be kept in sync for each AWS account the code is run against.

I was unable to locate a feature that would allow me to specify the location of _only_ the internal state file which is why I use TF\_DATA\_DIR.   If one exists, I would be happy to use it.  If not,  my feature request would be a mechanism to override the default for this file.

**Comment by apparentlymart** [comment]
Thanks for the extra context! That helps a lot.

I think the most significant disconnect between your intentions and OpenTofu's current design is that OpenTofu considers the dependencies of a configuration (including which versions are currently selected) to essentially be a part of that configuration, and so under that model all of your customers sharing a single configuration would also effectively share the decision about which version of each provider to use.

(A different way to think about that same idea, in case it resonates better: OpenTofu's current model effectively expects you to track which version of your code each of your customers is using _and track the dependency selections as part of that code_. If you included the `.terraform.lock.hcl` file as part of the source code, then have some way to "remember" for each customer which version of the source code each customer is currently using, then you'd start by switching to the version of the code that is active for the target customer -- including its `.terraform.lock.hcl` file -- and then initialize from there.)

You instead want to treat the version selections as something independent of the configuration, which is not currently directly supported. However, if you are using some custom automation around OpenTofu then you could potentially fake it by making your automation try to copy from `$TF_DATA_DIR/.terraform.lock.hcl` to `./.terraform.lock.hcl` before running `tofu init` and then copy in the opposite direction afterwards to capture any modifications OpenTofu has made to the file.

I believe Terragrunt currently has some behavior similar to this to support _its_ mechanisms for using the same module directory multiple times for different purposes, so perhaps we can find some common ground between your design and Terragrunt's design to try to better support both of them while making sure we don't undermine the guarantees the dependency lock file is intended to provide.

Unfortunately I suspect whatever we do here would need to involve an entirely new setting of some kind, rather than just retroactively growing the scope of `TF_DATA_DIR`, because existing automation could be relying on OpenTofu's current treatment of the dependency lock file while still using `TF_DATA_DIR` for some unrelated purpose.

**Comment by allpoints** [comment]
I understand the point and, as I said, I would prefer to have a consistent set of modules across all the environments.

The goal that started me down this path was the need to have a  .terraform/terraform.tfstate file that remained in sync with the AWS account being maintained by the code.  If it makes more sense to turn this into a feature request to be able to specify the location/name of "only this specific file" that would work well.  Uness there's something I'm missing as to why that must be part of the TF\_DATA\_DIR?

**Comment by apparentlymart** [comment]
`TF_DATA_DIR` is, broadly, "all of the transient local state OpenTofu needs to keep track of for a working directory".

Exactly what gets placed in that directory and in what format is implementation details subject to change at any time in future versions of OpenTofu, so I expect that's the main reason why individual parts of that are not exposed as their own settings: it's not intended to be guaranteed that any particular thing you find in there will even _exist_ in future versions of OpenTofu, although admittedly there's no current plan to change anything about the `.terraform/terraform.tfstate` file.

---

FWIW I think even if you _did_ have some way to repoint _just that backend state file_ to a different location, you'd still have a similar problem: the `.terraform/providers` directory (the local cache of the provider plugins required for the configuration) would still contain "the wrong versions" of the providers for your directory A, and so I think you'd need to reinit regardless.

Your current experience of this message is OpenTofu noticing that the dependency lock file disagrees with the cache directory, but step 4 of your repro steps would still cause the cache directory to be "wrong" and so you'd still need to run `tofu init` again before your step 6 to restore the versions that directory A was relying on.

All of that is why I was perceiving this more as a "use multiple dependency lock files in the same directory"-shaped problem, instead of a "share the provider cache directory between all of the customers (by swapping out only the local backend state file)"-shaped problem.

**Comment by allpoints** [comment]
Re ```... even if you did have some way to repoint just that backend state file to a different location, you'd still have a similar problem: the .terraform/providers directory (the local cache of the provider plugins required for the configuration) would still contain "the wrong versions" of the providers for your directory A```

Perhaps I'm misunderstanding some of the lower level details  but  a single module cache that would be used across disparate `tofu plan` runs  seems fine for _my_ use case.  I only see an issue when the lock file gets out of sync with the cache and that's hasn't been very often.  Put another way, for _my_ case, it would be fine if I ran `tofu init --upgrade` before each `tofu plan`.

As long as I can can keep the infrastructure state file unique to and in sync with the AWS account I'm running against things work well.

To be fair, I may be using the tool outside of it's design parameters.  However this feels like it would be a common use case, i.e.  identical configs with minor input changes.

It's also clear this is, at the very least, not a bug so feel free to close or re-categorize as you see fit.

Thanks

**Comment by apparentlymart** [comment]
Thanks again for the additional context, @allpoints.

Initially I was going to suggest that running `tofu init -upgrade` before each `tofu plan` should be sufficient to make this work on today's OpenTofu, but I think there is one important caveat to that:

The `-upgrade` option basically means "ignore the selections in the dependency lock file, and the newest available compatible version of each provider". So it _should_ have the effect of bypassing the error message you saw, because it will cause the right providers to be installed.

But notably it _won't_ preserve whatever provider versions a particular customer was using last time you applied changes there, because OpenTofu uses the dependency lock file as its "memory" of which provider versions were selected last time, and so if you ignore the dependency lock file then OpenTofu effectively has no memory of those selections: you'll always be upgrading to latest each time you switch to a different customer, and you'd earlier expressed that you wanted to instead preserve the current selections for each customer separately.

**Comment by allpoints** [comment]
Understood.  I think maybe I wasn't clear.   For _may_ use case it's not so much that the accounts have to be maintained separately as that it needs to be consistent.  So, if _every_ account were using the same version of, eg, the AWS module that would be fine.  It would also be fine if they were, always using the _latest_ version modules.

At the end of the day, what I want to do is use the exact same code in the working directory across multiple AWS accounts.  This is in conflict with how opentofu tracks internal state, e.g. which modules are installed, where to look for the cloud state (S3 backend) etc.

I'm aware there are workarounds for this.  I could, for example, use some other tool to manage opentofu (?terragrut?).  Alternatively, I could move all the code into a module and maintain forks for each account I want to manage which simply refer to a common module.

Having said all that, I do appreciate your time in talking through all this.  It feels like there's a feature request in here somewhere and I may put one together after I've thought about it for a bit.  In the mean time, the tool is working as intended so I'm going to close the bug.

Thanks again.
