### ISSUE TITLE
Option to turn off override files processing (or) Ability to process overrides within different modules.

### ISSUE THREAD

**Issue by vamshikrishna83** [opentofu/opentofu#2129]
### OpenTofu Version

```shell
OpenTofu v1.8.4
on linux_amd64
```

### The problem in your OpenTofu project

We have the need to enable some subset of changes to be deployed only on development environments, where as the production environments should have verified changes alone. If i understand this correctly, we could make use of override functionality to add new changes within a resource to override file and deployment in development environments would process the overrides and work as expected.

But, as we maintain the same code / configuration for all environments - this would deploy the same changes (with override processing) to production environments as well. This is not intended.

### Attempted Solutions

Override

### Proposal

To solve this issue - it would be nice to have an option to turn off override processing, so that we can explicitly turn it off for production tenancies. Another way to make this work - could be to allow processing of override files across different modules - root / child module. For example - main configuration will be part of child module, and override configuration will be part of root module for development environment, which gets merged into the latest configuration and gets deployed to development environment. For production environment - no override file will be included, which will ensure main configuration to be deployed in production environments.

**Comment by cam72cam** [comment]
To add on to what @abstractionfactory wrote, using `count = <some condition that indicates prod or dev> ? 1 : 0` will allow you to enable or disable components of your infrastructure dynamically.

**Comment by apparentlymart** [comment]
Just to add some context to the above:

The main uses of the [Override Files](https://opentofu.org/docs/language/files/override/) mechanism that people have told me about is when running OpenTofu indirectly through an automation tool, such as a wrapper script, or Terragrunt, or a "TACOS", and when that tool needs to make some transient adjustments to the configuration to adapt it to the automation environment in some way.

For example, the most popular variation I know of is having the automation generate an override file containing a systematically-generated backend configuration, so that the automation can ensure that state snapshots will be stored in an appropriate place based on the current system's conventions.

Some other automations also use this as a way to force a particular provider configuration, such as if the automation is acting as an OpenID Connect provider and so needs to force a particular provider to be configured to use a JSON Web Token that was generated for that particular run.

The common theme in these use-cases is that it's to introduce some sort of contextual information that makes the configuration integrate better with its execution environment. As others have said above, it's quite a marginal feature and was not intended for creating substantial variations in configuration between environments. Input variables, and dynamic expressions deriving other values from them, are the typical approach for describing expected variations between environments.

**Comment by vamshikrishna83** [comment]
Ok. May be override files are not ideal to deal with incremental changes in the configuration.

Wouldn't it still be useful to have an option to turn off override processing, if the user wishes to do so?

**Comment by cam72cam** [comment]
Thanks for the discussion @vamshikrishna83, let us know if can not solve this problem for you.
