### ISSUE TITLE
Add support for ElasticCache Valkey engine

### ISSUE THREAD

**Issue by shahen94** [opentofu/opentofu#2156]
### OpenTofu Version

```shell
OpenTofu v1.8.5
on darwin_arm64
```

### The problem in your OpenTofu project

I'm trying to use the Valkey cache that's newly released in AWS, and it seems OpenTofu doesn't have support for that

### Attempted Solutions

Opentofu throws an error when I'm trying to use engine.

```tf
resource "aws_elasticache_cluster" "this" {
  cluster_id           = var.cluster_id
  engine               = "valkey"
  node_type            = var.node_type
  num_cache_nodes      = var.nodes_count
  parameter_group_name = var.parameter_group_name
  port                 = var.port
  subnet_group_name    = aws_elasticache_subnet_group.this.name
  security_group_ids   = [aws_security_group.this.id]
}

```

### Proposal

Add valley in a list of supported Elastic Cache clusters, Enable validation & add parameters group.

### References

https://aws.amazon.com/about-aws/whats-new/2024/10/amazon-elasticache-valkey/
https://aws.amazon.com/elasticache/redis/
https://aws.amazon.com/blogs/opensource/why-aws-supports-valkey/

**Comment by shahen94** [comment]
> [!TIP]
> Invalid! [I found that it's already done](https://github.com/opentofu/terraform-provider-aws/commit/834404e295d1b352efc2b6e1bd124e6374703879), the issue is on my side. Closing this out

**Comment by shahen94** [comment]
Nope, the Valkey is not listed in the possible engine versions

https://github.com/opentofu/terraform-provider-aws/blob/main/internal/service/elasticache/cluster.go#L145

**Comment by apparentlymart** [comment]
Hi @shahen94,

The `opentofu/terraform-provider-aws` is just a read-only mirror of the upstream [`hashcorp/terraform-provider-aws`](https://github.com/hashicorp/terraform-provider-aws/), maintained by a separate team. The OpenTofu team does not maintain this provider.

I think what you've requested here is already represented in that repository by https://github.com/hashicorp/terraform-provider-aws/issues/39905, so perhaps you could add a :+1: upvote to that issue and subscribe there for updates. If you think your request is different than the one I've linked then I suggest opening a new issue in that other repository, so that the maintainers of that provider can consider it.

There isn't anything we could do in _this_ repository to add the functionality you're hoping for, and so I'm going to close this issue. Thanks!
