### ISSUE TITLE
`filesystem_mirror` doesn't work for provider version `0.0.0`

### ISSUE THREAD

**Issue by nazarewk** [opentofu/opentofu#2225]
### OpenTofu Version

```shell
OpenTofu v1.8.5
on linux_amd64
```

### OpenTofu Configuration Files

to demonstrate issue run https://gist.github.com/nazarewk/9421835b12445359e9c78b78a59eda61#file-tofu-issue-sh 

`.tofurc`:
```hcl
provider_installation {
  filesystem_mirror {
    path    = "/home/kdn/.config/JetBrains/IntelliJIdea2024.3/scratches/tofu-report.yMnMPc/plugins"
    include = ["registry.terraform.io/hashicorp/scaffolding"]
  }
  direct {
    exclude = ["registry.terraform.io/hashicorp/scaffolding"]
  }
}
```

`main.tf`:
```hcl
terraform {
  required_providers {
    scaffolding = {
      source = "registry.terraform.io/hashicorp/scaffolding"
      version = "0.0.0"
    }
  }
}
```

mirror structure:
```
/home/kdn/.config/JetBrains/IntelliJIdea2024.3/scratches/tofu-report.yMnMPc/pluginsratches/tofu-report.yMnMPc/plugins/
└── registry.terraform.io
    └── hashicorp
        └── scaffolding
            ├── 0.0.0
            │   └── linux_amd64
            │       └── terraform-provider-scaffolding_v0.0.0
            └── 0.0.1
                └── linux_amd64
                    └── terraform-provider-scaffolding_v0.0.1

8 directories, 2 files
```

### Debug Output

see https://gist.github.com/nazarewk/9421835b12445359e9c78b78a59eda61

this seem the most relevant:
```
2024-11-28T13:35:42.594+0100 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/scaffolding v0.0.0 for linux_amd64 at /home/kdn/.config/JetBrains/IntelliJIdea2024.3/scratches/tofu-report.OtWtNZ/plugins/registry.terraform.io/hashicorp/scaffolding/0.0.0/linux_amd64
2024-11-28T13:35:42.594+0100 [TRACE] getproviders.SearchLocalDirectory: found registry.terraform.io/hashicorp/scaffolding v0.0.1 for linux_amd64 at /home/kdn/.config/JetBrains/IntelliJIdea2024.3/scratches/tofu-report.OtWtNZ/plugins/registry.terraform.io/hashicorp/scaffolding/0.0.1/linux_amd64
2024-11-28T13:35:42.594+0100 [DEBUG] no available releases match the given constraints 0.0.0
2024-11-28T13:35:42.594+0100 [DEBUG] Available releases: [0.0.0 0.0.1]
```

### Expected Behavior

`tofu init` works

### Actual Behavior

```
╷
│ Error: Failed to resolve provider packages
│ 
│ Could not resolve provider registry.terraform.io/hashicorp/scaffolding: no available releases match the given constraints 0.0.0
╵
```

### Steps to Reproduce

run https://gist.github.com/nazarewk/9421835b12445359e9c78b78a59eda61#file-tofu-issue-sh

### Additional Context

- discovered during a debugging discussion at Slack https://opentofucommunity.slack.com/archives/C05R0FD0VRU/p1732708063998669

**Comment by apparentlymart** [comment]
I think the trick here is that `0.0.0` happens to match the internal representation of "unversioned" and so it cannot actually match as a valid version. While that special case is unfortunate, it runs quite deep -- it actually belongs to the third-party library we use for version matching, rather than to OpenTofu itself.

Perhaps in the short term we could at least change the filesystem mirror search code to detect that case and emit a `[WARN]` log about it, so there'd be some explicit clue that it can't work.

---

The other thing I'd note is that if you are intending to use this to represent that a provider hasn't yet got any published versions _at all_ then that's the use-case for [the special `dev_overrides` block](https://opentofu.org/docs/cli/config/config-file/#development-overrides-for-provider-developers): any providers mentioned there are just directly selected regardless of version constraints, on the assumption that someone who is developing a provider wants to just always use the latest executable they've built and not worry about assigning it a version number.

There are various quirks with `dev_overrides` that make that not a suitable mechanism for anything other than provider development, but the context here makes me suspect that provider development _is_ the goal, in which case here's a different way to get there which doesn't require the provider to have _any_ version number:

```hcl
provider_installation {
  dev_overrides {
    "registry.terraform.io/hashicorp/scaffolding" = "/home/kdn/etc/etc"
  }
}
```

The `/home/kdn/etc/etc` directory in this case should _directly contain_ the `terraform-provider-scaffolding` executable, without any nested directory structure. The special handling of dev overrides will then cause OpenTofu to ignore whatever is cached for that provider in `.terraform/providers` and use the given directory directly instead.

Since OpenTofu ignores `.terraform/providers` for this provider, the typical usage pattern is just to skip running `tofu init` _at all_ when developing a provider in this way, since `tofu init`'s job is to populate the `.terraform/providers` directory and that's a useless thing to do when you've overridden it anyway.

When I do this I typically drop a `cliconfig.tfrc` file with the `dev_overrides` block in the same directory as the `.tf` files I'm using for testing and run OpenTofu like this:

```shell
TF_CLI_CONFIG_FILE=cliconfig.tfrc tofu plan
```

(or, equivalently, set that environment variable in your shell before you run any other commands.)
