### ISSUE TITLE
Resources persist between tests when testing nested modules with `tofu test`

### ISSUE THREAD

**Issue by yozoraozora** [opentofu/opentofu#2260]
### OpenTofu Version

```shell
`1.8.6`

Behavior is as expected in version `1.7.0`
This issue appears in versions `>=1.7.1`
```

### OpenTofu Configuration Files

Reproducer available at:
https://github.com/yozoraozora/tofu-test

### Debug Output

https://gist.github.com/yozoraozora/a88b7333459805c78b996248175da5e4

### Expected Behavior

Test#1 creates 3 resources. These resources should be destroyed as part of the apply for test#2
Test#2 creates 3 resources. There should only be 3 resources in total.

### Actual Behavior

Test#1 creates 3 resources.
Test#2 destroys previous 3 and creates 3 new resources. Assertion fails as it thinks there are now 6 resources in total.

### Steps to Reproduce

In `test-parent-module` dir:
1. `tofu init`
2. `tofu test`

**Comment by ollevche** [comment]
Hey @yozoraozora, thank you for the issue! I will check it out shortly

**Comment by ollevche** [comment]
In v1.7.1 we fixed https://github.com/opentofu/opentofu/issues/1359 issue (unusable modules with no resources) by copying all the missing modules from plan ([PR changes](https://github.com/opentofu/opentofu/pull/1409/files#diff-b25dc5192febfed775106f6b0b46358593bc13e0af77bc6aed30c23f05e9c3e7R201)).

This is relevant to this particular issue, since after the first run we still have _almost_ empty modules for `1`, `2`, and `3` in plan state. These modules contain only outputs and no actual resources, so that's why they have been kept in the plan state (and haven't been pruned).

I am still finding out why the outputs were not destroyed in this particular case. Potentially, this issue affects more than `tofu test`.

**Comment by ollevche** [comment]
Here are a few more bullet points to better describe the problem:

* tofu core doesn't store non-root module outputs in a state file
* tofu core doesn't try to destroy such output values (so they present in in-mem state representation)
* such outputs are available for assertions in tofu test
* tofu test has a special planned state object which is a state after the plan (used for tofu test purposes only)
* planned state is used to retrieve module outputs
* planned state has non-destroyed non-root module outputs (which should be destroyed for tofu test)
* there is no difference between non-destroyed non-root module outputs and actual non-root module with only outputs inside
