### ISSUE TITLE
provider for_each recieves input variables that haven't been type-converted, de-nulled, or validated

### ISSUE THREAD

**Issue by OYTAdmin** [opentofu/opentofu#2268]
### OpenTofu Version

```shell
❯ tofu version
OpenTofu v1.9.0-alpha2
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v5.80.0
```

### OpenTofu Configuration Files

```hcl
variable "regions" {
  type = set(string)
}
```

```hcl
terraform {
  required_version = ">= 1.5.3"

  required_providers {
    aws = {
      source  = "opentofu/aws"
      version = "~>5.80" #The latest version at the time new repo was created
    }
  }
}

provider "aws" {
  alias    = "by_region"
  region   = each.value
  for_each = var.regions
}
```

```hcl
#in terraformtfvars:
regions          = ["us-east-1", "us-west-2"]
```

### Debug Output

N/A... if you really need it let me know but I suspect the root cause is simpler than this.

### Expected Behavior

tofu init should have succeeded, parsing my input variable as a set of strings and not a tuple.

### Actual Behavior

```
│ Error: Invalid for_each argument
│
│   on providers.tf line 16, in provider "aws":
│   16:   for_each = var.regions
│     ├────────────────
│     │ var.regions is tuple with 2 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type tuple.
```

### Steps to Reproduce

Define an input variable 'regions' as set(string) type in variables.tf:

```hcl
variable "regions" {
  type = set(string)
}
```

In terraform.tfvars, include
```hcl
regions = ["us-east-1", "us-west-2"]
```

In providers, set up AWS provider with for_each over regions:
```hcl
terraform {
  required_version = ">= 1.5.3"

  required_providers {
    aws = {
      source  = "opentofu/aws"
      version = "~>5.80" #The latest version at the time new repo was created
    }
  }
}

provider "aws" {
  alias    = "by_region"
  region   = each.value
  for_each = var.regions
}
```

Run tofu init. Get error:

```
│ Error: Invalid for_each argument
│
│   on providers.tf line 16, in provider "aws":
│   16:   for_each = var.regions
│     ├────────────────
│     │ var.regions is tuple with 2 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type tuple.
```

### Additional Context

Wrapping the iteration in the 'toset' function is a successful workaround:

```hcl
provider "aws" {
  alias    = "by_region"
  region   = each.value
  for_each = toset(var.regions)
}
```

**Comment by cam72cam** [comment]
Closing as duplicate

**Comment by apparentlymart** [comment]
I don't think this is actually a duplicate. :thinking: 

The issue describes assigning a variable that's declared as being `set(string)` to the provider `for_each`.

It seems like the `for_each` evaluation in early eval in `package configs` is not correctly handling the input variable type conversions and other such preparation. For other `for_each` that gets handled in `package tofu` as part of the normal evaluation process, but for provider `for_each` we handle that inside `package configs` using the early eval process.

**Comment by apparentlymart** [comment]
I think the problem originates here:

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/configs/module_call.go#L251-L272

This is directly evaluating the expression given in the caller, but it's not performing the other steps that would typically happen to "finalize" the input variable value for use inside the module it was being passed to:

- Convert it to the type constraint given in `type`.
- Handle `nullable = false` by substituting the default value if the expression returns `null`.
- Check any `validation` blocks to see if they pass.

In the normal codepath that's handled by these two functions:

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/tofu/eval_variable.go#L27-L196

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/tofu/eval_variable.go#L204-L287

**Comment by apparentlymart** [comment]
After digging into this a little further I realize that although the code I found above _does_ have the bug I attributed to it, that probably isn't actually what was involved in this particular issue because that would only arise for a `provider` block inside a nested module, whereas this issue is talking about a `provider` block (and a variable declaration) in the root module.

There are a number of different variations of this same code in different parts of the code base, all of which seem to have their own variation of the same bug, since it seems like they were copy-pasted and lightly modified for different contexts:

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/command/meta_config.go#L129-L157

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/backend/local/backend_local.go#L269-L293

I think that to fully fix this bug will require updating all three of these cases, so that the variable value will be treated as correct in the root module during planning, in the root module during apply, and in child modules in all phases.

Since the type conversion, nullable-handling, and validation are together a nontrivial amount of subtle code I'm going to see what it'll take to factor it out somewhere that all three of these _and_ the original case in `package tofu` can share it, although for the v1.9 release I expect to leave `package tofu` still with its own copy just because it seems like an inappropriate level of risk to significantly refactor how dynamic variable validation works when we're already in the beta period for v1.9.

**Comment by apparentlymart** [comment]
After poking around even more, it seems like a better compromise would be to put the extra logic near the end of this function:

https://github.com/opentofu/opentofu/blob/f5930c6ce1da94a73866fb4ad416b371b9d5e409/internal/configs/static_scope.go#L240-L264

The existing handling of the "sensitive" flag at the end of this suggests that this was the intended place for finalization logic to live for the early eval codepath. Although in the long run we'd prefer to have a single function that can be shared between both early and dynamic eval, to keep the risk low for the v1.9 release I'm going to implement some equivalent logic inline in this function for now and then we'll think about how to reduce the amount of code duplication for early eval in a later release.

**Comment by apparentlymart** [comment]
I've pushed a first attempt at this in https://github.com/opentofu/opentofu/pull/2273.

I decided to ignore validation rules for now because they don't affect the final value. Skipping validation does mean that invalid values will get to expressions that they shouldn't reach, but that's already true today and so ignoring it won't make it any worse.

The most important thing is making sure that the type conversions and default value substitutions are performed correctly enough for the rest of the language to receive variable values of the expected types, to avoid incorrect errors like the one reported here.

As noted before, the unit testing of this part of the code is pretty sparse and so I'm focusing on manual testing first and then will figure out how best to introduce automated testing (possibly just end-to-end testing for now) for this case once it seems like we have the correct behavior.

**Comment by apparentlymart** [comment]
Thanks again for reporting this, @OYTAdmin! I've merged a low-risk surgical fix for this problem that we'll include in the next v1.9.0 prerelease.

We do also intend to have a deeper discussion about how we might rearrange the early eval code so that it can share more logic with the traditional language runtime, but since our current focus is on getting v1.9.0 released I expect we'll wait until the new year to discuss that more, and then make some new issues and/or RFCs to cover whatever comes from that discussion.
