### ISSUE TITLE
Unexpected output when using -out command line parameter

### ISSUE THREAD

**Issue by OYTAdmin** [opentofu/opentofu#2294]
### OpenTofu Version

```shell
❯ tofu -version
OpenTofu v1.9.0-beta2
on windows_amd64
+ provider registry.opentofu.org/opentofu/aws v5.80.0
```

### OpenTofu Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

When using the -out command line argument with the plan command, tofu should write the plan to the specified file

### Actual Behavior

❯ tofu plan -out=plan.json
╷
│ Error: Too many command line arguments
│
│ To specify a working directory for the plan, use the global -chdir flag.
╵

### Steps to Reproduce

1. tofu plan -out=plan.json

### Additional Context

n/a

**Comment by OYTAdmin** [comment]
The output from the command above also says:

For more help on using this command, run:
  tofu plan -help
  
  When I run tofu plan -help, part of the output is:
  
    -out=path                  Write a plan file to the given path. This can be
                             used as input to the "apply" command.
                             
So it appears to me that I am using the command line as specified in the help file.

**Comment by ollevche** [comment]
Hello @OYTAdmin and thank you for the issue! This is a pretty basic use-case of OpenTofu and I am surprised it doesn't work in your environment. Could you please share trace logs so I can take a look on what OpenTofu actually reads from cli? I don't have a windows station right now to test it (not reproducable on macos).

**Comment by OYTAdmin** [comment]
I don't know that I'm comfortable submitting a PR for this, but my curiosity got the better of me and I cloned the repo. Line 173 of plan_test.go suggests that this is being tested and should work. 

Working on getting the trace logs, but this INFO might be a clue:

2024-12-13T09:15:40.854-0600 [INFO]  CLI command args: []string{"plan", "-out=plan", ".json"}

It looks like my filename plan.json is being split at the period, maybe? 

Let me get a trace log...

**Comment by OYTAdmin** [comment]
The trace output is mercifully short:

❯ tofu plan -out=plan.json
2024-12-13T09:19:27.101-0600 [INFO]  OpenTofu version: 1.9.0 beta2
2024-12-13T09:19:27.102-0600 [DEBUG] using github.com/hashicorp/go-tfe v1.36.0
2024-12-13T09:19:27.102-0600 [DEBUG] using github.com/opentofu/hcl/v2 v2.0.0-20240814143621-8048794c5c52
2024-12-13T09:19:27.102-0600 [DEBUG] using github.com/hashicorp/terraform-svchost v0.1.1
2024-12-13T09:19:27.103-0600 [DEBUG] using github.com/zclconf/go-cty v1.14.4
2024-12-13T09:19:27.103-0600 [INFO]  Go runtime version: go1.22.8
2024-12-13T09:19:27.103-0600 [INFO]  CLI args: []string{"C:\\Users\\Matthew\\CustomAppsInPath\\tofu.exe", "plan", "-out=plan", ".json"}
2024-12-13T09:19:27.104-0600 [TRACE] Stdout is a terminal of width 176
2024-12-13T09:19:27.104-0600 [TRACE] Stderr is a terminal of width 176
2024-12-13T09:19:27.104-0600 [TRACE] Stdin is a terminal
2024-12-13T09:19:27.108-0600 [DEBUG] Attempting to open CLI config file: C:\Users\<myname>\AppData\Roaming\terraform.rc
2024-12-13T09:19:27.108-0600 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2024-12-13T09:19:27.109-0600 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2024-12-13T09:19:27.109-0600 [DEBUG] ignoring non-existing provider search directory C:\Users\Matthew\AppData\Roaming\terraform.d\plugins
2024-12-13T09:19:27.110-0600 [DEBUG] ignoring non-existing provider search directory C:\Users\Matthew\AppData\Roaming\HashiCorp\Terraform\plugins
2024-12-13T09:19:27.111-0600 [DEBUG] Found the config directory: C:\Users\<myname>\AppData\Roaming\terraform.d
2024-12-13T09:19:27.111-0600 [INFO]  CLI command args: []string{"plan", "-out=plan", ".json"}

**Comment by apparentlymart** [comment]
This unfortunately seems like a classic PowerShell parsing bug.

On Windows the traditional model is that the command line interpreter just does some basic string substitution and then passes a full command line string to the program being executed and then the program parses it.

But PowerShell is designed more like a Unix-style shell that wants to tokenize the command line into separate arguments first and then pass those arguments to the target program. So when you use PowerShell to run an external program (rather than a PowerShell cmdlet) the following sequence of things happens:

1. PowerShell parses the command line itself, splitting it into a sequence of tokens.
2. PowerShell then sticks all of the tokens back together into a single string following the conventions expected for command line arguments by the Microsoft Visual C++ runtime, and passes that to the program.
3. The program then parses the command line again, hopefully using the same C++ runtime conventions.

Unfortunately, for reasons that I've never quite understood PowerShell's parser seems to decide to treat `-out=plan.json` as a series of two arguments: `-out=plan` and `.json`. In Step 2 above it then constructs something like `C:\Users\\CustomAppsInPath\tofu.exe plan -out=plan .json` and then OpenTofu (using code in the Go language runtime that mimics the Microsoft Visual C++ runtime) parses that into arguments like we can see in your log:

```
[]string{"C:\Users\\CustomAppsInPath\tofu.exe", "plan", "-out=plan", ".json"}
```

I think you can avoid this quirk by adding some quotes to the command line to change how PowerShell parses it. I forget exactly what the rules are but I might try something like `tofu plan "-out=plan.json"`.

However, I would note that an OpenTofu saved plan file _is not JSON_, so `.json` is an unusual suffix to use for it. I typically just name it `tfplan` with no suffix at all, which in your case would have the advantage of not including a dot for PowerShell to get confused about: `tofu plan -out=tfplan`

Since this is a PowerShell behavior rather than an OpenTofu behavior, unfortunately I don't think there's really any good way for OpenTofu to compensate for it.

(When I've seen this before it was with people trying to write arguments like `-var-file=something.tfvars`, which causes the same quirky behavior of passing two separate arguments `-var-file=something .tfvars` and thus the same symptom of a confusing error message from OpenTofu, because PowerShell passed OpenTofu something different than what the user typed.)

**Comment by OYTAdmin** [comment]
Thank you, @apparentlymart 

I am indeed using PowerShell. Wrapping the "-out=tofu.plan" in quotes allowed the command to run, then I used "tofu show -json tofu.plan" (which weirdly didn't require quoting) to get the JSON representation.

Let's see if I can close my own issue...

**Comment by apparentlymart** [comment]
I think the case that confuses PowerShell is a single argument containing an entire option, with the value delimited with an `=`, where the value has a suffix starting with a dot.

So `-json tofu.plan` doesn't cause the problem, but `json=tofu.plan` hypothetically would, if that were valid. (It isn't valid because `-json` is a separate option with no argument, and `tofu.plan` is a positional argument to the `tofu show` command independent of that argument.)

Unfortunately I've mostly just inferred this quirk from helping various folks encountering problems just like yours. I've never actually found any documentation describing this particular behavior.

The documentation [Passing arguments that contain quote characters](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.4#passing-arguments-to-native-commands) does give some broad details like what I summarized in my earlier comment about the fact that PowerShell first parses the command line and then turns it back into a single string again, but nothing in that section or elsewhere on that page seems to mention that a `.` character within an argument might be treated as an argument delimiter or states what situations that interpretation is used. :confounded:

**Comment by apparentlymart** [comment]
This issue inspired me to go hunting once more and it seems like this behavior is covered by an issue that I apparently missed on my previous travels: https://github.com/PowerShell/PowerShell/issues/6291
