### ISSUE TITLE
When `tofu test` has left-over resources in the state file, it should write it out to a file for investigation purposes.

### ISSUE THREAD

**Issue by eranelbaz** [opentofu/opentofu#248]
### OpenTF Version

```shell
`OpenTF v1.6.0-dev`
```

### Use Cases

As `opentf test` runs `opentf apply` and `opentf destroy` if for some reason OpenTF fails to destroy the resources it only prints the OpenTF resource ID, which makes the cleaning process hard as you don't know the actual Cloud Resource Id.

`main.tf`
```
resource "null_resource" "failing" {
  depends_on = [null_resource.failing_will_depend_on_me]
  provisioner "local-exec" {
    when    = destroy
    command = "exit 1"
  }
}

resource "null_resource" "failing_will_depend_on_me" {

}

check "check" {
  assert {
    condition = length(null_resource.failing.id) > 0
    error_message = "invalid value"
  }
}
```

`main.tftest.hcl`
```
run "test" {
}
```

```
> opentf test
main.tftest.hcl... pass
  run "test"... pass
OpenTF encountered an error destroying resources created while executing main.tftest.hcl/test.
╷
│ Error: local-exec provisioner error
│ 
│   with null_resource.failing,
│   on main.tf line 3, in resource "null_resource" "failing":
│    3:   provisioner "local-exec" {
│ 
│ Error running command 'exit 1': exit status 1. Output: 
╵

OpenTF left the following resources in state after executing main.tftest.hcl/test, and they need to be cleaned up manually:
  - null_resource.failing
  - null_resource.failing_will_depend_on_me

Success! 1 passed, 0 failed.
```

And as `opentf test` manages the state in memory, I can't print the resource id by using `opentf state show ...`

### Proposal

Print the actual cloud resource ids after OpenTF resource id

**Comment by misha-slyusarev** [comment]
@eranelbaz could I be assigned to this issue?

**Comment by cube2222** [comment]
I think what @eranelbaz proposed is an excellent idea.

I suppose when the final state is non-empty, we should write a warning in the test output and write out the statefile to a file, so the user can inspect it.

**Comment by Kazzhar** [comment]
Hi, I would like to work on this issue.

**Comment by janosdebugs** [comment]
Hey @Kazzhar , thank you for your help. I've assigned you to the issue. Please let us know what your estimate on time is so we can unassign the issue at that time if we don't hear back from you and someone else wants to work on it.

**Comment by Kazzhar** [comment]
Thanks @janosdebugs, I think a week's time should be adequate. I hope to finish up by the end of next week (2nd of Feb).

**Comment by janosdebugs** [comment]
Thank you @Kazzhar please reach out on the #dev-general channel on the [OpenTofu Slack](https://opentofu.org/slack) if you run into trouble.

**Comment by Kazzhar** [comment]
Hi, I was working on this issue and since it has been a week, here is the progress I've made so far:

- I have understood the working of state files and such, and have found and identified the location in code where the state file generated during the "test" process would be needed to be stored, as discussed earlier in this thread.

- I thought that I would see how exactly the creation and storage of the state file happens when we run "tofu apply". I eventually reached [https://github.com/opentofu/opentofu/blob/main/internal/backend/local/backend_apply.go](url) and noticed how the process of storing state files actually depends on the backend type.

- I currently am investigating how the state file is being written to in the Local backend. I see how the data is being fed into the File struct here [https://github.com/opentofu/opentofu/blob/64f419e33548d4a243b60c14ffe37be70e3eaf34/internal/backend/local/backend_apply.go#L264](url). However I cannot find how data from here is being written to the actual state file.

Could someone please help me out with this?

**Comment by Kazzhar** [comment]
Hi, I have the following questions pertaining to this issue:

- The function PersistState() which takes an argument of type *tofu.Schemas does not use the schema throughout the execution of the function, why is there a need to pass it through to the function?
![Screenshot 2024-02-06 at 1 06 08 PM](https://github.com/opentofu/opentofu/assets/76555721/9547c331-64b9-4304-b57d-fb27ad0f8e48)

Permalink: https://github.com/opentofu/opentofu/blob/199ec898e634b5c2782664cf436bac94eae3fd10/internal/states/statemgr/filesystem.go#L161

- Previously in the discussions, @cube2222 talked about storing the state persistently when the "test" command is run. I followed through the workflow of "tofu apply" and I noticed how the state file was written to "terraform.tfstate". In another instance here : https://github.com/opentofu/opentofu/blob/199ec898e634b5c2782664cf436bac94eae3fd10/internal/backend/local/backend_apply.go#L296 the path is set to "errored.tfstate".  With reference to this issue, what path should the state files be stored in?

**Comment by Yantrio** [comment]
> The function PersistState(), which is invoked when a write operation occurs to the state file, takes an argument of type *tofu.Schemas, but does not use the schema throughout the execution of the function. Why is there a need to pass it through to the function?

It looks like this was an oversight in this PR: https://github.com/opentofu/opentofu/pull/579/files#diff-773fc64cd5e180fca136864b681352fc5ce5af9f136b9dc4ff1065cbe955366bR137-R176

@jonjohnsonjr do you remember why the schemas were being passed around here? 

If we think we can remove it it may be a good idea to do so now :D

> the path is set to "errored.tfstate". With reference to this issue, what path should the state files be stored in?

I think that `errored_test.tfstate` may be a good file name, but others may have better opinions. 

Do you have any ideas about what it should be called whilst you're in this area of code @Kazzhar ?

**Comment by Kazzhar** [comment]
Hi, thanks for the response. 

I think `persisting_test_resources.tfstate` could be another good alternative, the name is self descriptive and clear, but it may be a bit long. 

Another follow up question that I have is related to the implementation for this issue. Something along the lines of this is what I had in mind:

<img width="1213" alt="Screenshot 2024-02-06 at 5 49 48 PM" src="https://github.com/opentofu/opentofu/assets/76555721/f0d151fd-ae72-41ff-80b3-e5d8024ab94d">

I was testing out how this would work - it seems to be working fine locally. Would this work even with a remote backend? I am unsure of how to test it for that.

**Comment by Yantrio** [comment]
The name `persisting_test_resources.tfstate` does not make it clear that it will only be there when things are errored.

As for the implementation it's quite difficult to see how this would work without me debugging, and without me seeing a good diff of the situation.

I was thinking it could be a good idea to extract out the existing logic around writing the errored statefile to disk to a method that can be re-used, and use that to write to the filesystem. Instead of implementing similar logic in 2 places.

**Comment by Kazzhar** [comment]
Understood, `errored_test.tfstate` is what I will be naming the file for now. I have written the logic to a function as well. Will make a PR so that it can be reviewed and tested.
