### ISSUE TITLE
Removing/"forgetting" objects using configuration

### ISSUE THREAD

**Issue by lorengordon** [opentofu/opentofu#299]
**Additional context**
Add any other context or screenshots about the issue here.

**Comment by eranelbaz** [comment]
Hey @lorengordon, thanks for submitting!

To help us maintain a clear separation between OpenTF and Hashicorp's offerings, we would like that people describe issues in other repositories rather than linking those directly.
I've thus scrubbed out any links to said issues.

Would you mind giving us a brief overview or description of this issue please?

**Comment by eranelbaz** [comment]
Hey @lorengordon can you please add relevant information here? as currently this is an empty issue

**Comment by eranelbaz** [comment]
Hey @lorengordon I'm currently closing this issue as it is empty for the last two week
feel free to update the description and reopen it

**Comment by lorengordon** [comment]
Please open it again. I don't have permission. I'll get around to updating the description eventually. It's a pain because you removed the links, and I have to do more work to go find everything and summarize it for you.

**Comment by eranelbaz** [comment]
Hey @lorengordon 
Sorry for the closing! 
reopened it

you can see the link in the description history

**Comment by lorengordon** [comment]
Closing in favor of https://github.com/opentofu/opentofu/issues/1032
