### ISSUE TITLE
Override module resource from outside module

### ISSUE THREAD

**Issue by Z4ck404** [opentofu/opentofu#302]
Was following this issue for a long time. it would be great to have this feature in OpenTF

**Comment by roni-frantchi** [comment]
Hey @Z4ck404  thanks for submitting!  

To help us maintain a clear separation between opentf and hashicorp's offerings, we're asking that people describe issues that are in other repositories rather than linking those directly.  

Would you mind giving us a brief overview or description of this issue please?

**Comment by cube2222** [comment]
I think the interaction of this with module updates could lead to unexpected breakage. We've decided to not do this for now.
