### ISSUE TITLE
Function to check if one ip belong to cidr

### ISSUE THREAD

**Issue by littlejo** [opentofu/opentofu#334]
### OpenTF Version

```shell
command not found: opentf ;)
```

### Use Cases

On AWS, if you have to create an EC2 with a static ip address as input, it's interesting to know directly in which subnet you have to set.

### Attempted Solutions

There is a workaround here:
https://xebia.com/blog/get-all-ip-addresses-of-a-cidr-block-using-terraform/

### Proposal

Create a function cidrexpand
cidrexpand("192.168.0.0/24") => list of ips of the cidr
contains(cidrexpand("192.168.0.0/24"), "192.168.0.3") => true

**Comment by cube2222** [comment]
Hey, thanks for creating the issue!

For what it's worth, if we were to do this, I'm not sure if a cidrexpand function would be the way to go here - that would be terribly inefficient for checking containment, as OpenTF would have to create a list of all the contained ips, which for 0.0.0.0/0 would contain 4 billion elements. Instead, I think a cidrcontains function that directly checks membership would make much more sense.

**Comment by marcinwyszynski** [comment]
If we were to add a generic rego evaluation function, we'd be getting [both of these functions](https://www.openpolicyagent.org/docs/latest/policy-reference/#net) from Rego. Just sayin' ;)

**Comment by Hefeweizen** [comment]
https://www.openpolicyagent.org/docs/latest/policy-language/#what-is-rego -- for others, like me, who aren't immediately familiar with the tool.

From my vantage, a general rego evaluation function would be powerful indeed.  There's at least one [rego golang package](https://pkg.go.dev/github.com/open-policy-agent/opa/rego) that is probably simple to embed.  The requested solution would then be something like `rego_eval(net.cidr_contains(cidr, cidr_or_ip))`.

That said, implementing a `cidrcontains()` function would offer a more developer-friendly experience.  The function would be in the opentf docs directly, rather than in some out-of-band docs, which could be missed when someone is researching this capability.

**Comment by marcinwyszynski** [comment]
Sure I was just daydreaming @Hefeweizen .

Does this [quick draft implementation](https://github.com/opentffoundation/opentf/pull/366/files#diff-cc24d95def0b5fe8cd413c605b95ebe6fa87c6aecd247886367596fcb0aa94c4R78-R109) look reasonable?

Corner cases handled:
- prefix invalid;
- address invalid;
- prefix and address are of different types;

Anything else that could go wrong here @littlejo @Hefeweizen ?

**Comment by marcinwyszynski** [comment]
Or am I being too strict here and it would be fine to mix IPv4 and IPv6 here?

**Comment by marcinwyszynski** [comment]
Ah, I missed the possibility of the "contained" address being a CIDR itself.

**Comment by Hefeweizen** [comment]
I commented on the PR.

And thanks for jumping on this!  That's impressive turn-around.
