### ISSUE TITLE
Proposal: port forwarding via SSH tunnel

### ISSUE THREAD

**Issue by littlejo** [opentofu/opentofu#339]
### OpenTF Version

```shell
?
```

### Use Cases

original request: https://github.com/hashicorp/terraform/issues/8367

Create an ssh tunnel to be on another network to acceed resources.

### Attempted Solutions

Workaround: https://github.com/flaupretre/terraform-ssh-tunnel

### Proposal

Example of implementation

```
port_forward "consul_tunnel" {
    remote_host = "demo.consul.io"
    remote_port = 80

    connection {
        # Now the connection block is the same as in other contexts, as long
        # as the selected connection type supports port forwarding.
        type = "ssh"
        user = "private-user"
        host = "private.jump-host.io"
    }
}

provider "consul" {
    address = port_forward.consul_tunnel.local_address
}
```

**Comment by Yantrio** [comment]
Hi @littlejo! 

Thank you very much for raising this issue.

To help us maintain a clear separation between opentf and hashicorp's offerings, we're asking that people describe issues that are in other repositories rather than linking those directly.

Would you mind giving us a brief overview or description of this issue please?

**Comment by Magnitus-** [comment]
I think its nice. However, there are a couple of alternatives there that mitigate its priority in my opinion.

You can:
- Run opentf remotely on the other side of the tunnel (it does require some integration to automate running opentf on the other side... currently we use terracd + systemd timers or terracd + kubernetes cron jobs for that... will have to migrate terracd to opentf when opentf is more mature)
- Use ansible to run opentf on the other side (honestly, no longer my favorite solution to tackle this problem so not sure about maintaining it, but if it inspires you...): https://github.com/Magnitus-/DockerFiles/tree/master/remote-terraform
- Run a tunnel client on your end, though you might get some certificate errors with tls (we tend to stick 127.0.0.1 in our certificates for projects that use a tunnel, but it may not be a possibility for you if you don't provision your own certificates).
- Plug it directly in the provider if it supports it like so: https://github.com/dmacvicar/terraform-provider-libvirt/blob/main/examples/v0.13/multiple/main.tf#L17

Btw, if implemented, it would be important to support the expected bastion fingerprint in the specs as not checking it is the ssh equivalent of doing an https request without checking the server certificate. It leaves you open to a man in the middle attack.

**Comment by janosdebugs** [comment]
Hey folks, thank you for the detailed write-up. Unfortunately, providers all have their own networking, often through including an SDK. There is no simple way we could route these connections through an SSH tunnel. As such, this is currently impossible to implement and I'll be closing this issue. However, I opened #1138 as a possible alternative solution which would enable the same thing.

**Comment by Blefish** [comment]
There is already a way to do this through data sources:
* https://github.com/AndrewChubatiuk/terraform-provider-ssh
* https://github.com/flaupretre/terraform-ssh-tunnel

Although these solutions work, they all lack support for differentiating between plan and apply. Apply step has to use the already planned data source which contains address for the locally forwarded port.

opentofu in this context would only provide a tunnel and the address for the tunnel, which is forwarded to the provider.
I am currently using the data source alternative to provision consul, nomad, vault, nexus, grafana, elasticsearch and more via original providers. None of the components are directly accessible. The only thing lacking is plan support, where opentofu could potentially step in.

**Comment by janosdebugs** [comment]
@Blefish thank you for the links. I've reviewed the code for both and unfortunately, both plugins only open an SSH/Kubernetes/etc port forward to which you can configure your services to run, but they don't do anything else. This will work fine until you want to access an endpoint that has a TLS certificate with a specific host name. If you were to access, for example, the AWS endpoint, you would want to verify their TLS certificate, which is impossible because the DNS doesn't point to the local endpoint of your forwarded tunnel.

Generally speaking, this kind of port forwarding without changing the hosts file only works if you are willing to forego certificate verification. An attacker could intercept your connection on the bastion host or anywhere en route from your bastion host to the endpoint and capture sensitive credentials.

Given the freedoms provider authors enjoy when writing their code, the only secure solution to achieve the goals of this issue is to actually run the provider on the remote site, which is covered by #1138. If this is something that you would like to see, please make sure to react or comment on that issue as we prioritize based on community feedback.
