### ISSUE TITLE
Open up github discussions on this repo

### ISSUE THREAD

**Issue by kaffarell** [opentofu/opentofu#340]
### Summary

Enable github discussions for this repo.

### Problem Statement

There are a lot of questions around the project/code/governance/... especially in the early moments of this project. We could enable github discussions to have a sort of forum with minimal effort from the admin and great value to the community/maintainers. Issues should be code-related, github discussions are for organizational questions and later also support questions.

### User-facing description

Users can ask and answer questions in the forum that are not directly code-related.

### Technical Description

https://docs.github.com/en/discussions
Github discussions is a growing feature, used successfully in a lot of big projects.

### Rationale and alternatives

Alternative would be to do nothing and let the questions come in as github issues (cluttering the inbox and "issues" page) or stackoverflow questions (which is a different platform where users/maintainers have to find). Another option would be to create a specific forum for opentf (Something like a hosted XenForo instance). The downside would be the administrative effort to setup and maintain.

Note: I would also be happy to begin moderating the discussions.

**Comment by marcindulak** [comment]
A decision whether slack or other platform is suitable for a long term storage of discussions is something to motivate a bit more, as this decision can both hurt or boost the community.

https://kotaku.com/please-stop-closing-forums-and-moving-people-to-discord-1847684851 describes the essence of slack-like services
>  discord [slack ...] It’s a river running in real-time, and while it does have search functions, the way the whole app is structured means you’re simply never going to get the same levels of detailed discussion or archived information as we can get from forums

There are more factors to consider in addition to the effort of setting up an instance and moderating it, and include planning for future migration away from it, or fulfilling legal requirements
https://slack.com/help/articles/201658943-Export-your-workspace-data
https://github.com/orgs/community/discussions/3315

**Comment by kaffarell** [comment]
Another important point is that you can't use search engines to find help, you need to create a discord/slack account, join the server and then search. All the other options such as Github Discussions or other Forums are indexed by search engines. Furthermore, Discord and Slack need a way higher administrative effort to keep them going.

**Comment by keen99** [comment]
having both semi-synchronous (lossy) and fully async discussion is pretty time honored - an irc channel and a mailing list (or 15), or any equivalent, will happen even if they're not official.   so giving an official live discussion source, on top of a forum/mailing list discussion group, at least lets you direct the community growth.

many projects used to log and archive chat logs to make them searchable - that's less common these days for lots of good reasons - but that's certainly a possibility even with slack (there are some decent tools for doing this, even retroactively, even without a paid-tier slack)

**Comment by keen99** [comment]
> Hey, right now the best place to ask such questions is the OpenTF Community Slack.

fwiw, this link is dead/expired - as well as the same link in https://opentf.org/fork

we should probably arrive at a better more persistent way of getting access than an expiring invite link :-)

**Comment by cube2222** [comment]
I've updated the invite link in the readme to one that doesn't expire, sorry for the inconvenience!

**Comment by kaffarell** [comment]
> having both semi-synchronous (lossy) and fully async discussion is pretty time honored - an irc channel and a mailing list (or 15), or any equivalent, will happen even if they're not official. so giving an official live discussion source, on top of a forum/mailing list discussion group, at least lets you direct the community growth.
> 
> many projects used to log and archive chat logs to make them searchable - that's less common these days for lots of good reasons - but that's certainly a possibility even with slack (there are some decent tools for doing this, even retroactively, even without a paid-tier slack)
Hmm, I don't like this. You can't continue old discussions and everything is linear. Of course you can have different channels, but its not as separated as a github discussion or issue.

> how well search-indexed are github discussions? I havent run into any personally yet
Same as Github Issues, so very good. Plenty of times I find a discussion (or issue) as the first few search results on google.

**Comment by peterwwillis** [comment]
I think Slack is not the best place for such discussions.

 - Chat apps are better designed for continuously rolling discussions. It is hard to maintain a list of specific subjects and their threads, page through them, refer to points, etc, in a chat app.
 - Forums and discussion software are designed for having a list of categories, and within those a list of topics, and within those a discussion thread which is paginated. Navigating older discussions is easier, and finding very old threads is easier (plus you don't have to worry about historic discussions being lost due to expired chats/logs).
 - The project lives on GitHub. Moving discussions to Slack makes it harder to find discussions and refer to conversations that span both GitHub and Slack.
 - With everything on GitHub, it's easier to manage access control, which accounts you're using for interaction, which sites or apps a corporate user (or person behind a great firewall?) might be allowed to use, etc.
 - GitHub vertically integrates its features, so in a GitHub discussion it may be easier to refer to bugs, or vice versa.
 - Slack is not well known for its ability to export records for free, or switch to other providers, and its features may change over time. GitHub is much easier to navigate and use and has a better track record for being compatible with other similar services.
 - As we already see above, "invites" to Slack can expire, so managing access to these discussions is already gated by Slack itself. GitHub Discussions have no gate; go view them at any time anonymously in the browser.

**Comment by keen99** [comment]
I just think its important to recognize that if the official community doesn't embrace a slack, the unofficial community will (on top of the various channels in existing infra/ops/dev/leadership slacks now).    it's totally fine to make that choice and or chose to not participate.  :)

**Comment by eranelbaz** [comment]
Hey all
Can we close this issue as the [discussions](https://github.com/orgs/opentofu/discussions) are open?

**Comment by kaffarell** [comment]
Yes, thanks for the help @eranelbaz!
