### ISSUE TITLE
Optional Delete on Resources.

### ISSUE THREAD

**Issue by lanrongwen** [opentofu/opentofu#543]
### OpenTofu Version

```shell
N/A
```

### Use Cases

When running a Delete operation, TF will start at the end of the graph and work it's way back up until all resources have been removed.  It makes sense based on the base architecture of the tool.  However, there are cases where this just adds time and complexity because the sub-resource would be removed by virtue of the parent-resource being removed.  For Example:  In azure, if you create a vm with extensions, TF attempts to remove the extensions before the VM.   To complicate mattes, if the vm is turned off, the extension can't be removed and the operation will fail.   But if it skipped the extension and just deleted the VM the extension would also be removed and be done much faster.

### Attempted Solutions

The work around is to use tf state file manipulation commands to remove the object from state, but that's not always feasible in an automated environment.

### Proposal

Can an annotation (maybe in the lifecycle block) be added to show that if the parent resource is to be removed, TF can skip the removal of this resource, thus speeding up the delete cycle and minimizing potential issues.  Something like:

lifecycle {
  destroyed_by_parent = true
}

This would also let TF know that if the resources is simply being updated it can still delete the individual component if the parent still exists, or skip it if the parent is also slated for removal.

**Comment by cube2222** [comment]
That's an interesting use-case, thanks for creating the issue!

I'm not sure if it's obvious **who the parent is**. A resource can have many attributes of the form xyz_id, and any of them could be its parent (or not).

I wonder if this could just be a "ignore-on-destroy" annotation (or lifecycle attribute), that would basically ignore the destroy step of a given resource?

**Comment by Hefeweizen** [comment]
In engineering this, we should investigate the feasibility of the specific provider being able to provide these hints as well.  It has to be implemented as initially described (as we can't wait on all providers, and even then, there'd be edge cases).  But at some future point, it would be wonderful if the providers (which are customized specifically for that platform) can use its understanding to provide this direction as well.

**Comment by lanrongwen** [comment]
I also debated making it less true false and more of the following:

lifecycle {
destroyed_by_parent = [
   id_1,
  id_2
]
}

**Comment by lanrongwen** [comment]
I'll also add - just doing a lifecycle ignore on delete wouldn't work, because sometimes you do want to remove the object even if the parent is staying there...

**Comment by Hefeweizen** [comment]
> This issue strongly aligns with a long-standing feature request that should be migrated to the OpenTF roadmap: https://github.com/hashicorp/terraform/issues/3874

Summarizing this issue, I would describe it as:  we want to delete resources.  Sometimes, we can ignore downstream components because they'll naturally go away.  Sometimes we can't even complete, because the parent resource is in a certain state.

The linked issue I would summarize as: prevent_destroy needs two forms -- one that warns when keeping components; and, one that doesn't.

I don't see how they align; if anything they're inverse operations.  I don't see that implementing one, would automatically give us the other.  For simplicity of implementation, I'd keep the issues separate.

Would you share how you see they align?  What would the code be doing similarly in each use case?

**Comment by Hefeweizen** [comment]
@jjno91 Thanks for being willing to talk this through.  I'm still getting up to speed on this codebase, and the opportunity to think through the code is much appreciated.

> the ability to orphan a resource based on .tf configuration rather than only through a CLI state operation

I can sort of see the linkage through that lens, but I still don't think it ties these two issues together strongly.

I confess, when I think about `destroyed_by_parent`, I assume some linkage to a parent, and that if we're attempting to destroy annotated resource, we check if parent is being destroyed, and then conditionally drop the annotated resource from the list of to_be_destroyed items.

@cube2222 rightly points out, the inference of parent is tricky, and so no automatic linkage is made.  Instead, `ignore_on_destroy` is offered.  Then, we have a simple drop from to_be destroyed items. [^1]

The other issue's `prevent_destroy` and it's request for control the warnings -- the item still has to be destroyed, we do not change whether the resource is in the to_be_destoryed items, we're just flagging whether errors are created or honored.

Let's look at `plan` as an example of how errors are processed:  https://github.com/opentofu/opentofu/blob/072d1dce56dd13406701cc3f2c18a7f71d56ee4f/internal/command/plan.go#L69 (and similarly on L77, L85, L99). Here, we see it proceeds with the operations as needed, and `diag` entries are sent back to the caller.  For #3874 this is the behaviour we want:  delete the item, and then conditionally alert the user.  A possible implementation of `prevent_destroy` then, wouldn't have to touch the DAG or resources at all, simple add an if to see whether the Errors have to be kept or removed.

Separately, we could go into the provider and have it parse the `prevent_destroy` directive.  If set, it could simply fail to create the error.  This has the advantage of keeping the behaviour close to the resource (where one probably expects to see such logic handled).  However, then we've got to implement the feature across multiple providers, instead of once, for all providers.[^2]

I still see the implementations as distinct enough to be better treated separately.

---
[^1]: stated this way, I'm not sure a simple `ignore_on_destroy` would be sufficient to the original request.  Certainly, in the case of the Azure example, when the instance is going to be deleted anyways, it is sufficient.  But what if we want to leave the instance, and destroy the extension?  Now the entire procedure fails in the user's intent.

[^2]: or, maybe I'm wrong that.  TODO: look at how `depends_on` is implemented.  Does each provider really implement it?

**Comment by huix11** [comment]
👍👍

**Comment by Hefeweizen** [comment]
> A note on your last statement about depends_on - depends_on is a meta-argument my understanding is that providers don't have to do any work to implement it. Since it is only operating on TF primitives its functionality is always available regardless of resource. Just like the lifecycle block:

https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on

Great point.  Thanks.

**Comment by cube2222** [comment]
We've discussed this and believe that the "issue-avoiding" part of this proposal can be accomplished by using the `removed` block coming in 1.7. As a performance improvement, it seems like quite a bit of complexity to add to the language. Please reopen if you'd like to discuss further.
