### ISSUE TITLE
Add code formatting guidelines, and the "Code Consistency Check" step to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kislerdm** [opentofu/opentofu#584]
### OpenTofu Version

```shell
-
```

## Problem

Different contributors have different IDE settings, which may lead to the source code re-formatting violating the OpenTofu guidelines. **Note** that there are no explicit linting/formatting guidelines beyond running `gofmt` and `goimports` yet.

_The consequence_: avoidable increase of the "time-to-merge" causing delivery delays.

For example, my IDE has re-formatted a couple of files causing CI check to [fail](https://github.com/opentofu/opentofu/pull/576#issuecomment-1735127229).

### Attempted Solutions

Run the [CI command](https://github.com/opentofu/opentofu/blob/daf275ffbe213d06837be8e50c8081e54b266d2c/.github/workflows/checks.yml#L185C11-L185C78) in local env:

```bash
make fmtcheck importscheck generate staticcheck exhaustive protobuf
```

### Proposal

1. Describe the formatting guidelines explicitly as part of the contribution instructions [CONTRIBUTING.md](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md)
2. Include corresponding step to the [instructions](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#contributing-a-code-change)

In addition, we may consider use of pre-commit, or pre-push git hooks as a contribution prerequisite.

## Open questions

- Shall we opt in for using [golang-lint](https://golangci-lint.run/) to facilitate maintenance of the codebase formatting?

**Comment by serdardalgic** [comment]
Thanks for this suggestion @kislerdm, I agree adding a pre-commit hook would save time and avoid confusion. 

Adding a `.pre-commit-config.yaml` like this to the root would work for now if I'm not mistaken. 

```shell
repos:
  - repo: local
    hooks:
      - id: code-consistency-checks
        name: code-consistency-checks
        description: This pre-commit hook runs the consistency checks
        entry: make fmtcheck importscheck generate staticcheck exhaustive protobuf
        language: system
        pass_filenames: false
```
 Some of those checks, such as `fmtcheck`, `importscheck`, `staticcheck` etc. can be implemented using golangci-lint ([here](https://golangci-lint.run/usage/quick-start) is a list of by default enabled and disabled checks). But I wonder if it would be worth the effort for now to rewrite them to use golangci-lint, before the 1.6.0.  I would vote for postponing these efforts for now, unless there is anyone who deliberately wants to work on that. 

Pre-commit also comes with several useful hooks, as the output of `pre-commit sample-config` suggests:
```
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
 ```

My 2 cents on the topic, it would make sense to implement the pre-commit hook with only the code consistency checks for now because the trailing whitespace fix will change many files (~300). 

And we should encourage contributors to install pre-commit hook in their repositories. 

Another thing,
```
% pre-commit run  --all-files
code-consistency-checks..................................................Passed
- hook id: code-consistency-checks
- duration: 22.51s
```
It would make sense to run some of those consistency checks only on `pre-push` (by default, pre-commit runs on both pre-commit and pre-push stages, details [here](https://pre-commit.com/#top_level-default_stages))

**Comment by Hefeweizen** [comment]
+1 on project standards and encouraging pre-commit usage.

However, we shouldn't trust that everyone runs the tool; we should have our own check.  In #624, I add a github-action using commonly available tooling to check imports.  I start in a limited way as #513 tries to clean up imports across the project, but it was wisely pointed out by @eranelbaz that such clean-up is premature until we take steps to make sure the project stays clean.

**Comment by davidjeddy** [comment]
+1 to formatting and linting consistence. It greatly lowers the cognitive workload for: new contributors, maintainability, and code rot. Who wants to work on code that looks like a mess? 

+1 to pre-commit AND pipeline execution of the tooling.
