### ISSUE TITLE
Feature request: Community enhancement request list with voting

### ISSUE THREAD

**Issue by peterwwillis** [opentofu/opentofu#597]
### OpenTofu Version

```shell
N/A
```

### Use Cases

One of the problems of Terraform was the community wanting features or changes which would be rejected by the project owner. I request that this new community fork have a single list of feature requests that the community can vote on, and be adopted even if the "project owner" has a "philosophical" difference with it. In other words, the interests of the community should trump those of whatever entity controls the project.

This list would be useful for going back to review previous requested features, and for prospective contributors to find proposals which have been accepted but not worked on yet.

### Attempted Solutions

I personally have a laundry list of changes I would like to see in OpenTofu :) But of course I am just one person; it's likely some of those changes will be rejected by the community, and some approved of, and some adopted if the idea is modified. I think a *lot* of people would contribute more if they thought they could get substantive changes adopted.

**Comment by alrs** [comment]
Hi, @peterwwillis.

I was a contributor to a number of Hashicorp projects (including Terraform), and I've been contributing to opentofu since the repo was opened to the public earlier this month.

I doubt you'll find any enthusiasm for driving project features by means of a vote from potential users. Even a project as democratic as Debian takes votes from its developers, not its users.

I will say that I've felt far less "backpressure' getting pull requests approved in the new project than in the old. Instead of waiting weeks or months for a bugfix to land under the old regime, most of my efforts here have landed in a few days.

**Comment by marcinwyszynski** [comment]
While we intend to run the project in an inclusive way, prioritizing purely according to the number of votes misses a lot of context. First, it's easy to influence the vote count. Second, it misses how badly folks need a given feature. Third, it can potentially prioritize tiny improvements which everyone immediately understands (without having to read an RFC) over potentially groundbreaking improvements that take time to fully appreciate.

I would rather look at a combination of the following factors:
- total utility provided (prioritize things used by most);
- novel use cases enabled by a feature (driving new adoption through innovation);
- number of thoughtful comments on the RFC by unique users, which are way more valuable than simple votes IMO;

**Comment by cam72cam** [comment]
We've created https://github.com/opentofu/opentofu/issues/1496 which is automatically updated daily.  This has influenced our triage process and helped the core team have a better view in what the community is directly invested in.
