### ISSUE TITLE
Dedupe modules in .tofu/modules directory

### ISSUE THREAD

**Issue by aclarknexient** [opentofu/opentofu#642]
### OpenTofu Version

```shell
n/a or latest
```

### Use Cases

Tofu will copy a distinct instance of every module referenced in your code. There's no deduplication, lookup table, or symbolic links used.

This results in a slow, inefficient `tofu init` process.

### Attempted Solutions

n/a

### Proposal

I propose that each module exists only once in a table or other store, and each module is referenced to as a UUID or via a symbolic link within tofu and inside the `.tofu/modules` directory.

Instead of one copy per instance per module:
```
policy
policy.validate_tags
policy.workspace
role
role.validate_tags
role.workspace
```

One instance per module:
```
policy
role
validate_tags
workspace

policy.validate_tags -> validate_tags
policy.workspace -> workspace
role.validate_tags -> validate_tags
role.workspace -> workspace
```

**Comment by Hefeweizen** [comment]
+1, I like this idea.

Symlinks aren't an issue on unix-like OSes.  I believe Win 10/11 have support for symlinks, but I don't know their exact semantics.   Are there any Windows platforms that don't support the feature?

I'm curious if anyone can speak to Golang's ability to use this feature on Windows platforms?  Should we find issues, I'd say those issues are defects of the golang implementation, and bugs should be raised upstream.  However, I'd still like to know about any potential issues or caveats earlier rather than later.

Or, maybe I'm worried about nothing.   : )

**Comment by aclarknexient** [comment]
Looking at this a little more, I missed that there's a `modules.json` file in the `.tofu/modules/` directory:

```js
{
  "Modules": [
    {
      "Key": "webapp.redacted.codepipeline_html.codepipeline_iam_role",
      "Source": "app.terraform.io/redacted/iam/aws//modules/iam_role",
      "Version": "0.0.6",
      "Dir": ".tofu/modules/webapp.redacted.codepipeline_html.codepipeline_iam_role/modules/iam_role"
    },
  ]
}
```

So it might be as "easy" as updating that "Dir" attribute to point at a single instance of each module. My current projects have over 1,000 module instances, with some frequently-used modules referenced 250+ times.

Unfortunately this might break compatibility with the other tf tool. There would need to be a test of moving a project between the 2 tools, if that's something this project wishes to support.

@Hefeweizen I am not familiar with how tf is used in Windows. If it's within WSL, then symlinks won't be an issue. Thank you for the +1, it's appreciated!

**Comment by Hefeweizen** [comment]
If I've read the code correctly, the `modules.json` file is just a snapshot of the state of `.tofu/modules` directory ([code comment](https://github.com/opentofu/opentofu/blob/913578a9f45acebbb2c35279925e475ff839c14b/internal/modsdir/manifest.go#L65)).

The work of building the .tofu/modules directory is done in [modules_install.go](https://github.com/opentofu/opentofu/blob/main/internal/initwd/module_install.go).  Module installation is done from configs.configLoader.  In my reading of `internal/configs/configload` the work to duplicate the module structure is rigorously done.  Neither in the docs, or in the code, do I find where this assumption that configuration will map to specific place on disk.  To be clear, I'm not saying I've read them all; I'm just saying I personally can't point to doc or code that spells out that this should always be the case.

There's a glimmer of hope for an easy adjustment in `LoadConfigwithSnapshot()` [as](https://github.com/opentofu/opentofu/blob/913578a9f45acebbb2c35279925e475ff839c14b/internal/configs/configload/loader_snapshot.go#L21):
> LoadConfigWithSnapshot is a variant of LoadConfig that also simultaneously creates an in-memory snapshot of the configuration files used

Maybe we can just build all the modules in memory?  But this later appears to be a mirage [as](https://github.com/opentofu/opentofu/blob/913578a9f45acebbb2c35279925e475ff839c14b/internal/configs/configload/loader_snapshot.go#L131):
> exhibit the same lookup behaviors as l.moduleWalkerLoad but will additionally write source files from the referenced modules into the given snapshot.

So, it creates an in-memory snapshot, but it still writes everything to disk.

From my current understanding, to effect this type of deduplication, we have a few options:
- write to memory -- grab a chunk of memory, treat is as a filesystem, and have full module load happen there, rather than in the root module location on disk
- virtual fs -- add a virtual fs layer to manage the redirection between common modules.  While this may sound ambitious, the LoadConfigWithSnapshot() implementation already uses go's [afero](https://github.com/spf13/afero) lib for its snapshots.
- rewrite all of config -- not practical, just mentioning for completeness

If a more experienced dev can comment on the apparent assumption that the entirety of config is present, fully-written in the root module directory, I'd love to learn more.

**Comment by cam72cam** [comment]
This is now replaced by this RFC which contains more information on why this is problematic: https://github.com/opentofu/opentofu/issues/1086
