### ISSUE TITLE
enrich functional capabilities with ifnull, ifnullorempty, and other frequently requested ones

### ISSUE THREAD

**Issue by joaocc** [opentofu/opentofu#681]
### OpenTofu Version

```shell
1.6.x
```

### Use Cases

The terraform language is quite rich and very powerful.
However, for those accustomed to other similar languages, some useful functions could be added to make development life easier, and without breaking any kind of existing code. It does also allow the use of some development idioms that are currently out of bounds.

* `ifnull(expression, expression-to-return-if-null)` -> expression
* `ifempty(expression, expression-to-return-if-empty)` -> expression
* `ifnullorempty(expression, expression-to-return-if-null-or-empty)` -> expression
* `isempty(expression)` -> `true` if is "", [], {}
* `isnullorempty(expression)` -> `true` if is null, "", [], {}

### Attempted Solutions

There are workarounds for them, but they are quite verbose, force expressions to be repeated (eg, when using ?: to do a ifnull) and/or are harder to manage

### Proposal

Add the following functions to the library:
* `ifnull(expression, expression-to-return-if-null)` -> expression
* `ifempty(expression, expression-to-return-if-empty)` -> expression
* `ifnullorempty(expression, expression-to-return-if-null-or-empty)` -> expression
* `isempty(expression)` -> `true` if is "", [], {}
* `isnullorempty(expression)` -> `true` if is null, "", [], {}

**Comment by maunzCache** [comment]
Note: Took me longer to write this comment as expected. I'll try to update it tomorrow. Sorry if it is not cohesive.

I've been thinking about it a bit and while i find it tempting to implement, i'd like to get some examples where one of those functions would have a major benefit despite what is currently possible.
Additionally, i don't think all five requests functions would be required just for the sake of completeness.

**ifnull(expression, expression-to-return-if-null)**
Can be written as `<expression> == null ? <expression-to-return-if-null> : null`
While it can be confusing to return `null` in the false-case, it is aligned with [the type definition](https://developer.hashicorp.com/terraform/language/expressions/types#null)

> a value that represents absence or omission

I think writing `isnull(<expression>) ? <expression-to-return-if-null> : null` might be easier to read.

**ifempty(expression, expression-to-return-if-empty)**
Can be written as `length(<expression>) == 0 ? <expression-to-return-if-empty> : null` currently. I personally would prefer to have `isempty(<expression>)` as it is much easier to read.

**ifnullorempty(expression, expression-to-return-if-null-or-empty)**
I cannot think of a situation where the value would be dynamical that such a check is required to be honest. If so, you would surely require to wrap it with `try` in addition. That gives me a headache.
It gets very verbose if you want it in one line: `try(<expression> == null || length(<expression>) == 0) ? <expression-to-return-if-null-or-empty> : null`. If possible, I'd declare some locals to make it easier to read. However, there is not always a chance to split expressions into separate locals:

```hcl
locals {
    expression_to_check = { for entry in magic_values : entry.id => length(entry.value) == 0 ? null : entry} // This inline function can't be separated
}
```

So i believe in general having `isempty()` and `isnull()` would be a nice thing. The conditional variants seem a bit too much for me without a reasonable example. If there is a need for simple conditionals such as `if` without an `else` clause, one might write `<expression> ? true` instead of `<expression> ? true : null`. This is something OpenTofu could support.

Introducing the news functions would make OpenTofu incompatible with Terraform but not vice-versa. No problems here.

**Comment by janosdebugs** [comment]
Hey folks, thank you for this proposal, we have discussed this issue in the core team. HashiCorp has announced that providers would receive the ability to define functions. As we this functionality is useful and we aim to be compatible with Terraform for the time being, we will implement this functionality.

As such, it will be possible to implement this functionality in a provider and we are closing this issue as a result. Please feel free to reopen the issue if you feel that this solution does not adequately address your use case.
