### ISSUE TITLE
Provide a way to disable provider dependency lock file

### ISSUE THREAD

**Issue by grimm26** [opentofu/opentofu#685]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha2
on linux_amd64
```

### Use Cases

See my comment on https://github.com/hashicorp/terraform/issues/31856#issuecomment-1259902539 and its long history.

> We also don't use the .terraform.lock.hcl and find this warning more spam from terraform. We lock down providers using the required_providers block and that works fine for us. Trying to control and manage yet another place to lock down provider versions that also keeps nagging me about including multiple platforms is just too much.
> Plus, I know that I only care about one platform because all of our terraform work happens on linux_amd64 and for the life of me I don't see a way to tell terraform that I am satisfied with the included platforms in .terraform.lock.hcl.

### Attempted Solutions

One solution is to never check in a `.terraform.lock.hcl` file so that it is generated each time with `init`, but this breaks provider caching. This lack of caching ends up filling the disk volume on my Atlantis server.

The other solution is to just break down and start including the lock file and try to educate my users about another hoop to jump through for almost 0 benefit.

### Proposal

Provide a setting/flag to disable the provider lockfile for those that do not want/need it.

### References

https://github.com/hashicorp/terraform/issues/31856
https://github.com/hashicorp/terraform/issues/29760
https://github.com/hashicorp/terraform/issues/31533

**Comment by janosdebugs** [comment]
Hey @grimm26, hey everyone, thank you for this issue. We have discussed this issue in the core team and would like to ask for community feedback.

1. If this issue would solve a problem for you and you'd like to implement this, please add a reaction to this issue so we can prioritize development accordingly.
2. this feature seems relatively dangerous and we know of no package manager that does this. If you know of any, please link the documentation for that package manager.

**Comment by grimm26** [comment]
> Hey @grimm26, hey everyone, thank you for this issue. We have discussed this issue in the core team and would like to ask for community feedback.
> 
>     1. If this issue would solve a problem for you and you'd like to implement this, please add a reaction to this issue so we can prioritize development accordingly.
> 
>     2. this feature seems relatively dangerous and we know of no package manager that does this. If you know of any, please link the documentation for that package manager.

" this feature seems relatively dangerous": what feature? The feature I am asking to repeal? Or the previous lack of that feature?

**Comment by Yantrio** [comment]
Hi! Core team member here.

Our concern when we discussed this was around the idea that lockfiles are a largely important part of package version management.

We understand that they could get in the way in the situation where you want to download fresh, latest versions over and over. However this lack of change control makes end users vulnerable to supply chain attacks.

By allowing users to disable lockfiles, we would be opening up some users to some issues. 

I am however interested in trying to find a solution here to maybe reduce down some of the pain points, rather than throwing lockfiles out the window. For example we could reduce some of the "spam" in some way, or improve the outputs for multiple platforms you may be hitting.

**Comment by skyzyx** [comment]
I was going to say "supply chain attacks", but @Yantrio got there first. :)

> The other solution is to just break down and start including the lock file and try to educate my users about another hoop to jump through for almost 0 benefit.

IMO, this is a pretty fundamental cybersecurity concept. It helps ensure that what you got last time is the same as you got this time. It helps make sure that nobody took over the upstream repo and messed with it. It also helps ensure that the configuration you ship to dev is the same you ship to prod (e.g., a 12-factor app).

The problem I usually have is the inverse — too many platforms to support, and not enough people updating the lock file beyond their own personal os/arch.

**Comment by digitalfiz** [comment]
Understanding that this is a pretty standard security protocol that terraform/tofu only recently adopted (I assume because pre-v1 things changed way to much) if you still wish to disable this functionality you can just add a command to your `Makefile` or `Taskfile` or whatever you're using to apply your terraform code that just simply deletes the lock file before you try to apply. If you add it to your `.gitignore` for the repo your terraform is in and you use ci/cd to deploy/apply your terraform it shouldn't even be a problem as the file will be recreated every time you "deploy" through your ci/cd.

**Comment by grimm26** [comment]
> Understanding that this is a pretty standard security protocol that terraform/tofu only recently adopted (I assume because pre-v1 things changed way to much) if you still wish to disable this functionality you can just add a command to your `Makefile` or `Taskfile` or whatever you're using to apply your terraform code that just simply deletes the lock file before you try to apply. If you add it to your `.gitignore` for the repo your terraform is in and you use ci/cd to deploy/apply your terraform it shouldn't even be a problem as the file will be recreated every time you "deploy" through your ci/cd.

That's not a viable solution as that breaks provider caching.

**Comment by Yantrio** [comment]
Overall, We have discussed this as a core team and we feel that this could be too much of an issue to allow this feature to exist.

For an interesting read on a related note, please see this blogpost: https://blog.plerion.com/hacking-terraform-state-privilege-escalation/

**Comment by pauldraper** [comment]
I found that blogpost entirely uninformative on why I need to compile my provider, then generate a lockfile for the thing that I just compiled.
