### ISSUE TITLE
executing 'tofu init' on an existing configuration 

### ISSUE THREAD

**Issue by binnsr** [opentofu/opentofu#763]
### OpenTofu Version

```shell
$ tofu version
OpenTofu v1.6.0-alpha3
on linux_amd64
```

### OpenTofu Configuration Files

we have quite a lot of code ( ~7k lines of active terraform code across ~200 files )
```hcl
...tofu config...
```

### Debug Output

tofu  init -backend-config="conn_str=${TERRAFORM_STATE_BACKEND}" -upgrade && tofu select workspace <name> && tofu plan
https://gist.github.com/binnsr/a6789f676849e191858288d1d8b1b205

second tofu  init -backend-config="conn_str=${TERRAFORM_STATE_BACKEND}" -upgrade && tofu plan
https://gist.github.com/binnsr/434bd52428052c5ecadfd844984a174a

### Expected Behavior

No changes. Your infrastructure matches the configuration.

OpenTofu has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

### Actual Behavior

╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: 3 problems:
│ 
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/cloudflare/cloudflare: failed to instantiate provider "registry.terraform.io/cloudflare/cloudflare" to obtain
│ schema: unavailable provider "registry.terraform.io/cloudflare/cloudflare".
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/local: failed to instantiate provider "registry.terraform.io/hashicorp/local" to obtain schema:
│ unavailable provider "registry.terraform.io/hashicorp/local".
│ - Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/random: failed to instantiate provider "registry.terraform.io/hashicorp/random" to obtain schema:
│ unavailable provider "registry.terraform.io/hashicorp/random"..

### Steps to Reproduce

1. `rm -rf .terraform .terraform.lock.hcl`
2. `tofu  init -backend-config="conn_str=${TERRAFORM_STATE_BACKEND}" -upgrade`
3. `tofu workspace select $(cat .workspace_name)`
4. `tofu plan`

### Additional Context

Running `tofu init` and `tofu plan` a second time results in a valid plan.

Not having the .terraform and .terraform.lock.hcl files is important as our build process runs in containers that do not have those until a `tofu init` is run as part of the build.

**Comment by cube2222** [comment]
Thanks a lot for submitting the issue @binnsr, we'll look into it!

**Comment by cube2222** [comment]
Alright, I have successfully reproduced this. Here's a minimal reproduction:

Create a single file called main.tf
```
terraform {
  required_providers {
    random = {}
  }
}

resource "random_string" "this" {
  length      = 10
}

output "random_string" {
  value = random_string.this.result
}
```

and then run (with Terraform 1.5.x and Tofu alpha 3)
```
terraform init
terraform workspace select -or-create test
terraform apply
rm -rf .terraform .terraform.lock.hcl
tofu init -upgrade
tofu workspace select test
tofu plan
```

which will result in
```
random_string.this: Refreshing state... [id=@i&l[cf>Uv]
╷
│ Error: Failed to load plugin schemas
│ 
│ Error while loading schemas for plugin components: Failed to obtain provider schema: Could not load the schema for provider registry.terraform.io/hashicorp/random:
│ failed to instantiate provider "registry.terraform.io/hashicorp/random" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/random"..
╵
```

**Comment by Yantrio** [comment]
Hi @binnsr,

Thank you for reporting this issue,

I've analyzed the underlying problem, which appears to stem from a registry mismatch between `tofu` and `terraform`. Essentially, `tofu` is unaware of the distinction between the two registries and merely detects a discrepancy.

When executing `tofu init`, the command attempts to locate the existing state file, pulling provider information both from that state file and from your `.tf` files. Since the `.terraform/environment` file is missing in this case, `tofu init` is unable to locate the state file and solely resorts to the `.tf` files to resolve providers.

The root cause of this issue appears to be the incongruity between the providers that `tofu` resolves and those that `terraform` uses. If you were solely using `terraform`, this inconsistency would not be an issue, as both the state file and `.tf` files would reference the same providers.

### Suggested Fix

To remedy this, I suggest executing `tofu workspace select` prior to running `tofu init`. By adjusting the sequence of these commands, `tofu` will be equipped to correctly locate the state file and harmonize the providers between the state file and `.tf` files.

Here are the revised steps:
1. `tofu workspace select $(cat .workspace_name)`
2. `tofu init -backend-config="conn_str=${TERRAFORM_STATE_BACKEND}" -upgrade`
3. `tofu plan`

By reordering these steps, I believe your infrastructure planning will proceed without errors.

I hope this clears up the issue. If you have any further questions or concerns, please don't hesitate to ask.

**Comment by binnsr** [comment]
@Yantrio - thanks for the suggestion, however, when selecting a workspace prior to running `tofu init` with a remote backend (we use a Postgres db), the `workspace select` fails.
```
$ rm -rf .terraform .terraform.lock.hcl 
$ tofu workspace select $(cat .workspace_name)
╷
│ Error: Backend initialization required, please run "tofu init"
│ 
│ Reason: Initial configuration of the requested backend "pg"
│ 
│ The "backend" is the interface that OpenTofu uses to store state,
│ perform operations, etc. If this message is showing up, it means that the
│ OpenTofu configuration you're using is using a custom configuration for
│ the OpenTofu backend.
│ 
│ Changes to backend configurations require reinitialization. This allows
│ OpenTofu to set up the new configuration, copy existing state, etc. Please run
│ "tofu init" with either the "-reconfigure" or "-migrate-state" flags to
│ use the current configuration.
│ 
│ If the change reason above is incorrect, please verify your configuration
│ hasn't changed and try again. At this point, no changes to your existing
│ configuration or state have been made.
╵
```
Probably because `tofu init -backend-config="conn_str=${TERRAFORM_STATE_BACKEND}"` is what pulls the workspace list into the working directory, I believe.

**Comment by Yantrio** [comment]
@binnsr in this case, do you think it would be possible to do the following:

- `tofu init`
- `tofu workspace select`
and then
- `tofu init` again?

I think that this process isn't just going to hit issues with moving from terraform to tofu, but could also be an issue if you move between incompatible provider versions, or to a private registry.

**Comment by binnsr** [comment]
@Yantrio - running the commands in that order does bypass the issue and updating our automation to the same should get us back up and running.

**Comment by cube2222** [comment]
The related PR #773 should make this workaround no longer needed, once we make the next OpenTofu release.
