### ISSUE TITLE
Extending terraform with custom functions

### ISSUE THREAD

**Issue by nitrocode** [opentofu/opentofu#793]
### OpenTofu Version

```shell
latest
```

### Use Cases

Instead of creating a new provider, I'd like to define a custom function in code and use it

### Attempted Solutions

Custom provider
Custom module

### Proposal

```hcl
locals {
  func myfunc(var1: string, var2: list(string)) => map(string) {
     var3 = ...expression involving var1, var2, and any local.*...
     var4 = ...expression involving previous vars...
     return var3
  }
}
```

See below credits

### References

https://github.com/hashicorp/terraform/issues/27696

Credit to previous author (now ghost) and @schollii

**Comment by kislerdm** [comment]
Hey! Thank you for your proposal. Maybe you could share more illustrations of use cases you have in mind?

AFAIK such drastic change would be beyond current objectives of OpenTofu. Moreover, IMO the proposed functionality is a drastic change which would bring the complexity and risk of side effects outweighing any possible benefits. I feel that the focus on stability, security and simplicity of tofu would be more beneficial for community compared to introduction of complex abstractions requiring deviations from HCL.

See the [comment](https://github.com/opentofu/opentofu/issues/761#issuecomment-1772723464) to somewhat similar proposal for more context.

**Comment by reegnz** [comment]
For anyone struggling with this, there is a hacky workaround that works today, using a module.
Example:

'function' definition:
```hcl
variable "var1" {
  type = string
}
variable "var2" {
  type = list(string)
}
locals {
     var3 = ...expression involving var1, var2, and any local.*...
     var4 = ...expression involving previous vars...
}
output "result" {
  value = local.var4
}
```

'function' usage:
```hcl
module "myfunc" {
  source = "./modules/myfunc"
  var1 = "test"
  var2 = [ "alpha", "beta", "gamma", "delta"]
}

locals {
   result = module.myfunc.result
}
```

For small trivial things it's gonna be very verbose in comparison to the proposal, but for very complicated stuff it might still lead to reducing duplication.

This pattern is very closely related to [data-only modules](https://developer.hashicorp.com/terraform/language/modules/develop/composition#data-only-modules)

**Comment by janosdebugs** [comment]
Hey folks, thank you very much for all your input and apologies for the delayed reply. We are currently not he owner of the HCL language and this would be a significant change to the codebase we'd have to maintain in a fork. There are also several ways to solve this issue, ranging from Pulumi to modules or the upcoming functions from providers feature. Since it is not feasible for us to implement this and several working solutions exists, we are closing this issue.

**Comment by reegnz** [comment]
This feature is coming to terraform 1.8 so can this be opened up again?
See comment here https://github.com/hashicorp/terraform/issues/25584#issuecomment-1967957406

**Comment by reegnz** [comment]
cc @janosdebugs

**Comment by mariusmanea-selfridges** [comment]
Hello,

Terraform 1.8 is implementing this feature, can this be reconsidered for opentofu as well?
https://github.com/hashicorp/terraform/pull/34394

And HCL has support for user functions already:
https://github.com/hashicorp/hcl/tree/main/ext/userfunc

best regards,

**Comment by schollii** [comment]
> This feature is coming to terraform 1.8 so can this be opened up again?
> See comment here https://github.com/hashicorp/terraform/issues/25584#issuecomment-1967957406

#25584 does not seem to be about custom functions:

> the built-in "terraform" provider ... will also now offer three functions covering the main use-cases discussed in this issue.

These are just 3 new functions that will do stuff related to format conversions.

**Comment by schollii** [comment]
Provider-provided functions will be useful when their is a major piece of functionality that is best implemented in a full, procedural PL like golang. The feature also opens the open door to adding libraries of functions that all focus on the same thing, eg string manipulation, now someone can create a string manip provider. 

But it covers a very different use case from this proposal, which is to provide the ability to quickly refactor declarative tf code snippets for re-use in your tf stack, to keep code DRY *easily* by just writing tf code. 

Having to create a provider just so I can have, eg, a function that refactors a complicated loop that is specific to a given module, is totally not practical and totally not what this proposal seeks.

**Comment by janosdebugs** [comment]
Hey folks, yes, this has been presented to the TSC and is being planned for OpenTofu 1.8.

**Comment by reegnz** [comment]
> Having to create a provider just so I can have, eg, a function that refactors a complicated loop that is specific to a given module, is totally not practical and totally not what this proposal seeks.
I think the point is that there will be community projects creating a lot of useful utility functions that are missing from terraform currently and you'd use those.
The end-user would still just write tf code, but utilize the 3rd party utility functions.

**Comment by nitrocode** [comment]
@janosdebugs thanks for the update. Since the feature is now planned for 1.8, could we reopen this ticket? Or is there another ticket for tracking?

**Comment by schollii** [comment]
No @reegnz that is not the point. The point is actually that if I have terraform code with an expression that I want to use in multiple places and the expression depends on a loop var, one cannot currently use a local, and nor is it going to be something available in a provider.

**Comment by cam72cam** [comment]
Alternatively, you could define a provider function to do most of this, something like

```hcl
locals {
  body = "
func myfunc(var1: string, var2: list(string)) => map(string) {
     var3 = ...expression involving var1, var2, and any local.*...
     var4 = ...expression involving previous vars...
     return var3
  }"
  
  value = providers::custom_fn::exec(body, arg1, arg2)
}

```

**Comment by schollii** [comment]
> Part of the problem with implementing this in HCL, is that attributes are not ordered.  They are stored in a map internally.
> 
>... example removed for brevity... 
> 
> Which is problematic when defining a function body.

A map is actually ideal, as it means no positional args. So the syntax might be a tad different from the request, but the idea remains. 

If I'm misunderstanding can you clarify pls.

**Comment by schollii** [comment]
> Alternatively, you could define a provider function to do most of this, something like
> 
> ```hcl
> locals {
>   body = "
> func myfunc(var1: string, var2: list(string)) => map(string) {
>      var3 = ...expression involving var1, var2, and any local.*...
>      var4 = ...expression involving previous vars...
>      return var3
>   }"
>   
>   value = providers::custom_fn::exec(body, arg1, arg2)
> }
> 
> ```

I've looked at that option too but the major problem with defining a custom fn in a string is no intellisense possible. 

It also makes them third class citizens in the language (not even second class). Eg, the tf fn "compiler" would have no way of inspecting the body of the function to eg ensure no side-effects, cycles etc, this would be dependent on the provider's custom fn engine (if done at all). 

In fact I believe that allowing custom functions to be a free for all by tapping into procedural and oo languages would be a big mistake. There are guarantees in terraform that are easy to take for granted and we don't want to lose those. A custom functions capability should uphold those guarantees.

**Comment by cam72cam** [comment]
> A map is actually ideal, as it means no positional args. So the syntax might be a tad different from the request, but the idea remains.

The problem is that we can't re-use a lot of existing HCL structures in that scenario, which increases the significance of the ask.

**Comment by tsarna** [comment]
Leaving this here for anyone who revisits the idea, not to relitigate the closure.

I've recently developed [functy](https://github.com/tsarna/functy), a small language designed for _exactly_ this sort of thing. functy is an imperative language whose values are cty values and whose expressions are real HCL expressions. A compiled functy function is an ordinary `cty.Function` with a static return type, i.e. exactly what Terraform/OpenTofu's function table already holds. It's the natural evolution of the ext/userfunc add-on linked earlier in this thread, with actual control flow (if/for/return), typed params, exceptions/error handling, embedded testing, etc. It's MIT-licensed. 

It addresses several objections raised above:

 * "Attributes are unordered, which is problematic for a function body" (@cam72cam): functy doesn't express bodies as HCL attributes. It has its own ordered statement grammar; only the expressions inside are HCL.

 * ~~String-embedded bodies mean no intellisense / "third-class citizens" / no way to inspect for side-effects or cycles (@schollii, @cam72cam): there's a design for embedding functy cleanly inside an HCL file (a functy { … } region, or sibling .cty files) that keeps the code as real source, not a quoted string. functy reuses HCL's own lexer and only needs a byte-level preprocessing shim, so it addresses the "we don't own HCL and can't change it" concern directly: zero HCL changes required, and functy is maintained as an external library rather than a fork. functy also has tooling already: a CLI with `check`, `fmt`, `symbols` commands, a very basic REPL, and a VS Code extension today. I've started thinking about an LSP.~~ _After more thought I've decided embedding within HCL files is a bad idea (see https://github.com/tsarna/functy/REJECTED.md for reasons), so I'm revising to:_

 * String-embedded bodies mean no intellisense / "third-class citizens" / no way to inspect for side-effects or cycles (@schollii, @cam72cam): functy source lives in its own .cty files, sibling to the .tf files that use them — real source in a real file, not a quoted string, so an editor can actually help you. That is also what makes the inspection question tractable: a function is a parsed declaration with a typed signature, so purity and call-graph cycles are statically checkable before anything is evaluated, rather than properties you'd have to guess at from inside a string. It needs no HCL changes at all — no new syntax, no fork, no preprocessing shim — which addresses the "we don't own HCL and can't change it" concern directly; functy is an external MIT-licensed library, and the expressions inside a function body are literally HCL expressions, parsed by HCL's own parser. Tooling exists today: a CLI with check, fmt, symbols, a basic REPL, and a VS Code extension. I've started thinking about an LSP.

 * "A custom-functions capability should uphold Terraform's guarantees; don't just tap into Lua/procedural runtimes" (@schollii): functy is not a general procedural/OO runtime bolted on. It's cty-native, typed, pure by construction (no side-effecting builtins unless a host injects them. A Terraform/OpenTofu embedding simply wouldn't), deterministic, and statically checkable, with a design for an execution-step limit so an unbounded loop can't wedge a plan. That's the narrow "expressive but still safe" niche this thread was asking for. And, functy was designed specifically to feel native in a HCL-based application, not like suddenly switching to another language.

To be clear about the hard part: doing this in OpenTofu is a core change, not a plugin: a function defined in config has to be injected into the eval context core builds, which a provider can't do. functy removes the "who builds/maintains the function language" objection, but not the governance ones (language surface, an extra eval phase). A lighter-weight path that reuses machinery you've already shipped would be a built-in functy provider that loads local .cty at config-load time and exposes them as provider::functy::name. Essentially, @cam72cam's providers::custom_fn::exec(body, …) sketch, but with the body as real .cty source instead of a string, and with core (not a third-party gRPC plugin) controlling schema timing so local-file loading is legitimate.

Not asking for anything here, just flagging that the missing ingredient (a finished, guarantee-preserving function language ~~, plus a no-HCL-change embedding design~~) now exists, in case it lowers the bar for a future RFC.

**Comment by schollii** [comment]
@tsarna as mentioned elsewhere, very cool!

But since this issue is closed, I would consider opening a new one or, better, starting a thread in Discussions: your proposal is fundamentally different from others I've seen, it's not just asking for the capability, it's proposing integration with an existing tool (yours) that might provide most of the heavy lifting, and that you're willing to help with the integration. 

But I'm not an expert in opentofu source code so maybe there is a major barrier to such integration, barrier is definitely possible. One assumption is that functy meets all platform requirements of opentofu (platforms supported, etc).

Personally I'm not a fan of provider-provided custom functions, the approach is worse than using modules-as-functions and seriously if I just want to refactor a portion of a loop to a function for a stack, I'm not going to create a custom provider, I'm not going to find out if someone from the same company has published one and could add it immediately... the whole notion is preposterous. 

So I would welcome functy-based custom functions as first-class citizen in HCL as long as they can be called at plan time with no state or side effects. Such proposal might also belong on [HCL](https://github.com/hashicorp/hcl), but a new Discussion (on this or HCL repo) would tell you pretty quickly.

**Comment by cam72cam** [comment]
We are actually re-considering adding functions of this style in https://github.com/opentofu/opentofu/pull/4052 [RFC].  If you have any thoughts on what forms that it should take, please go take a look at the proposal!
