### ISSUE TITLE
Do not fail initialization if signing key has expired

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#822]
### OpenTofu Version

```shell
1.6.0-alpha3
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

.

### Expected Behavior

Running `tofu init` should not fail if one of the providers' signing keys are expired

### Actual Behavior

Running `tofu init` does fails if one of the providers' signing keys are expired

### Steps to Reproduce

`tofu init` on a configuration that includes a provider that has been signed by expired signing keys

### Additional Context

`go-crypto` is making the GPG key expiry validation for `tofu`. We'd need to either pick a different package, or to somehow skip this validation / display a warning instead of an error.
An expired key should not fail `tofu init`

### References

- Related issue in the Terraform repository: https://github.com/hashicorp/terraform/issues/33984
- Related issue regarding the current behaviour of having the GPG key validation not be mandatory - https://github.com/opentofu/opentofu/issues/266

**Comment by Yantrio** [comment]
We had a discussion around this one here: #673 . And In my opinion whilst the conversation didn't carry on much, I think there was a general concensus.

Overtime we should get stricter.

I'd love to propose that we do the following (instead of just allowing it):

**For the stable release**
Allow expired gpg keys for now, but display a warning. 

**For the next release**
Add an opt-in variable that forces a stricter mode of verification (allow by default, disallow expired keys if the var is true)

** For a future release **
Look into asserting validation of provider signings by combining both the expiry of the key along with other factors (Generation of sig file, time of provider artifacts being generated, etc etc)

For reference, here's some comments/ideas on this:
- https://github.com/opentofu/opentofu/issues/673#issuecomment-1750950454 @cipherboy discussing attack vectors and even possibilities around keyless approaches
- https://github.com/opentofu/opentofu/issues/673#issuecomment-1751039594 @pdecat mentioning that we could take the github release asset creation date into account.

WDYT @cube2222 @RLRabinowitz

**Comment by MKK711** [comment]
I need help guys I don't know what to do. So Apple iPhone. Broke their most valuable rule about themselves and encrypted my phone while I was sleeping broken into my brand new phone and completely crashed and encrypted and lost my touch ID software and data on my iPhone SE generation two am I identity got stolen my bank account got stolen and all of my social media they stole my phone number my service provider didn't even know what my number was and how I was calling him to pay my phone bill I can't back out of my phone and any direction I go any thing I click on my touch ID is my back button to every program that is now broken and does not exist and the dab platform of my phone because they broke their Number one respected law privacy just to update one of the platforms for a beta that I was testing for them and they couldn't wait a few hours for me to wake up so they did it without me thinking I was not gonna know as I woke up freaking out because I couldn't figure out what I did to my phone Newsflash I didn't do anything the creators of Apple pen and then encrypted my code and broke the brain of my phone as it is not work as it should it is definitely lacking intelligence on top of that I don't know where I should start I lost $43,000 on my bank account I no longer have any access to besides Bank statements and the bank cards and the original contract when it was wrote up and I signed it because I created it with my Social Security number the bank still will not let me verify or access it because they changed some kind of outspoken word you're supposed to say on the phone with them so I lost that my Sim card has some kind of weird encryption on it or something it keeps saying that I have to unlock my Sim card with a puke key I don't know how I access that I also don't know how to access my bank account my phone my Facebook my phone number was even taken and removed from my service provider these people that did this to me I have all documentation of their footprints I don't have faces I don't have names I just have data a little bit of their beta and contracts and messages what they do while they do it it's called imply got databased enhanced cyber intelligence something like that located out of California I was wondering if I could make an agreement with Apple that they are responsible for breaking my finger ID fingerprint security on my phone has there the one reason that this all happened if they never would've broke my fingerprinting security lock on my phone they would've never got $43,000 from me which I only have 37,000 of it to prove that they took and the rest of my Internet access because Apple is all about privacy and one thing today literally honor and live by somebody's privacy they broke their law hacked into my phone just for update no under my understandings these people got the best of me because I'm a tone baby my Social Security number and a lot of my bank statements aren't really looked at and they're bypassed by a lot of movement with large numbers as of the IRS didn't look at me very much as much on larger Bank transfers then the average person because my trust fund under my social Security number is put in and the system I'm tax-free trust fund baby so they don't have to analyze and they're not responsible for any of moneya I've been off for days trying to figure this out and I needed at least at least $33,000.00Thousand of it back to take care of the things I need to take care of my personal information and privacy. That is the most bottom dollar then I can accept without taking them to court if this is even possible my entire identity has been stolen and I'm a victim of fraud the people that took my bank account, I can't access it but I can still see all the activity on my phone. Every transaction sends me a notification. These guys have pushed over a half $1 million and laundering money in my bank account because the IRS don't look at it besides a few months back, they fucked up and flagged them one time where they did contact me and they have my phone so controlled that they hang up my phone calls as the lady just emailed me and basically it was like a verbal warning is all I can say because I've never heard anything else about it bank account are in my name can move larger amounts and transactions and transfers without flag in the IRS then the average citizen because my trust fund money was given to me tax-free and was wrote up like that 28 years ago that being said I've got over 33 different bank accounts in my name and honestly they could care less to look at me because I'm not a threat to them and they just think I'm spending my trust fund money because it was a large amount definitely larger than a half $1 million but unfortunately my daughter's birthday is in 22 hours. I've never met her, but I was planning on surprising the baby mama, putting a smile on her face with a little bit of some money just to be able to lay eyes on my daughter for the first time in my life and I can't do that anymore because I've been robbed of everything I can't even verify my ID they stole that too. A cop pulled me over a month ago or so and forgot to give me my ID back I can't even verify who I am when my identity is stolen and I can't access any of my shit because don't have my ID or any money to make my life a little easier. I'm really sorry that this is being brought to you guys but I got a major case of cyber security here and I know for a fact I probably will never get them most baddest, computer wizard sneaky little conniving as fucked up as it is cyber hackers and coders got the best of me somebody's got to be reliable, and the only person I can prove that to his Apple because this would've not happened if they didn't break my finger scanner on my phone they would've not been able to access any of my data. Maybe couple hundred dollars here and there Facebook social media stuff but not taking my phone number taking my Gmail off my bank account attached it from my Facebook my bank account and my phone number from my service provider as my number never exist and neither did my bank account information and security questions as the same as social media didn't take my keys my platforms, they removed them and took the corporation as my Google Gmail and my iCloud my phone number and my Social Security number are the keys that started all of this they didn't take none of that they removed it and took the cash prize 30 year investment my entire life please help guys I'm supposed to be in Orlando Florida by January 9 to start cyber security college on dorm. I wanted this my whole life and the second that I put my fingertips on the key to accessing my life and open new doors. Somebody comes by and takes it. Funny story how do I get a trust fund my mom died. She dropped me off at a doorstep. She rang the doorbell. She drove off she got hit by a train my dad didn't find me until two years after my mother was already dead my dad raised me until I was 15 broke my face for my ribs, and I'm not seen him or talk to him since he stole for me and my trust fund that he created don't ask me why I didn't even know I had this until I was a certain age long story short, abandoned from my father. Now I get money I'm ready to see my baby and open new doors to this experience of life taken from me. Story of my life I need to know and I need help I need some very honest very trustworthy good friends in my life right now and this is the most trusted card that I have in my hand you guys are the only thing I got I am special in I was in special ed classes in school from kindergarten through graduation I graduated with very low GPA and I always made fun of and bullied my entire life they shoved me in my lockers and yes they did lock my locks putting that behind me I don't care I wanna learn how to go to school in college like every other normal person I'm just a little bit slower but once I learn it I promise you I'll master and I am very committed at everything I do please help me guys I want to be success to my daughter my baby and give her the world that I had to work for my whole life too yet so I worked harder than others because I am slower and it seems a lot gets taken away and makes someways in life more difficult than the average bear I need some trusted Friends please I am out here on my own. Maybe I'll be with me as I need his grace and all of your guises as well as I may need his love as I have very little of it I need more I need your guises I will pray and I will do whatever I can to bless you all as well as God bless their soul thank you for your time sincerely Mr.Halter711
