### ISSUE TITLE
Split second performance through aggressive caching

### ISSUE THREAD

**Issue by cveld** [opentofu/opentofu#888]
### OpenTofu Version

```shell
OpenTofu v1.6.0-alpha5
on linux_amd64
```

### Use Cases

I believe it is essential to have a very performant and productive inner dev loop. Any change in terraform configuration and a rerun of terraform plan/apply workflows incurs some waiting time. This should be minimal.

### Attempted Solutions

I am aware of the `--refresh=false` flag but this does only skip refreshing resources. 

### Proposal

Opentofu should be reengineered from the ground up with performance as a main goal using aggressive caching, essentially providing a watch mode. A reevaluated plan should take few seconds.

### References

We are impacted by the combination of azurerm provider and kubernetes provider and created a ticket on the terraform cli side: https://github.com/hashicorp/terraform/issues/34254

**Comment by theherk** [comment]
I'm unclear on what is being proposed here aside from the vague implication that rather than forking a well established product to maintain its status as an open source community project, a new product should be built with a different architecture.

First, I think it is safe to assume everybody feels performance should be a goal, though how it is prioritized versus safety and security is sometimes worth considering. Therefore, I believe performance is already a goal of the project, accepting there are many places it can and should be improved, unknown though they may be.

What would be helpful here are precise examples of what data can be cached or more aggressively cached than the current architecture. As it stands, generating a plan requires comparing the state the requested configuration. As far as the tofu executable is concerned it is limited to provider dependency resolution, acquisition, and execution; the first two which can be extremely fast because they are already cached and the third is entirely in the hands of the provider. Getting values from the various clouds can probably be a bit faster in many cases depending on how the provider is designed to acquire these values, but that is strictly outside of tofu. Tofu already does this in parallel in all cases that the dependency tree allows.

I am interested in what you're suggesting, and I don't mean to sound blithe, but please articulate you suggestion in a bit more detail. Also, to clarify I'm not a maintainer, just an interested participant.

**Comment by cube2222** [comment]
Hey, thanks for creating the issue @cveld!

> Opentofu should be reengineered from the ground up

I'll be fairly direct here - realistically, I don't see this happening. Both because of bigger priorities, and also seeing what "big bang rewrites" usually end up accomplishing (failure). Thus, I encourage you to propose specific improvements that we could make.

Regarding the watch mode and caching, I think an enhancement that could be proposed, and would I think be possibly realistic to do in an incremental way, is plan caching. For example, if a subgraph of resources hasn't changed, including the set places referencing it, then we can reuse a plan that we already have cached somewhere. With such an approach we might be able to drastically reduce the time needed to do a replan if only a single resource changes / is added.

**Comment by janosdebugs** [comment]
Having written a provider in the past, I found that a lot of the time spent isn't actually building the plan, it's the provider waiting for API calls to happen. The `plan` itself reaches out to the remote APIs for information on the current state (e.g. the AWS API), which is fairly slow in comparison to locally computing a plan. Even if you get an incremental plan, it still won't be a "live edit" feeling you may be accustomed to, it's still going to take a little while for the plan to come together. If you want an incremental `apply` instead of a `plan`, it will be several minutes, depending on the provider you are using, at which point monitoring filesystem changes is a bit pointless.

My additional worry would be that your code is being written from possibly invalid assumptions as not the entire plan is being executed. One of the strengths of TF compared to other tools is that when a plan is known to work, it is replicable to a very high degree. Run the code again, get the same results.

I would try to build reusable modules, test them separately, and then integrate them. If a live edit is needed, I'd use the filesystem watcher functionality included in most IDEs.

**Comment by theherk** [comment]
Hmm, you may have stumbled into something interesting @ArbitraryCritter. At least, it piqued my curiosity. I am wondering about explicit targeting done via the hcl. For example a lifecycle attribute that allows the configuration to specify that if the graph shows no dependent or reliant resources have configuration updates, treat this as though it is specified as targeted. By way of example,

```tf
  lifecycle {
    target_if_isolated = true
  }
```

Being functionally equivalent to `--target` if nothing it depends on or which depends on it are eligible.

I'm confident this is a terrible idea, but I can't say why yet, so I'm invoking Cunningham's Law here.

**Comment by janosdebugs** [comment]
Hey folks, thank you very much for the issue and comments and apologies for the late reply. We have discussed this issue in the core team and feel that the implementation as requested here would be a massive undertaking. Furthermore, for most use cases the API rate limiting most provider APIs impose will be a far larger factor in the planning than the actual planning algorithm. As such, we have decided to close this issue.

However, we are well aware that the entire plan can take up significant time and would be open to an issue that discusses supporting partial plans in detail, especially when supported by actual use cases that cannot be otherwise addressed.
