### ISSUE TITLE
[RFC] Adding a new Provider/Module to the Stable Registry

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#895]
# Overview

This proposal is part of the [Homebrew-like Registry Design](https://github.com/opentofu/opentofu/issues/741).

This proposal lays out how providers and modules could be added to the registry. This proposal attempts to make the process  as easy as possible to the contributor wishing to add a new provider or module to the registry.

Basically, new providers and modules could be added to the registry via a PR that introduces a new valid provider or module JSON metadata file. In order to streamline the action, and to not require each contributor to clone the registry repository, we'll provide a binary CLI which will let contributors easily open PRs for new providers/modules

So here I'll explain how this will work:

## tofu-registry-tool CLI

The registry will provide a binary that will allow a contributor to immediately create a PR with the new provider or module. All the CLI will require as input is the user's GitHub token, and the full name of the provider / module.

The CLI will then attempt to create a fork of the registry repository, then it will create a metadata JSON file for the provider/module, commit it to a new branch, and create a PR to the base registry repository

### Using the CLI

You'll need:
- A GitHub token with permissions to create forks, create branches and files, create Pull Requests
- The details of the provider / module
  - For a provider, the "namespace" and "name" of the provider, in the following format: `<NAMESPACE>/<NAME>`
  - For a module, the "namespace", "name" and "target system" of the module, in the following format: `<NAMESPACE>/<NAME>/<TARGET_SYSTEM>`

Use the CLI as follows: `tofu-registry-tool add-provider oracle/oci --token <MY_GH_TOKEN>` or `tofu-registry-tool add-module terraform-aws-module/lambda/aws --token <MY_GH_TOKEN>`

### How the CLI will work

- Check that all relevant inputs were received (GitHub token, provider's namespace and name / module's namespace, name and system)
- Check if the registry repository already has a metadata file for the provider/module, via GitHub API. If the file exists - then exit, as the provider/module exists in the registry
- Check if there ever existed Pull Requests in the registry repository for this provider / module. If there have - then exit, as we don't want to create another Pull Request
  - Check Open as well as Closed Pull Requests
    - Closed Pull Requests are checked to avoid spamming the registry with unwanted providers/modules
    - However, a Pull Request might be closed by mistake or by the contributor themselves, making creating a new PR for the provider/module harder. So we might want to skip looking at closed PRs or introduce some `--force` flag for such a case
  - Check for PRs matching in name to expected generated PR name `New Provider/Module: XXX`
- Create the contents of the new provider/module metadata file. This would be done similarly to how we bump versions for existing providers/modules, by using the GitHub API to list releases and by downloading artifacts where necessary
- Create fork for the registry repository, if one doesn't exist yet for the current GitHub token's user. Wait for it to actually be created (API resolves correctly but it takes a few seconds for GitHub to create the forked repository)
- Create a branch and commit the provider/module file to it via GitHub API
- Create a PR to the base registry repository. In the description write `generated by tofu-registry-tool`
- Print out the PR URL

### Building and Publishing the CLI

The `tofu-registry-tool` CLI should be built and released using the golang source code of the registry repository. The OpenTofu docs would later mention how to download the CLI and use it, in order to add a new provider/module to the registry

### Adding a GPG key for a new provider

For now, this RFC assumes that GPG keys could only be added to **existing** providers of the registry. 

However, we could change that in the future, and have the CLI also accept a public GPG key, to be uploaded in the PR alongside the provider metadata file. Then, the PR would behave similarly to what's described in the [GPG key verification RFC](https://github.com/opentofu/opentofu/issues/832), under "Automation", running automated checks verifying the GPG keys uploaded 

### Approval and Merge of new Providers and Modules

When new Pull Requests are opened, the core maintainers of OpenTofu would manually go over the Pull Request, and decide whether the change is OK and legitimate and can be put into the registry.

There are some CI automations the core team might put in place to help validate the authenticity of the provider/module (like validating the artifacts and their SHASUM values).

### Justification and Tradeoffs

This approach tries making the action of adding providers and modules to the registry as simple as possible, without requiring a contributor to be fully aware of the registry repository and how it works

This approach does require human oversight and approval for addition of new providers and modules to the registry, however this could re-evaluated in the future if necessary

**Comment by kislerdm** [comment]
Hey Arel! Thank you for the proposal - looks great!

I'd share a couple of proposals for further discussion.

- WDYT about adding CLI functionality as a `tofu` command? Motivation: ease of adoption because users won't need to install an additional tool. To illustrate, new provider/module/gpg key can be submitted by executing the following commands:
```commandline
# to create new provider in the OpenTofu registry:
tofu registry add provider <NAMESPACE>/<NAME>

# to create new module in the OpenTofu registry:
tofu registry add module <NAMESPACE>/<NAME>/<TARGET_SYSTEM>

# to create a new GPG key in the OpenTofu registry:
tofu registry add gpg-key <KEY_NAME> --path <PATH/TO/KEY>
```
It can be extended by adding commands to delete provider/module/key and to submit new provider/module version. For example, users could submit new version of provider by running: `tofu registry add provider <NAMESPACE>/<NAME> --version <VERSION>`. Furthermore, the command of submitting new version can be included to github workflow to notify OpenTofu registry of a newly released version. In a way, it's similar to how terraform registry is notified using webhooks.

- WDYT about reading GH key from the environment as a fallback to the command line argument?

Thanks!

**Comment by RLRabinowitz** [comment]
This could be a `tofu` command, but the code here should be aligned with the registry repository's code. A change in repository code would probably require us to change the CLI accordingly. Also, I'm not sure we'd want to inflate the `tofu` CLI with "dev" commands right now, but it's a possibility

I like the `add` subcommand compared to `add-provider`/`add-module` subcommands

> WDYT about reading GH key from the process environment (env variable) as a fallback to the command line argument?

I preferred having the token be a mandatory field when using to CLI to be more explicit, but an environment variable is also a valid option

**Comment by Yantrio** [comment]
A few comments/thoughts about this:

## Comments
> tofu-registry-tool CLI

adding `-tool` as a suffix feels like overkill, what about `tofu-registry`?

> All the CLI will require as input is the user's GitHub token, and the full name of the provider / module.

I would prefer browser based/oauth like what what the github CLI does. This ensures that users do not accidentally create PATs that could leak their information. However I'm aware some people may want to run this inside CI/CD so we should also look for `GITHUB_TOKEN` to grab that if it exists instead.

> Create the contents of the new provider/module metadata file. 

If this is the case, I would like to make some of this generation available to a public package so that other people can consume this code too if possible. (Right now it's an internal package in the registry-stable repo). Even if it's just the types so that we end up with a data contract (Similar to hashicorp/terraform-json)

Also:
**- How can we disuade people from generating these PRs manually?** 
We need to liberally add notes in the README.md, opentofu.org website, PR templates to ensure we drive people to use the tool.

**- Where does this code go?**
I think right now this should go inside the registry repo, and that's where we should distribute releases too.

**- Is there a possibility we could wrap something like the `gh` cli to acheive a lot of this, or do we require to write our own?**
WDYT?

## Summary
Overall I like the approach: I feel like users can then use this to integrate into their workflows nicely.

**Comment by serdardalgic** [comment]
Hi folks! 
Great RFC again, @RLRabinowitz, thanks! (No Lady Gaga GIF this time, though :) ) 

My random thoughts and comments: 

* +1 to @Yantrio on this one
> adding -tool as a suffix feels like overkill, what about tofu-registry?

Also, I'd prefer the tofu-registry tool as a separate tool instead of a tofu command. I think there should be a distinction between the practitioners (users of OpenTofu) and the module/provider maintainers. 

* About GH Token/PAT env var and the CLI argument for that:
I think both should exist. I'd even vote for using the env var only. 

* About the subcommands:
I'm a big fan of https://clig.dev/ to standardize the CLI commands. The current command set we're using in OpenTofu (and Terraform) is a mix of `verb noun` and `noun verb` type of [subcommands](https://clig.dev/#subcommands). At some point in the future, it would benefit to standardize the commands, but that's a long shot. 
For the `tofu-registry` command, I'd propose/vote for the `tofu-registry provider <verb>` and `tofu-registry module <verb>`.

* Another +1 goes to creating the provider/module metadata-generation code as a public package

* Wrapping around gh cli: 
Is there a huge advantage using GH cli instead of directly calling the GH API endpoints? I'm not using the GH cli in everyday life, so I wonder if it would be worth introducing this dependency. I'd be happy to hear your thoughts on that. 

* One small suggestion: 
> Create a PR to the base registry repository. In the description write generated by tofu-registry-tool

This can also be a GH label in the registry repository
