### ISSUE TITLE
Native Version Handling Similar to TFSwitch

### ISSUE THREAD

**Issue by devopsmerc** [opentofu/opentofu#926]
### OpenTofu Version

```shell
OpenTofu v1.6.0-dev
on darwin_arm64
```

### Use Cases

Over time there will be more versions of tofu available and it would be nice to programatically select the version you would like to use.  

TF switch is a project that lets you specify the TF verison you want to use and updates a symlink.  We regularly use it in pipelines to test against multiple versions.  Simplifying what it does: reads various config locations to determine which version you want to use, downloads that version if needed to a local file with the version number included, then sym links "terraform" to that binary.   

### Attempted Solutions

I haven't attempted to write a solution yet.  I would be interested in helping once/if the community shown a preference. 

### Proposal

It would be nice if that functionality was natively added to tofu. It could be handled a few different ways.  
- separate install_tofu binary which takes a --version option which downloads and links to tofu
- an option like "--use-version" that you could specify to target a version
- have tofu use the required_version parameter in the terraform block to specify and pull the required version. 

### References

https://tfswitch.warrensbox.com/Quick-Start/

**Comment by janosdebugs** [comment]
Hi @devopsmerc this sounds like something that would be an excellent addition to TFSwitch itself. I don't know how we would provide such a functionality in tofu since there are [several installation methods](https://opentofu.org/docs/intro/install/), most of which wouldn't support this behavior or have their own version switching built in.

OpenTofu versions can be listed using the GitHub API and can also be downloaded from there (see [this sample script](https://opentofu.org/docs/intro/install/portable)). Looking at the TFSwitch source code, it would be fairly simple to add it there.

**Comment by kislerdm** [comment]
Hey @devopsmerc! Thanks for your suggestion. 

AFAIK tfswitch will support OpenTofu. Please find details in the [issue](https://github.com/warrensbox/terraform-switcher/issues/315). I agree with @janosdebugs, and would rather suggest to contribute to tfswitch instead of making another version manager.

Alternatively, please consider using tfenv: OpenTofu support is about to be [added](https://github.com/tfutils/tfenv/pull/411) there.

**Comment by kislerdm** [comment]
Instead or a manual version switching, the functionality enabling for forward compatibility would be valuable. With this feature, `tofu` will read the state file and would attempt to use the `tofu` version from there if it's newer. 

For example, similar behavior was implemented in [go1.21](https://go.dev/doc/toolchain).

**Comment by roni-frantchi** [comment]
I'm in agreement with the rest of the core team - I think at this point think we should contribute to supporting Tofu in `tfenv` and `tfswitch`.

**Comment by kislerdm** [comment]
Hello @devopsmerc! Thank you for your contribution!

Based on the core team agreement, it was decided to maintain OpenTofu support in existing version managers, `tfswtich` and `tfenv`, instead of introducing another one. 

The rationale: 
- _Discoverability_: the teams which use the mentioned version manager(s) will require almost no extra effort to start with `tofu`.
- _Community adoption_: existing version managers are widely adopted; a significant avoidable effort will be required for adoption of yet another tool.
- _Interoperability_: existing tools will enable for more smooth transition from terraform to tofu.

This issue is being closed because the RFC considered concluded. 

Please feel free to share more proposals, or contribute to execution of this RFC by contributing to tfswtich which you mentioned as a reference.

Thanks!

**Comment by kvendingoldo** [comment]
Hello there,
[Tofuenv's](https://github.com/tofuutils/tofuenv) first stable release (v1.0) is now available! tofuenv is a fork of tfenv that only works with OpenTofu binaries. Our crew (me, @anastasiiakozlova245, @Nmishin) has been working on the fork over the past week. We worked hard to improve the usability of core [tofuenv](https://github.com/tofuutils/tofuenv) features, add some new capabilities, and, of course, fix a few bugs in the original [tfenv](https://github.com/tfutils/tfenv) program.

We'd appreciate your input and support on GitHub. Please feel free to submit issues and make contributions. Link to tofuenv: https://github.com/tofuutils/tofuenv

tofuenv can be installed manually from GitHub or via brew (for mac users).

**Comment by kvendingoldo** [comment]
A small update: my team created [tenv](https://github.com/tofuutils/tenv) that is a replacement for tofuenv. 

[tenv](https://github.com/tofuutils/tenv) support version management for OpenTofu as well as for Terraform and Terragrunt. 
You're welcome to open any issues or contribute it!
