### ISSUE TITLE
Document provider development

### ISSUE THREAD

**Issue by janosdebugs** [opentofu/opentofu#982]
We don't have our own SDK yet, but many have asked about developing a provider and there are [quirks](https://github.com/orgs/opentofu/discussions/975) that need to be documented.

**Comment by Kazzhar** [comment]
Hi, I would like to work on this issue.

**Comment by Kazzhar** [comment]
Hi, thanks for assigning this to me. I estimate that I would need until the end of this week to get this done. 

To quickly confirm that my understanding of this issue is right: 
OpenTofu uses the Terraform plugin SDK to develop plugins, and users run into a problem while setting `TF_ACC_TERRAFORM_PATH` to the tofu binary. Additionally ```TF_ACC_PROVIDER_NAMESPACE="hashicorp"
TF_ACC_PROVIDER_HOST="registry.opentofu.org"``` have to be set, and this needs to be documented [here](https://opentofu.org/docs/language/providers/#how-to-develop-providers) under "How to Develop Providers".

Please correct me if I am wrong.

**Comment by janosdebugs** [comment]
@Kazzhar yes, these settings seem to be correct.
