### ISSUE TITLE
Propose enhancements for install shell scripts

### ISSUE THREAD

**Issue by srjennings** [opentofu/opentofu#992]
### OpenTofu Version

```powershell
tofu --version
OpenTofu v1.6.0-alpha2
on windows_amd64
```

```bash
tofu --version
OpenTofu v1.6.0-alpha2
on linux_amd64
```

### Use Cases

Improved compatibility for machines installing Tofu.
There is:

1. No error handling
2. Lack of user assistance
3. Lack of compatibility for multiple shells

### Attempted Solutions

Code enhancements are required. I have a PR ready but, anticipating it was going to be rejected per guidance in https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md -- I have held off on making the PR.

### Proposal

Install scripts should be:
1. Modular
2. Backwards compatible for a wide-install base
3. Use appropriate logging to ensure the user knows what to do in the case of an error

### References

I have submitted an issue (and a related PR) as an attachment to this request: https://github.com/opentofu/opentofu/pull/991

**Comment by janosdebugs** [comment]
Hi @srjennings thank you very much for your contribution, such quality improvements are always very welcome.

The original intention was to provide a relatively simple starting point for people to develop their own script, not to provide a fully supported automatable installation method. Other tools, such as tfenv, tfswitch, or tfvm already provide much more robust automation and they are in the process of getting support for OpenTofu. However, that sentiment may be wrong and we should indeed provide more robust scripts for copy-pasting. I'll let my fellow maintainers chime in on this one. (@opentofu/core-engineers do you have any thoughts on this?)

My main concern with your draft PR is the size of the script that people are being asked to start working from. It's a bit unwieldy (observe the scroll bar on the right, this is a 4K monitor at 200% zoom):

![Screenshot of the portable installation page](https://github.com/opentofu/opentofu/assets/86970079/e2d2c5d0-3d35-494e-b335-e6d90474b09b)

Maybe the convenience script proposed in #979 could benefit from your improvements much more than this script? It will support downloads from GitHub in parallel to OS package installations to better suit our needs than the current Packagecloud script. Once that script is up, we could even remove the current snippet and point people to that script for automation.

**Comment by janosdebugs** [comment]
On that note, I started putting the new convenience script together [here](https://github.com/opentofu/opentofu/pull/994). @srjennings it's not anywhere near done yet, but if you feel like reviewing it (especially when it's done), your input is much appreciated. I'm also very curious about your thoughts on the installation manual page, please share your thoughts.

**Comment by janosdebugs** [comment]
Hi @srjennings thank you for your explanation. I'm a Windows user (with heavy WSL usage) myself, so I absolutely understand your need here. Interestingly enough, [@kdpuvvadi added OpenTofu to `winget`](https://github.com/microsoft/winget-pkgs/pull/129995) and keeps updating it, so you should be able to just install it that way. We didn't know until a few days ago, which is why it is not in the install docs at all. Ideally, we'd consolidate updating platforms such as `winget` and `choco` as a GitHub Action from the main repository so we can be sure that all "officially" documented distribution points stay up to date at all times.

As far as zsh is concerned, the new convenience script should hopefully take care of that. I'm painfully aware of my over-reliance on Bash features, it's a bad habit, and I plan to address that with some container-based testing with the new script.

If you are not opposed to it, we could close your PR for now. As for the snippet, I believe the best way to move forward would be to simply point people to the GitHub Releases page for the download and offer them the convenience script as an easy way to install OpenTofu in a portable fashion. We can make a decision on that at a later time.

If you have time to review the draft PR (especially the `install.sh` file), I'd be happy for any input you have. I'm sorting out the tooling around GPG signing at the moment, but I'll hopefully be able to return to the script around the end of this week.

Thank you for the time and thought you put into this issue, your feedback is really valuable.

**Comment by janosdebugs** [comment]
@srjennings we moved the convenience script to its own repo, please see opentofu/get.opentofu.org#1 for the work in progress. Any comments you may have about that script are very welcome.

**Comment by janosdebugs** [comment]
Happy holidays @srjennings, we'll finish this in January :)
